/* Generated by ui/scripts/gen-bindings.mjs from ipc.json (app.exe --dump-schema). Do not edit. */

/**
 * The Console's classes (docs/design/README.md: FAIL, INFO and OK; WARN for the amber lines).
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "LineClass".
 */
export type LineClass = 'FAIL' | 'WARN' | 'INFO' | 'OK';
/**
 * Where a line came from. Lines are classified by content, never by stream (laydown, Traps).
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Stream".
 */
export type Stream = 'stdout' | 'stderr';

/**
 * The app's command results and events, dumped by app.exe --dump-schema. Do not edit.
 */
export interface IpcBindings {
  cmd_error: CmdError;
  events_probe_report: EventsProbeReport;
  float_probe: FloatProbe;
  prepared: Prepared;
  project_info: ProjectInfo;
  run_event_batch: RunEventBatch;
  startup_info: StartupInfo;
}
/**
 * An error for the UI: a stable reason code and a message for people.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CmdError".
 */
export interface CmdError {
  code: string;
  message: string;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "EventsProbeReport".
 */
export interface EventsProbeReport {
  batch_period_ms: number;
  elapsed_ms: number;
  lines: number;
  stats: BatchStats;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "BatchStats".
 */
export interface BatchStats {
  batches: number;
  events: number;
  /**
   * Batches the sink refused (the webview went away, for example).
   */
  send_failures: number;
}
/**
 * What each reader made of a JSON array of numbers: the bits as `0x` + 16 hex digits.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "FloatProbe".
 */
export interface FloatProbe {
  /**
   * How many values the two readers disagree on.
   */
  disagreements: number;
  /**
   * Read with the core's exact reader, as every schema value from the UI is.
   */
  exact_bits: string[];
  /**
   * Read with `serde_json::from_str`, as a command argument typed `f64` would be.
   */
  serde_json_bits: string[];
}
/**
 * A prepared buffer: take it with `token`; `checksum` is [`checksum`] of its bytes.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Prepared".
 */
export interface Prepared {
  bytes: number;
  checksum: number;
  prepare_ms: number;
  token: number;
}
/**
 * What the chrome shows about the open project: names and counts, never an acoustic value.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  active_variant?: string | null;
  can_redo: boolean;
  can_undo: boolean;
  faces: number;
  id: string;
  materials: number;
  name: string;
  path?: string | null;
  point_receivers: number;
  sources: number;
  surface_groups: number;
  surface_receivers: number;
  variants: VariantInfo[];
  vertices: number;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "VariantInfo".
 */
export interface VariantInfo {
  id: string;
  name: string;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "RunEventBatch".
 */
export interface RunEventBatch {
  /**
   * 0, 1, 2, ... per run.
   */
  batch: number;
  events: RunEvent[];
  /**
   * The producer has finished; no batch follows.
   */
  last: boolean;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "RunEvent".
 */
export interface RunEvent {
  class: LineClass;
  /**
   * 0, 1, 2, ... per run, so the UI can prove it lost nothing and kept the order.
   */
  seq: number;
  stream: Stream;
  /**
   * Milliseconds since the run started.
   */
  t_ms: number;
  text: string;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "StartupInfo".
 */
export interface StartupInfo {
  app_version: string;
  project?: ProjectInfo | null;
  project_error?: CmdError | null;
  selftest: boolean;
  tauri_version: string;
  webview: WebviewInfo;
}
/**
 * The webview engine and its runtime version, for the self-test and the Console.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "WebviewInfo".
 */
export interface WebviewInfo {
  engine: string;
  /**
   * `None` when the runtime cannot be queried (it is then missing or broken).
   */
  version?: string | null;
}
