/* Generated by ui/scripts/gen-bindings.mjs from ipc.json (app.exe --dump-schema). Do not edit. */

/**
 * A named entity of the project. In JSON: `{"kind": "material", "id": "<uuid>"}`; any other
 * key is refused.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "EntityRef".
 */
export type EntityRef =
  | {
      id: string;
      kind: 'surface_group';
    }
  | {
      id: string;
      kind: 'material';
    }
  | {
      id: string;
      kind: 'source';
    }
  | {
      id: string;
      kind: 'point_receiver';
    }
  | {
      id: string;
      kind: 'surface_receiver';
    }
  | {
      id: string;
      kind: 'fitting_zone';
    }
  | {
      id: string;
      kind: 'variant';
    };
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "IssueSeverity".
 */
export type IssueSeverity = 'error' | 'warning';
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CheckVerdict".
 */
export type CheckVerdict = 'ok' | 'refused';
/**
 * The Console's classes (docs/design/README.md: FAIL, INFO and OK; WARN for the amber lines).
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "LineClass".
 */
export type LineClass = 'FAIL' | 'WARN' | 'INFO' | 'OK';
/**
 * Octave or third-octave bands.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "BandKind".
 */
export type BandKind = 'octave' | 'third_octave';
/**
 * `bfreq@loi`, one law for every band or one per band.
 */
export type ReflectionLaws = ReflectionLaw | ReflectionLaw1[];
/**
 * The same law in every band.
 */
export type ReflectionLaw =
  ('specular' | 'lambert' | 'w2' | 'w3' | 'w4' | 'semi_diffuse') | 'uniform';
/**
 * How a surface reflects the diffuse part of the energy: `type_surface/bfreq@loi`, the solver's
 * `REFLECTION_LAW` (`lib_interface/coreTypes.h:83-92`). The discriminant is the solver code.
 *
 * SPPS draws a diffuse reflection with probability equal to the scattering coefficient
 * (`spps/CalculationCore.cpp:318`), so the law has no effect at scattering 0.
 * [`ReflectionLaw::SemiDiffuse`] has no case in SPPS's `ReflectionLaws::SolveReflection`
 * (`spps/tools/dotreflection.h:23-45`) and falls to its default, a specular reflection.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "ReflectionLaw".
 */
export type ReflectionLaw1 =
  ('specular' | 'lambert' | 'w2' | 'w3' | 'w4' | 'semi_diffuse') | 'uniform';
/**
 * The shape of a level spectrum across the project's bands.
 *
 * In JSON: `{"kind": "pink"}`, `{"kind": "white"}` or `{"kind": "custom", "relative_db": [...]}`.
 * Extra keys are refused for every kind: serde's derive alone would read
 * `{"kind": "pink", "relative_db": [...]}` as pink and drop the levels, so the reader is written
 * by hand.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "SpectrumShape".
 */
export type SpectrumShape =
  | {
      kind: 'pink';
    }
  | {
      kind: 'white';
    }
  | {
      kind: 'custom';
      /**
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      relative_db: (number | string)[];
    };
/**
 * Source directivity: `source@directivite`, the solver's `SOURCE_TYPE`
 * (`lib_interface/coreTypes.h:96-104`). See [`Directivity::solver_code`].
 *
 * In JSON: `{"kind": "omni"}`, `{"kind": "unidirectional", "direction": [x, y, z]}`, ...
 * Extra keys are refused for every kind. (serde's derive alone would read
 * `{"kind": "omni", "file": "balloon.txt"}` as omni and drop the file, so the reader is written
 * by hand.)
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Directivity".
 */
export type Directivity =
  | {
      kind: 'omni';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      direction: [number | string, number | string, number | string];
      kind: 'unidirectional';
    }
  | {
      kind: 'plane_xy';
    }
  | {
      kind: 'plane_yz';
    }
  | {
      kind: 'plane_xz';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      direction: [number | string, number | string, number | string];
      file: string;
      kind: 'balloon';
    };
/**
 * Where a surface receiver lies.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "SurfaceReceiverShape".
 */
export type SurfaceReceiverShape =
  | {
      groups: string[];
      kind: 'scene';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      a: [number | string, number | string, number | string];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      b: [number | string, number | string, number | string];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      c: [number | string, number | string, number | string];
      kind: 'cutting_plane';
      /**
       * A float. Finite values are numbers; non-finite values are strings.
       */
      resolution_m: number | string;
    };
/**
 * Where a line came from. Lines are classified by content, never by stream (laydown, Traps).
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Stream".
 */
export type Stream = 'stdout' | 'stderr';
/**
 * A material's reflection law: one law for every band, or one per band. The solvers read it per
 * band (`type_surface/bfreq@loi`, `base_core_configuration.cpp:210-219`), and upstream's GUI
 * keeps one per band (the `loi` list of each row, `e_data_row_materiau.h:218`): tutorial 3's
 * material 100 is Lambert in the six octave bands and specular in the others.
 *
 * In JSON: one law, `"lambert"`, or one per band in the band set's order,
 * `["specular", "lambert", ...]`. [`ReflectionLaws::from_bands`] gives the single spelling
 * whenever every band has the same law.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "ReflectionLaws".
 */
export type ReflectionLaws1 = ReflectionLaw | ReflectionLaw1[];

/**
 * The app's command results and events, dumped by app.exe --dump-schema. Do not edit.
 */
export interface IpcBindings {
  cmd_error: CmdError;
  edit_outcome: EditOutcome;
  events_probe_report: EventsProbeReport;
  float_probe: FloatProbe;
  prepared: Prepared;
  project_info: ProjectInfo;
  run_event_batch: RunEventBatch;
  scene_state: SceneState;
  startup_info: StartupInfo;
}
/**
 * An error for the UI: a stable reason code and a message for people.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CmdError".
 */
export interface CmdError {
  code: string;
  message: string;
}
/**
 * The result of `edit_apply`, the checked apply (PLAN.md 1.8).
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "EditOutcome".
 */
export interface EditOutcome {
  /**
   * False when the validator refused the edit: the project and its history are unchanged.
   */
  applied: boolean;
  /**
   * The new errors the edit would have introduced.
   */
  refusals: UiIssue[];
  state: SceneState;
}
/**
 * A validator issue as the UI shows it: the UI code and the core rule, both.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "UiIssue".
 */
export interface UiIssue {
  /**
   * The UI code ([`ui_code`]), e.g. `RECEIVER_OUTSIDE`.
   */
  code: string;
  /**
   * The entity the pointer names, resolved in the issue's own project.
   */
  entity?: EntityRef | null;
  /**
   * The pointer after the entity, e.g. `position` or `absorption/3`; empty when there is no
   * entity or the pointer names the entity itself.
   */
  field: string;
  message: string;
  /**
   * The validator's JSON pointer into the project.
   */
  path: string;
  /**
   * The core's rule code, e.g. `receiver_outside_volume`.
   */
  rule: string;
  severity: IssueSeverity;
}
/**
 * The state of the open project as the M10 UI shows it. Returned by every M10 command.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "SceneState".
 */
export interface SceneState {
  /**
   * The model check of the current geometry; `None` when the project has no faces.
   */
  check?: CheckSummary | null;
  /**
   * One per surface group, in project order.
   */
  groups: GroupStats[];
  info: ProjectInfo;
  /**
   * The validator's issues on the current project, with their UI codes.
   */
  issues: UiIssue[];
  /**
   * Console lines produced since the last state was returned.
   */
  lines: LogLine[];
  /**
   * Why Run is disabled, as UI codes. Never empty in M10: `M11_PENDING` is always present.
   */
  run_blockers: string[];
  view: ProjectView;
}
/**
 * The model check, for the Geometry panel and the view's highlight.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CheckSummary".
 */
export interface CheckSummary {
  area_m2: number;
  /**
   * The bounding box of the vertices the faces use.
   *
   * @minItems 3
   * @maxItems 3
   */
  bbox_min: [number, number, number];
  counts: CheckCounts;
  enclosed_volume_m3: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  extents_m: [number, number, number];
  /**
   * Every face any reason names, ascending, unique.
   */
  highlight_faces: number[];
  /**
   * In the core's reason order; empty exactly when the verdict is ok.
   */
  reasons: CheckReasonOut[];
  verdict: CheckVerdict;
}
/**
 * The check's counts that the UI shows.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CheckCounts".
 */
export interface CheckCounts {
  /**
   * Open edges on the outer shell, after analysis.
   */
  boundary_open_edges: number;
  cells: number;
  coincident_vertices: number;
  components: number;
  degenerate_faces: number;
  duplicate_faces: number;
  edges: number;
  exterior_faces: number;
  faces: number;
  invalid_faces: number;
  inverted_faces: number;
  nonmanifold_edges: number;
  /**
   * Census edges used once (by index, before analysis).
   */
  open_edges: number;
  self_intersecting_faces: number;
  self_intersecting_pairs: number;
  vertices: number;
}
/**
 * One reason the check refused the geometry.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "CheckReasonOut".
 */
export interface CheckReasonOut {
  /**
   * The core's stable reason code (`open_boundary`, ...).
   */
  code: string;
  /**
   * How many findings, as the message counts them.
   */
  count: number;
  /**
   * How many faces are involved.
   */
  faces: number;
  message: string;
  repairable: boolean;
}
/**
 * A surface group's geometry facts, and whether it has a real material.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "GroupStats".
 */
export interface GroupStats {
  area_m2: number;
  /**
   * False when its effective material under the active variant is the placeholder
   * ([`is_placeholder`]).
   */
  assigned: boolean;
  faces: number;
  id: string;
}
/**
 * What the chrome shows about the open project: names and counts, never an acoustic value.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "ProjectInfo".
 */
export interface ProjectInfo {
  active_variant?: string | null;
  can_redo: boolean;
  can_undo: boolean;
  /**
   * Changed since it was last saved or opened, or never saved.
   */
  dirty: boolean;
  faces: number;
  /**
   * Changes whenever the geometry can have changed; the UI refetches the mesh on a change.
   */
  geometry_rev: number;
  /**
   * Surface groups whose effective material is not the import placeholder
   * (`scene::is_placeholder`).
   */
  groups_assigned: number;
  id: string;
  materials: number;
  name: string;
  path?: string | null;
  point_receivers: number;
  /**
   * Entries on the redo stack.
   */
  redo_depth: number;
  sources: number;
  surface_groups: number;
  surface_receivers: number;
  /**
   * Entries on the undo stack.
   */
  undo_depth: number;
  variants: VariantInfo[];
  vertices: number;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "VariantInfo".
 */
export interface VariantInfo {
  id: string;
  name: string;
}
/**
 * One Console line.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "LogLine".
 */
export interface LogLine {
  class: LineClass;
  text: string;
}
/**
 * The project without its mesh; the mesh travels as bytes (`scene_mesh`).
 */
export interface ProjectView {
  active_variant?: string | null;
  bands: BandSet;
  description: string;
  materials: Material[];
  name: string;
  point_receivers: PointReceiver[];
  sources: Source[];
  surface_groups: SurfaceGroup[];
  surface_receivers: SurfaceReceiver[];
  variants: Variant[];
}
/**
 * The frequency bands every per-band value in the project is given on.
 *
 * `frequencies_hz` holds nominal centre frequencies of `kind`, strictly ascending. The solvers
 * sort `freq_enum` and map every per-band array by sorted position, so ascending order here is
 * the order of every per-band array in the project.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "BandSet".
 */
export interface BandSet {
  frequencies_hz: number[];
  kind: BandKind;
}
/**
 * A surface material: `surface_absorption_enum/type_surface`.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Material".
 */
export interface Material {
  /**
   * Absorption coefficient per band, 0 to 1 (`bfreq@absorb`).
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  absorption: (number | string)[];
  /**
   * Display colour.
   */
  color: string;
  /**
   * `@side_material`: the material acts on both sides of a face.
   */
  double_sided: boolean;
  id: string;
  name: string;
  reflection_law: ReflectionLaws;
  /**
   * Scattering coefficient per band, 0 to 1: the share of reflections that are diffuse
   * (`bfreq@diffusion`).
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  scattering: (number | string)[];
  /**
   * A pinned solver id (`type_surface@id`, the `.cbin` face `idMat`). `None` lets export
   * assign one. Importers set it so that a project imported from a solver mesh exports the
   * same ids and still matches that mesh. At most [`SOLVER_INT_MAX`]: the solver reads
   * `@id` with `atoi`.
   */
  solver_id: number | null;
  /**
   * Transmission loss per band in dB (`bfreq@affaiblissement`, tau = 10^(-R/10)). `None`
   * means no transmission in any band; a `None` band does not transmit. Either way the
   * attribute is left out of that band, which is how the solver knows
   * (`base_core_configuration.cpp:210-219`), as upstream's GUI leaves it out of a band whose
   * `transmission` switch is off (`e_data_row_materiau.h:98-106`): tutorial 3's
   * `Open_door` transmits from 250 Hz to 4 kHz but not at 125 Hz.
   */
  transmission_loss_db: ((number | string) | null)[] | null;
}
/**
 * A point receiver: `recepteursp/recepteur_ponctuel`.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "PointReceiver".
 */
export interface PointReceiver {
  /**
   * Background noise, `bfreq@db` per band. `None` writes none.
   */
  background_noise: Spectrum | null;
  id: string;
  /**
   * `@lbl` and `@name`. SPPS makes it a folder name and TCR a file name.
   */
  name: string;
  /**
   * `@u`, `@v`, `@w`, normalised by the solver; must not be zero.
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  orientation: [number | string, number | string, number | string];
  /**
   * `@x`, `@y`, `@z`; must lie inside the meshed volume.
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  position: [number | string, number | string, number | string];
  /**
   * A pinned solver id (`recepteur_ponctuel@id`). `None` lets export assign one
   * (`config_xml`, "Solver ids"). A `.proj` import pins upstream's element id (its `wxid`,
   * `docs/m5-m6-design.md`, decision 13), so an imported project writes upstream's ids. At
   * most [`SOLVER_INT_MAX`], and unique among point receivers.
   */
  solver_id: number | null;
}
/**
 * A level spectrum: a global level spread over the project's bands by a shape.
 *
 * Used for source sound power (dB re 1 pW) and receiver background noise.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Spectrum".
 */
export interface Spectrum {
  /**
   * The energetic sum over the project's bands, in dB.
   */
  global_db: number | string;
  shape: SpectrumShape;
}
/**
 * A point sound source: `sources/source`.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  /**
   * `@delay`, seconds.
   */
  delay_s: number | string;
  directivity: Directivity;
  /**
   * A disabled source is left out of config.xml.
   */
  enabled: boolean;
  /**
   * The source group it sits in, as upstream's GUI groups sources (a source list's element of
   * type 15, `e_scene_sources.h:73-87`): the groups' names from the outermost, joined by
   * ` / `. `None` at the top level, as for every source made here. It reaches no solver:
   * upstream writes a group's sources in its place. Source names need be unique only within
   * one group (`name_duplicate`), unless per-source output makes them folder names.
   */
  group: string | null;
  id: string;
  /**
   * `@name`.
   */
  name: string;
  /**
   * `@x`, `@y`, `@z`. Must lie strictly inside the meshed volume: SPPS crashes on a source
   * outside it (contract survey, `run_srcout`).
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  position: [number | string, number | string, number | string];
  power: Spectrum1;
  /**
   * A pinned element id: upstream's `source@id` for a source imported from a `.proj` (its
   * `wxid`, `docs/m5-m6-design.md`, decision 13). `None` for a source made here. The solvers
   * number sources by position and never read `source@id`
   * (`base_core_configuration.cpp:153`); `config.xml` carries it when pinned, as upstream's
   * GUI writes it, so that an imported project keeps upstream's ids. At most
   * [`SOLVER_INT_MAX`], and unique among sources.
   */
  solver_id: number | null;
}
/**
 * A level spectrum: a global level spread over the project's bands by a shape.
 *
 * Used for source sound power (dB re 1 pW) and receiver background noise.
 */
export interface Spectrum1 {
  /**
   * The energetic sum over the project's bands, in dB.
   */
  global_db: number | string;
  shape: SpectrumShape;
}
/**
 * A named set of faces sharing one material: the unit materials are assigned to.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "SurfaceGroup".
 */
export interface SurfaceGroup {
  id: string;
  /**
   * The base project's material; a [`Variant`] may override it.
   */
  material: string;
  name: string;
}
/**
 * A surface receiver (sound map): `recepteurss/recepteur_surfacique` or
 * `recepteur_surfacique_coupe`.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "SurfaceReceiver".
 */
export interface SurfaceReceiver {
  enabled: boolean;
  id: string;
  /**
   * `@name`.
   */
  name: string;
  shape: SurfaceReceiverShape;
  /**
   * A pinned solver id (`recepteur_surfacique@id` or `recepteur_surfacique_coupe@id`, and a
   * scene receiver's `.cbin` `idRs`). `None` lets export assign one (`config_xml`, "Solver
   * ids"). A `.proj` import pins upstream's element id (decision 13). At most
   * [`SOLVER_INT_MAX`], and unique among surface receivers and cutting planes.
   */
  solver_id: number | null;
}
/**
 * A named set of material overrides on top of the base project.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Variant".
 */
export interface Variant {
  id: string;
  name: string;
  /**
   * At most one per group, strictly ascending by group id (so each variant has one spelling).
   */
  overrides: MaterialOverride[];
}
/**
 * One material override in a [`Variant`].
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "MaterialOverride".
 */
export interface MaterialOverride {
  group: string;
  material: string;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "EventsProbeReport".
 */
export interface EventsProbeReport {
  batch_period_ms: number;
  elapsed_ms: number;
  lines: number;
  stats: BatchStats;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "BatchStats".
 */
export interface BatchStats {
  batches: number;
  events: number;
  /**
   * Batches the sink refused (the webview went away, for example).
   */
  send_failures: number;
}
/**
 * What each reader made of a JSON array of numbers: the bits as `0x` + 16 hex digits.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "FloatProbe".
 */
export interface FloatProbe {
  /**
   * How many values the two readers disagree on.
   */
  disagreements: number;
  /**
   * Read with the core's exact reader, as every schema value from the UI is.
   */
  exact_bits: string[];
  /**
   * Read with `serde_json::from_str`, as a command argument typed `f64` would be.
   */
  serde_json_bits: string[];
}
/**
 * A prepared buffer: take it with `token`; `checksum` is [`checksum`] of its bytes.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "Prepared".
 */
export interface Prepared {
  bytes: number;
  checksum: number;
  prepare_ms: number;
  token: number;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "RunEventBatch".
 */
export interface RunEventBatch {
  /**
   * 0, 1, 2, ... per run.
   */
  batch: number;
  events: RunEvent[];
  /**
   * The producer has finished; no batch follows.
   */
  last: boolean;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "RunEvent".
 */
export interface RunEvent {
  class: LineClass;
  /**
   * 0, 1, 2, ... per run, so the UI can prove it lost nothing and kept the order.
   */
  seq: number;
  stream: Stream;
  /**
   * Milliseconds since the run started.
   */
  t_ms: number;
  text: string;
}
/**
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "StartupInfo".
 */
export interface StartupInfo {
  app_version: string;
  /**
   * Started with `--e2e`: the UI installs its test hooks.
   */
  e2e: boolean;
  project?: ProjectInfo | null;
  project_error?: CmdError | null;
  selftest: boolean;
  tauri_version: string;
  webview: WebviewInfo;
}
/**
 * The webview engine and its runtime version, for the self-test and the Console.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "WebviewInfo".
 */
export interface WebviewInfo {
  engine: string;
  /**
   * `None` when the runtime cannot be queried (it is then missing or broken).
   */
  version?: string | null;
}
/**
 * The project without its geometry.
 *
 * This interface was referenced by `IpcBindings`'s JSON-Schema
 * via the `definition` "ProjectView".
 */
export interface ProjectView1 {
  active_variant?: string | null;
  bands: BandSet;
  description: string;
  materials: Material[];
  name: string;
  point_receivers: PointReceiver[];
  sources: Source[];
  surface_groups: SurfaceGroup[];
  surface_receivers: SurfaceReceiver[];
  variants: Variant[];
}
