/* Generated by ui/scripts/gen-bindings.mjs from schema.json (app.exe --dump-schema). Do not edit. */

/**
 * One edit. [`Op::apply`] returns its exact inverse.
 *
 * `Add*` ops insert at `index` (at most the list length); their inverse is `Remove*` by id,
 * whose inverse re-inserts at the same index. `Replace*` ops swap a whole entity, found by its
 * id. A removal is refused while anything refers to the entity.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Op".
 */
export type Op =
  | {
      name: string;
      op: 'set_project_name';
    }
  | {
      description: string;
      op: 'set_description';
    }
  | {
      name: string;
      op: 'rename';
      target: EntityRef;
    }
  | {
      bands: BandSet;
      data: BandData;
      op: 'set_bands';
    }
  | {
      geometry: Geometry;
      op: 'set_geometry';
    }
  | {
      group: SurfaceGroup;
      index: number;
      op: 'add_surface_group';
    }
  | {
      id: string;
      op: 'remove_surface_group';
    }
  | {
      group: string;
      material: string;
      op: 'set_group_material';
    }
  | {
      index: number;
      material: Material;
      op: 'add_material';
    }
  | {
      id: string;
      op: 'remove_material';
    }
  | {
      material: Material;
      op: 'replace_material';
    }
  | {
      band: number;
      material: string;
      op: 'set_material_band';
      quantity: MaterialQuantity;
      /**
       * A float. Finite values are numbers; non-finite values are strings.
       */
      value: number | string;
    }
  | {
      index: number;
      op: 'add_source';
      source: Source;
    }
  | {
      id: string;
      op: 'remove_source';
    }
  | {
      op: 'replace_source';
      source: Source;
    }
  | {
      id: string;
      op: 'move_source';
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      position: [number | string, number | string, number | string];
    }
  | {
      enabled: boolean;
      id: string;
      op: 'set_source_enabled';
    }
  | {
      index: number;
      op: 'add_point_receiver';
      receiver: PointReceiver;
    }
  | {
      id: string;
      op: 'remove_point_receiver';
    }
  | {
      op: 'replace_point_receiver';
      receiver: PointReceiver;
    }
  | {
      id: string;
      op: 'move_point_receiver';
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      position: [number | string, number | string, number | string];
    }
  | {
      index: number;
      op: 'add_surface_receiver';
      receiver: SurfaceReceiver;
    }
  | {
      id: string;
      op: 'remove_surface_receiver';
    }
  | {
      op: 'replace_surface_receiver';
      receiver: SurfaceReceiver;
    }
  | {
      index: number;
      op: 'add_fitting_zone';
      zone: FittingZone;
    }
  | {
      id: string;
      op: 'remove_fitting_zone';
    }
  | {
      op: 'replace_fitting_zone';
      zone: FittingZone;
    }
  | {
      band: number;
      op: 'set_fitting_band';
      quantity: FittingQuantity;
      /**
       * A float. Finite values are numbers; non-finite values are strings.
       */
      value: number | string;
      zone: string;
    }
  | {
      environment: Environment;
      op: 'set_environment';
    }
  | {
      op: 'set_solver_settings';
      settings: SolverSettings;
    }
  | {
      band: number;
      computed: boolean;
      op: 'set_band_computed';
      solver: SolverKind;
    }
  | {
      index: number;
      op: 'add_variant';
      variant: Variant;
    }
  | {
      id: string;
      op: 'remove_variant';
    }
  | {
      group: string;
      material: string | null;
      op: 'set_variant_override';
      variant: string;
    }
  | {
      op: 'set_active_variant';
      variant: string | null;
    }
  | {
      camera: Camera | null;
      op: 'set_camera';
    }
  | {
      op: 'batch';
      ops: Op[];
    };
/**
 * A named entity of the project. In JSON: `{"kind": "material", "id": "<uuid>"}`; any other
 * key is refused.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "EntityRef".
 */
export type EntityRef =
  | {
      id: string;
      kind: 'surface_group';
    }
  | {
      id: string;
      kind: 'material';
    }
  | {
      id: string;
      kind: 'source';
    }
  | {
      id: string;
      kind: 'point_receiver';
    }
  | {
      id: string;
      kind: 'surface_receiver';
    }
  | {
      id: string;
      kind: 'fitting_zone';
    }
  | {
      id: string;
      kind: 'variant';
    };
/**
 * Octave or third-octave bands.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "BandKind".
 */
export type BandKind = 'octave' | 'third_octave';
/**
 * Diffusion law inside a fitting zone: `encombrement/bfreq@loi_diff`, the solver's
 * `DIFFUSION_LAW` (`lib_interface/coreTypes.h:108-113`). The discriminant is the solver code.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "DiffusionLaw".
 */
export type DiffusionLaw = 'uniform' | 'uniform_reflection' | 'lambert_reflection';
/**
 * One law, which fits any band set, or one per band.
 */
export type ReflectionLaws = ReflectionLaw | ReflectionLaw1[];
/**
 * The same law in every band.
 */
export type ReflectionLaw =
  ('specular' | 'lambert' | 'w2' | 'w3' | 'w4' | 'semi_diffuse') | 'uniform';
/**
 * How a surface reflects the diffuse part of the energy: `type_surface/bfreq@loi`, the solver's
 * `REFLECTION_LAW` (`lib_interface/coreTypes.h:83-92`). The discriminant is the solver code.
 *
 * SPPS draws a diffuse reflection with probability equal to the scattering coefficient
 * (`spps/CalculationCore.cpp:318`), so the law has no effect at scattering 0.
 * [`ReflectionLaw::SemiDiffuse`] has no case in SPPS's `ReflectionLaws::SolveReflection`
 * (`spps/tools/dotreflection.h:23-45`) and falls to its default, a specular reflection.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "ReflectionLaw".
 */
export type ReflectionLaw1 =
  ('specular' | 'lambert' | 'w2' | 'w3' | 'w4' | 'semi_diffuse') | 'uniform';
/**
 * `bfreq@loi`, one law for every band or one per band.
 */
export type ReflectionLaws1 = ReflectionLaw | ReflectionLaw1[];
/**
 * A per-band quantity of a material.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "MaterialQuantity".
 */
export type MaterialQuantity = ('absorption' | 'scattering') | 'transmission_loss';
/**
 * Source directivity: `source@directivite`, the solver's `SOURCE_TYPE`
 * (`lib_interface/coreTypes.h:96-104`). See [`Directivity::solver_code`].
 *
 * In JSON: `{"kind": "omni"}`, `{"kind": "unidirectional", "direction": [x, y, z]}`, ...
 * Extra keys are refused for every kind. (serde's derive alone would read
 * `{"kind": "omni", "file": "balloon.txt"}` as omni and drop the file, so the reader is written
 * by hand.)
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Directivity".
 */
export type Directivity =
  | {
      kind: 'omni';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      direction: [number | string, number | string, number | string];
      kind: 'unidirectional';
    }
  | {
      kind: 'plane_xy';
    }
  | {
      kind: 'plane_yz';
    }
  | {
      kind: 'plane_xz';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      direction: [number | string, number | string, number | string];
      file: string;
      kind: 'balloon';
    };
/**
 * The shape of a level spectrum across the project's bands.
 *
 * In JSON: `{"kind": "pink"}`, `{"kind": "white"}` or `{"kind": "custom", "relative_db": [...]}`.
 * Extra keys are refused for every kind: serde's derive alone would read
 * `{"kind": "pink", "relative_db": [...]}` as pink and drop the levels, so the reader is written
 * by hand.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SpectrumShape".
 */
export type SpectrumShape =
  | {
      kind: 'pink';
    }
  | {
      kind: 'white';
    }
  | {
      kind: 'custom';
      /**
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      relative_db: (number | string)[];
    };
/**
 * Where a surface receiver lies.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SurfaceReceiverShape".
 */
export type SurfaceReceiverShape =
  | {
      groups: string[];
      kind: 'scene';
    }
  | {
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      a: [number | string, number | string, number | string];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      b: [number | string, number | string, number | string];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      c: [number | string, number | string, number | string];
      kind: 'cutting_plane';
      /**
       * A float. Finite values are numbers; non-finite values are strings.
       */
      resolution_m: number | string;
    };
/**
 * The volume of a fitting zone. Export marks it as a TetGen region whose attribute is the zone's
 * solver id (`mbin idVolume`, `.cbin idEn`).
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "FittingShape".
 */
export type FittingShape =
  | {
      /**
       * Which bound upstream's destination corner `hc` ("Destination volume") takes on each
       * axis; its origin corner `ba` takes the other. Upstream stores the two corners as the
       * user typed them, not ordered (tutorial 3's box: `ba` (13, 4, 0), `hc` (18, 1, 1.2)),
       * and seeds the box's TetGen region at `hc - (hc - ba) * 1e-4`
       * (`e_scene_encombrements_encombrement_cuboide.h:333-336`), so this is what reproduces
       * that seed ([`FittingShape::box_corners`]). `None`: `ba` is `min` and `hc` is `max`,
       * as for a box drawn here.
       *
       * @minItems 3
       * @maxItems 3
       */
      destination: [BoxBound, BoxBound, BoxBound] | null;
      kind: 'box';
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      max: [number | string, number | string, number | string];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      min: [number | string, number | string, number | string];
    }
  | {
      groups: string[];
      /**
       * [x, y, z] in metres, Z up
       *
       * @minItems 3
       * @maxItems 3
       *
       * Items: A float. Finite values are numbers; non-finite values are strings.
       */
      inside_point: [number | string, number | string, number | string];
      kind: 'surfaces';
    };
/**
 * One bound of a box on one axis: see `FittingShape::Box::destination`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "BoxBound".
 */
export type BoxBound = 'min' | 'max';
/**
 * A per-band quantity of a fitting zone.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "FittingQuantity".
 */
export type FittingQuantity = 'absorption' | 'mean_free_path';
/**
 * Air absorption: `condition_atmospherique@disable_absatmo_computation` and `@absatmo`.
 *
 * In JSON: `{"kind": "iso9613"}` or `{"kind": "user_defined", "value": v, "unit": u}`. Extra
 * keys are refused for both kinds, so a hand-edited `{"kind": "iso9613", "value": 0.5}` is an
 * error, not a silent switch to the computed value.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "AirAbsorption".
 */
export type AirAbsorption =
  | {
      kind: 'iso9613';
    }
  | {
      kind: 'user_defined';
      unit: AttenuationUnit;
      /**
       * A float. Finite values are numbers; non-finite values are strings.
       */
      value: number | string;
    };
/**
 * Unit of a user-defined air absorption.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "AttenuationUnit".
 */
export type AttenuationUnit = 'per_metre' | 'decibel_per_metre';
/**
 * SPPS's absorption method: `simulation@computation_method`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "ComputationMethod".
 */
export type ComputationMethod = 'random' | 'energetic';
/**
 * `@surf_receiv_method`.
 */
export type SoundMapQuantity = 'intensity' | 'spl';
/**
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SolverKind".
 */
export type SolverKind = 'spps' | 'tcr';
/**
 * Length unit of every coordinate in the project. Only metres: the file states it so that a
 * file in any other unit is refused rather than misread.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "LengthUnit".
 */
export type LengthUnit = 'metre';
/**
 * The vertical axis. Only +Z, as the solvers use it (`@alog`/`@blin` gradients act along z).
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "UpAxis".
 */
export type UpAxis = 'z';
/**
 * A material's reflection law: one law for every band, or one per band. The solvers read it per
 * band (`type_surface/bfreq@loi`, `base_core_configuration.cpp:210-219`), and upstream's GUI
 * keeps one per band (the `loi` list of each row, `e_data_row_materiau.h:218`): tutorial 3's
 * material 100 is Lambert in the six octave bands and specular in the others.
 *
 * In JSON: one law, `"lambert"`, or one per band in the band set's order,
 * `["specular", "lambert", ...]`. [`ReflectionLaws::from_bands`] gives the single spelling
 * whenever every band has the same law.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "ReflectionLaws".
 */
export type ReflectionLaws2 = ReflectionLaw | ReflectionLaw1[];
/**
 * What SPPS writes on surface receivers: `simulation@surf_receiv_method`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SoundMapQuantity".
 */
export type SoundMapQuantity1 = 'intensity' | 'spl';

/**
 * simpa_core::schema, dumped by app.exe --dump-schema. Do not edit.
 */
export interface SchemaBindings {
  op: Op;
  project: Project;
}
/**
 * The frequency bands every per-band value in the project is given on.
 *
 * `frequencies_hz` holds nominal centre frequencies of `kind`, strictly ascending. The solvers
 * sort `freq_enum` and map every per-band array by sorted position, so ascending order here is
 * the order of every per-band array in the project.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "BandSet".
 */
export interface BandSet {
  frequencies_hz: number[];
  kind: BandKind;
}
/**
 * Every per-band array of a project, keyed by entity in project order: what changes with the
 * band set. Custom spectrum shapes are `Some`, other shapes `None`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "BandData".
 */
export interface BandData {
  background_noise_shapes: [string, (number | string)[] | null][];
  fitting_zones: [string, FittingBands][];
  materials: [string, MaterialBands][];
  source_shapes: [string, (number | string)[] | null][];
  spps_bands_computed: boolean[];
  tcr_bands_computed: boolean[];
}
/**
 * A fitting zone's per-band arrays.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "FittingBands".
 */
export interface FittingBands {
  /**
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  absorption: (number | string)[];
  diffusion_law: DiffusionLaw[];
  /**
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  mean_free_path_m: (number | string)[];
}
/**
 * A material's per-band values.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "MaterialBands".
 */
export interface MaterialBands {
  /**
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  absorption: (number | string)[];
  reflection_law: ReflectionLaws;
  /**
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  scattering: (number | string)[];
  transmission_loss_db: ((number | string) | null)[] | null;
}
/**
 * The room's surface mesh, in world metres. Each face belongs to one surface group.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Geometry".
 */
export interface Geometry {
  faces: [number, number, number, string][];
  vertices: [number | string, number | string, number | string][];
}
/**
 * A named set of faces sharing one material: the unit materials are assigned to.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SurfaceGroup".
 */
export interface SurfaceGroup {
  id: string;
  /**
   * The base project's material; a [`Variant`] may override it.
   */
  material: string;
  name: string;
}
/**
 * A surface material: `surface_absorption_enum/type_surface`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Material".
 */
export interface Material {
  /**
   * Absorption coefficient per band, 0 to 1 (`bfreq@absorb`).
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  absorption: (number | string)[];
  /**
   * Display colour.
   */
  color: string;
  /**
   * `@side_material`: the material acts on both sides of a face.
   */
  double_sided: boolean;
  id: string;
  name: string;
  reflection_law: ReflectionLaws1;
  /**
   * Scattering coefficient per band, 0 to 1: the share of reflections that are diffuse
   * (`bfreq@diffusion`).
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  scattering: (number | string)[];
  /**
   * A pinned solver id (`type_surface@id`, the `.cbin` face `idMat`). `None` lets export
   * assign one. Importers set it so that a project imported from a solver mesh exports the
   * same ids and still matches that mesh. At most [`SOLVER_INT_MAX`]: the solver reads
   * `@id` with `atoi`.
   */
  solver_id: number | null;
  /**
   * Transmission loss per band in dB (`bfreq@affaiblissement`, tau = 10^(-R/10)). `None`
   * means no transmission in any band; a `None` band does not transmit. Either way the
   * attribute is left out of that band, which is how the solver knows
   * (`base_core_configuration.cpp:210-219`), as upstream's GUI leaves it out of a band whose
   * `transmission` switch is off (`e_data_row_materiau.h:98-106`): tutorial 3's
   * `Open_door` transmits from 250 Hz to 4 kHz but not at 125 Hz.
   */
  transmission_loss_db: ((number | string) | null)[] | null;
}
/**
 * A point sound source: `sources/source`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  /**
   * `@delay`, seconds.
   */
  delay_s: number | string;
  directivity: Directivity;
  /**
   * A disabled source is left out of config.xml.
   */
  enabled: boolean;
  /**
   * The source group it sits in, as upstream's GUI groups sources (a source list's element of
   * type 15, `e_scene_sources.h:73-87`): the groups' names from the outermost, joined by
   * ` / `. `None` at the top level, as for every source made here. It reaches no solver:
   * upstream writes a group's sources in its place. Source names need be unique only within
   * one group (`name_duplicate`), unless per-source output makes them folder names.
   */
  group: string | null;
  id: string;
  /**
   * `@name`.
   */
  name: string;
  /**
   * `@x`, `@y`, `@z`. Must lie strictly inside the meshed volume: SPPS crashes on a source
   * outside it (contract survey, `run_srcout`).
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  position: [number | string, number | string, number | string];
  power: Spectrum;
  /**
   * A pinned element id: upstream's `source@id` for a source imported from a `.proj` (its
   * `wxid`, `docs/m5-m6-design.md`, decision 13). `None` for a source made here. The solvers
   * number sources by position and never read `source@id`
   * (`base_core_configuration.cpp:153`), so `config.xml` does not carry it; the project keeps
   * it so that an imported project keeps upstream's ids. At most [`SOLVER_INT_MAX`].
   */
  solver_id: number | null;
}
/**
 * Sound power, dB re 1 pW (`bfreq@db` per band, from [`Spectrum::band_levels_db`]).
 */
export interface Spectrum {
  /**
   * The energetic sum over the project's bands, in dB.
   */
  global_db: number | string;
  shape: SpectrumShape;
}
/**
 * A point receiver: `recepteursp/recepteur_ponctuel`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "PointReceiver".
 */
export interface PointReceiver {
  /**
   * Background noise, `bfreq@db` per band. `None` writes none.
   */
  background_noise: Spectrum1 | null;
  id: string;
  /**
   * `@lbl` and `@name`. SPPS makes it a folder name and TCR a file name.
   */
  name: string;
  /**
   * `@u`, `@v`, `@w`, normalised by the solver; must not be zero.
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  orientation: [number | string, number | string, number | string];
  /**
   * `@x`, `@y`, `@z`; must lie inside the meshed volume.
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  position: [number | string, number | string, number | string];
  /**
   * A pinned solver id (`recepteur_ponctuel@id`). `None` lets export assign one
   * (`config_xml`, "Solver ids"). A `.proj` import pins upstream's element id (its `wxid`,
   * `docs/m5-m6-design.md`, decision 13), so an imported project writes upstream's ids. At
   * most [`SOLVER_INT_MAX`], and unique among point receivers.
   */
  solver_id: number | null;
}
/**
 * A level spectrum: a global level spread over the project's bands by a shape.
 *
 * Used for source sound power (dB re 1 pW) and receiver background noise.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Spectrum".
 */
export interface Spectrum1 {
  /**
   * The energetic sum over the project's bands, in dB.
   */
  global_db: number | string;
  shape: SpectrumShape;
}
/**
 * A surface receiver (sound map): `recepteurss/recepteur_surfacique` or
 * `recepteur_surfacique_coupe`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SurfaceReceiver".
 */
export interface SurfaceReceiver {
  enabled: boolean;
  id: string;
  /**
   * `@name`.
   */
  name: string;
  shape: SurfaceReceiverShape;
  /**
   * A pinned solver id (`recepteur_surfacique@id` or `recepteur_surfacique_coupe@id`, and a
   * scene receiver's `.cbin` `idRs`). `None` lets export assign one (`config_xml`, "Solver
   * ids"). A `.proj` import pins upstream's element id (decision 13). At most
   * [`SOLVER_INT_MAX`], and unique among surface receivers and cutting planes.
   */
  solver_id: number | null;
}
/**
 * A fitting zone (encombrement): a volume filled with scattering objects, `encombrement_enum`.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "FittingZone".
 */
export interface FittingZone {
  /**
   * `bfreq@alpha` per band: absorption of the fittings, 0 to 1.
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  absorption: (number | string)[];
  /**
   * `bfreq@loi_diff` per band.
   */
  diffusion_law: DiffusionLaw[];
  enabled: boolean;
  id: string;
  /**
   * `bfreq@lambda` per band: mean free path between fittings, metres.
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  mean_free_path_m: (number | string)[];
  name: string;
  shape: FittingShape;
  /**
   * A pinned solver id (`encombrement@id`, the `.cbin` `idEn`, and the TetGen region
   * attribute its tetrahedra carry as `idVolume`; the room's parts are numbered by TetGen
   * above the largest). `None` lets export assign one (`config_xml`, "Solver ids"). A `.proj`
   * import pins upstream's element id (tutorial 3: 1930 and 2083, its room then 2084 to 2086;
   * decision 13). At least 1 (the solvers read `idVolume` 0 as no fitting), at most
   * [`SOLVER_INT_MAX`], and unique among fitting zones.
   */
  solver_id: number | null;
}
/**
 * The medium: `condition_atmospherique`. A missing element would leave the sound speed and
 * density at 0, so config.xml always writes every attribute.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Environment".
 */
export interface Environment {
  air_absorption: AirAbsorption;
  /**
   * `@blin`: linear celerity-gradient coefficient (0 = homogeneous).
   */
  celerity_gradient_lin: number | string;
  /**
   * `@alog`: logarithmic celerity-gradient coefficient (0 = homogeneous).
   */
  celerity_gradient_log: number | string;
  /**
   * `@z0`, metres: ground roughness for the celerity profile.
   */
  ground_roughness_m: number | string;
  /**
   * `@pression`, pascals.
   */
  pressure_pa: number | string;
  /**
   * `@humidite`, percent relative humidity.
   */
  relative_humidity_percent: number | string;
  /**
   * `@temperature`, degrees Celsius.
   */
  temperature_c: number | string;
}
/**
 * Settings of every solver the project can run.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SolverSettings".
 */
export interface SolverSettings {
  meshing: MeshSettings;
  spps: SppsSettings;
  tcr: TcrSettings;
}
/**
 * TetGen settings (`e_core_core_tetconf.h`).
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "MeshSettings".
 */
export interface MeshSettings {
  /**
   * `-a`: maximum tetrahedron volume, cubic metres; `None` for no bound.
   */
  max_volume_m3: (number | string) | null;
  /**
   * `-q`: radius-to-edge quality bound.
   */
  min_radius_edge_ratio: number | string;
  /**
   * Upstream's "Scene correction before meshing" (`mesh_conf@preprocess`,
   * `e_core_core_tetconf.h:108`): the `.poly` goes through upstream's `preprocess.exe` before
   * TetGen, with box fitting zones in its user facet list, as upstream's GUI does it
   * (`projet_maillage.cpp:206-213`). The geometry check then runs on what `preprocess.exe`
   * wrote. Upstream's GUI default is on; this crate's default is off
   * (`docs/m5-m6-design.md`, decision 12).
   */
  preprocess: boolean;
  /**
   * `-Y`: add no Steiner points on the boundary.
   */
  preserve_boundary: boolean;
  /**
   * Facet-area constraint on surface-receiver faces, square metres (the `.var` file); `None`
   * for no refinement.
   */
  surface_receiver_max_area_m2: (number | string) | null;
}
/**
 * SPPS, the particle solver: the `simulation` element's SPPS attributes.
 *
 * The three integers are C `int`s in the solver: each is at most [`SOLVER_INT_MAX`], which
 * [`Project::check_integrity`] enforces.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "SppsSettings".
 */
export interface SppsSettings {
  /**
   * `@abs_atmo_calc`.
   */
  air_absorption: boolean;
  /**
   * `freq_enum/bfreq@docalc` per band: which bands SPPS computes.
   */
  bands_computed: boolean[];
  /**
   * `@direct_calc`: direct field only (every surface fully absorbing).
   */
  direct_field_only: boolean;
  /**
   * `@duree_simulation`, seconds.
   */
  duration_s: number | string;
  /**
   * `@output_recp_bysource`: an echogram per source as well as the total.
   */
  echogram_per_source: boolean;
  /**
   * `@trans_epsilon`: a particle dies below `E0 * 10^-n`. A missing value (0) kills every
   * particle at the first step in energetic mode (contract survey, `run_noeps`).
   */
  extinction_exponent: number | string;
  /**
   * `@enc_calc`: fitting zones on. Off, the solver ignores them silently.
   */
  fittings: boolean;
  method: ComputationMethod;
  /**
   * `@nbparticules`: particles per source per band. The solver raises values below 1 to 1.
   */
  particles_per_source: number;
  /**
   * `@nbparticules_rendu`: particles per source saved for display; 0 saves none.
   */
  particles_saved: number;
  /**
   * `@random_seed`: 0 leaves the generator unseeded and runs one thread per band; any other
   * value seeds it and forces a single thread. The solver reads it as a C `int`.
   */
  random_seed: number;
  /**
   * `@rayon_recepteurp`: point-receiver sphere radius, metres. Must be above 0.
   */
  receiver_radius_m: number | string;
  /**
   * `@save_receivers_intersection`: per-band receiver collision CSVs.
   */
  save_receiver_intersections: boolean;
  /**
   * `@save_surface_intersection`: per-band surface collision CSVs.
   */
  save_surface_intersections: boolean;
  sound_map: SoundMapQuantity;
  /**
   * `@output_recs_byfreq`: surface-receiver files for every band, not only the global one.
   */
  sound_maps_per_band: boolean;
  /**
   * `@pasdetemps`, seconds. `duration / time step` must stay below 65,536 steps.
   */
  time_step_s: number | string;
  /**
   * `@trans_calc`: transmission through materials that have a transmission loss.
   */
  transmission: boolean;
}
/**
 * TCR, the classical theory of reverberation. TCR always writes surface receivers per band
 * (it tests the attribute's presence, not its value), so that switch is not a setting.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "TcrSettings".
 */
export interface TcrSettings {
  /**
   * `@abs_atmo_calc`.
   */
  air_absorption: boolean;
  /**
   * `freq_enum/bfreq@docalc` per band.
   */
  bands_computed: boolean[];
}
/**
 * A named set of material overrides on top of the base project.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Variant".
 */
export interface Variant {
  id: string;
  name: string;
  /**
   * At most one per group, strictly ascending by group id (so each variant has one spelling).
   */
  overrides: MaterialOverride[];
}
/**
 * One material override in a [`Variant`].
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "MaterialOverride".
 */
export interface MaterialOverride {
  group: string;
  material: string;
}
/**
 * A perspective camera looking from `eye` at `target`, Z up.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Camera".
 */
export interface Camera {
  /**
   * [x, y, z] in metres, Z up
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  eye: [number | string, number | string, number | string];
  /**
   * [x, y, z] in metres, Z up
   *
   * @minItems 3
   * @maxItems 3
   *
   * Items: A float. Finite values are numbers; non-finite values are strings.
   */
  target: [number | string, number | string, number | string];
  /**
   * A float. Finite values are numbers; non-finite values are strings.
   */
  vertical_fov_deg: number | string;
}
/**
 * A room-acoustics project: the model, its materials, sources and receivers, the solver settings
 * and the GUI state.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Project".
 */
export interface Project {
  /**
   * The variant the GUI shows and a run uses; `None` is the base project.
   */
  active_variant: string | null;
  bands: BandSet1;
  description: string;
  environment: Environment;
  fitting_zones: FittingZone[];
  /**
   * Always [`FORMAT_VERSION`]; checked first on load.
   */
  format_version: number;
  frame: Frame;
  geometry: Geometry;
  id: string;
  /**
   * The project's material library. Entries need not be in use.
   */
  materials: Material[];
  name: string;
  point_receivers: PointReceiver[];
  solvers: SolverSettings;
  sources: Source[];
  surface_groups: SurfaceGroup[];
  surface_receivers: SurfaceReceiver[];
  variants: Variant[];
  view: ViewState;
}
/**
 * The frequency bands every per-band value in the project is given on.
 *
 * `frequencies_hz` holds nominal centre frequencies of `kind`, strictly ascending. The solvers
 * sort `freq_enum` and map every per-band array by sorted position, so ascending order here is
 * the order of every per-band array in the project.
 */
export interface BandSet1 {
  frequencies_hz: number[];
  kind: BandKind;
}
/**
 * The world frame.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "Frame".
 */
export interface Frame {
  length_unit: LengthUnit;
  up_axis: UpAxis;
}
/**
 * GUI state that belongs to the project.
 *
 * This interface was referenced by `SchemaBindings`'s JSON-Schema
 * via the `definition` "ViewState".
 */
export interface ViewState {
  /**
   * The saved 3D view; `None` lets the GUI frame the model.
   */
  camera: Camera | null;
}
