# Builds the oracle: upstream's lib_interface format readers (unchanged, from the M1 source
# archive) behind a CLI that prints canonical dumps. Test-only; never shipped.
#   powershell -File oracle/build.ps1               # every oracle/dump_*.cpp -> target/oracle/all/oracle.exe
#   powershell -File oracle/build.ps1 -Only cbin    # one format -> target/oracle/cbin/oracle.exe
#   ... -UpstreamSrc <tree>\src                    # upstream's src/ from another tree at that commit
# A dump_<fmt>.cpp may pull in more upstream sources or defines with header lines such as
#   // oracle-extra-source: tetgen/tetgen.cxx      (path relative to the upstream src/ directory)
#   // oracle-define: TETLIBRARY
param([string]$Only = '', [string]$Commit = '929a5c8', [string]$UpstreamSrc = '')
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$oracle = Join-Path $repo 'oracle'
$src = if ($UpstreamSrc) { $UpstreamSrc } else { Join-Path $repo "target\solvers\src-$Commit\src" }
$li = Join-Path $src 'lib_interface'
if (-not (Test-Path $li)) { throw "upstream source archive missing at ${src}; run solvers/build.ps1 first" }
$name = if ($Only) { $Only } else { 'all' }
$out = Join-Path $repo "target\oracle\$name"
New-Item -ItemType Directory -Force $out, (Join-Path $out 'obj') | Out-Null

$dumps = Get-ChildItem $oracle -Filter 'dump_*.cpp' | Where-Object { -not $Only -or $_.BaseName -eq "dump_$Only" }
if (-not $dumps) { throw "no oracle/dump_$(if ($Only) { $Only } else { '*' }).cpp to build" }
$formats = $dumps | ForEach-Object { $_.BaseName.Substring(5) }

$reg = @('// Generated by oracle/build.ps1. Do not edit.')
$reg += $formats | ForEach-Object { "int dump_$_(const char* path);" }
$reg += 'struct OracleEntry { const char* name; int (*fn)(const char*); };'
$reg += 'static const OracleEntry ORACLE[] = {'
$reg += $formats | ForEach-Object { "    {`"$_`", dump_$_}," }
$reg += '};'
Set-Content (Join-Path $out 'registry.inc') $reg -Encoding ASCII

$upstream = @(
    'input_output\bin.cpp', 'input_output\importExportMaillage\mbin.cpp', 'input_output\poly\poly.cpp',
    'input_output\gabe\gabe.cpp', 'input_output\exportRecepteurSurf\rsbin.cpp',
    'input_output\particles\part_io.cpp', 'input_output\cxml.cpp', 'coreString.cpp',
    'input_output\pugixml\src\pugixml.cpp'
) | ForEach-Object { Join-Path $li $_ }
$extra = @(); $defines = @()
foreach ($d in $dumps) {
    foreach ($line in Get-Content $d.FullName) {
        if ($line -match '^//\s*oracle-extra-source:\s*(\S+)') { $extra += (Join-Path $src $Matches[1]) }
        if ($line -match '^//\s*oracle-define:\s*(\S+)') { $defines += $Matches[1] }
    }
}
$sources = @((Join-Path $oracle 'main.cpp'), (Join-Path $oracle 'std_tools_nob.cpp')) + ($dumps | ForEach-Object { $_.FullName }) + $upstream + ($extra | Select-Object -Unique)
$defs = ($defines | Select-Object -Unique | ForEach-Object { "/D$_" }) -join ' '
$quoted = ($sources | ForEach-Object { "`"$_`"" }) -join ' '
$vcvars = 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat'
$bat = Join-Path $out 'build.bat'
Set-Content $bat -Encoding ASCII -Value @(
    '@echo off',
    "call `"$vcvars`" >nul",
    "cl /nologo /EHsc /MD /O2 /std:c++17 /DWIN32 /D_WINDOWS /DNDEBUG /W1 $defs /I`"$li`" /I`"$oracle`" /I`"$out`" /Fo`"$out\obj\\`" /Fe:`"$out\oracle.exe`" $quoted"
)
$log = Join-Path $out 'build.log'
cmd /c "`"$bat`" > `"$log`" 2>&1"
if ($LASTEXITCODE -ne 0) { Get-Content $log -Tail 30; throw "oracle build failed (log: $log)" }
Write-Host "oracle built: $out\oracle.exe [$($formats -join ', ')]"
