// Oracle CLI: upstream's own lib_interface readers, printing the canonical dump of a file.
//   oracle list
//   oracle dump <format> <file>
// registry.inc is generated by oracle/build.ps1 from the dump_<format>.cpp files being built.
#include <cstdio>
#include <string>

#include "common.hpp"
#include "registry.inc"

int main(int argc, char** argv) {
    if (argc == 2 && std::string(argv[1]) == "list") {
        for (const auto& e : ORACLE) std::printf("%s\n", e.name);
        return 0;
    }
    if (argc != 4 || std::string(argv[1]) != "dump") {
        std::fprintf(stderr, "usage: oracle list | oracle dump <format> <file>\n");
        return 2;
    }
    for (const auto& e : ORACLE) {
        if (std::string(argv[2]) == e.name) return e.fn(argv[3]);
    }
    std::fprintf(stderr, "oracle: no dumper for format '%s'\n", argv[2]);
    return 2;
}
