# M1 gate: the solvers we build are upstream's unchanged solvers, and the mesher is TetGen 1.5.0.
# - spps, classicalTheory and preprocess come from the pinned commit 929a5c8 and must equal the
#   2026-09-08 reference build byte for byte outside the link timestamps (MSVC writes the link
#   time into the COFF header and the debug directory, and nowhere else in these builds), and
#   produce the reference's outputs from identical, seeded inputs.
# - tetgen.exe is WIAS TetGen 1.5.0 from third_party/tetgen-1.5.0, the TetGen upstream shipped in
#   1.3.3 and 1.3.4 (decision of 2026-09-23, target/investigate/DECISIONS.md). It is checked by
#   its source (the tarball's bytes, upstream 4db335c's blobs), by its build (upstream's tetgen
#   command lines, and a from-scratch rebuild in this gate run that must give bin\tetgen.exe
#   again), and by what it does: upstream's tutorial 1 input must mesh to the 2019 tutorial
#   files byte for byte, the '# Generated by' trailer line aside.
# Every check that can pass has a "says NO" partner: an input it must refuse. The TetGen checks
# refuse upstream's own 1.6.0 tetgen, built in the same run by solvers/build.ps1.
# Run from anywhere: powershell -File tools/gates/m1.ps1
$ErrorActionPreference = 'Stop'
$failures = @(); $script:checks = 0
# A check body returns exactly one bool. Anything else (no value, several values, a non-bool)
# is a FAIL: a stray value leaking into the pipeline must never turn into a PASS.
function Check($name, [scriptblock]$body) {
    $script:checks++
    try {
        $r = @(& $body)
        if ($r.Count -eq 1 -and $r[0] -is [bool] -and $r[0]) {
            Write-Host "PASS  $name"
        } elseif ($r.Count -eq 1 -and $r[0] -is [bool]) {
            Write-Host "FAIL  $name"; $script:failures += $name
        } else {
            Write-Host "FAIL  $name :: the check returned $($r.Count) values, not one bool"; $script:failures += $name
        }
    } catch {
        Write-Host "FAIL  $name :: $($_.Exception.Message)"; $script:failures += $name
    }
}

$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$up = 'B:\repos\I-Simpa-upstream'
$commit = '929a5c8e5f590b189f29155faeff8670f3699479'
$solvers = Join-Path $repo 'target\solvers'
$bin = Join-Path $solvers 'bin'
$fix = Join-Path $repo 'tests\fixtures\upstream\tutorial1'
$tgSrc = Join-Path $repo 'third_party\tetgen-1.5.0'
$manifest = Get-Content (Join-Path $repo 'solvers\manifest.json') -Raw | ConvertFrom-Json
$bld = Join-Path $solvers $manifest.build_dir
$tgBld = Join-Path $solvers $manifest.tetgen.build_dir
$usrc = Join-Path $solvers ('src-' + $commit.Substring(0, 7))
# upstream's own 1.6.0 tetgen target, built by solvers/build.ps1 beside ours and never shipped
$tg16 = Join-Path $bld 'src\tetgen\Release\tetgen.exe'
$ref = @{
    spps       = Join-Path $up 'build_solvers\src\spps\Release\spps.exe'
    tcr        = Join-Path $up 'build_solvers\src\ctr\Release\classicalTheory.exe'
    preprocess = Join-Path $up 'build_solvers\src\preprocess\Release\preprocess.exe'
    tetgen16   = Join-Path $up 'build_solvers\src\tetgen\Release\tetgen.exe'
}
$new = @{
    spps       = Join-Path $bin 'spps.exe'
    tcr        = Join-Path $bin 'classicalTheory.exe'
    preprocess = Join-Path $bin 'preprocess.exe'
    tetgen     = Join-Path $bin 'tetgen.exe'
}
# WIAS tetgen1.5.0.tar.gz, and the git blob ids of upstream's src/tetgen at 4db335c (2016-08-11,
# "Build tetgen from sources"; unchanged up to a0d4d43, the parent of the 1.6 update ef2f764).
$tarballSha = '4d114861d5ef2063afd06ef38885ec46822e90e7b4ea38c864f76493451f9cf3'
$blobCommit = '4db335c123eb54986015dbd8192aa8a7e0ec0969'
$blobs4db = [ordered]@{
    'tetgen.cxx'     = 'da4ef3d73513af1acad895153b65e5d80f66842b'
    'tetgen.h'       = '3196e031f5318369c6842296cf58fa45a2af611b'
    'predicates.cxx' = '33817d7999cf04ee831bcae75e053a39d9b783cb'
    'LICENSE'        = 'e253c3d965ddda3797c1ce80fedde3c84c54ecd4'
    'README'         = 'bc5cfa04c0e901cb5c5890b9783a781fa31eda1a'
}
. (Join-Path $repo 'solvers\tetgen\build-commands.ps1')

# Fresh folder per gate run, so no earlier output is ever reused or needs deleting.
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$work = Join-Path $repo "target\gates\m1\$stamp"
$no = Join-Path $work 'says-no'
New-Item -ItemType Directory -Force $work, $no | Out-Null
$trackedBefore = @(git -C $up status --porcelain --untracked-files=no)

# --- Helpers ----------------------------------------------------------------------------------

function New-RunFrom([string]$from, [string]$label) {
    $dir = Join-Path $work $label
    New-Item -ItemType Directory -Force $dir | Out-Null
    Copy-Item (Join-Path $from '*') $dir -Recurse
    $cfg = Join-Path $dir 'config.xml'
    if (Test-Path $cfg) {
        (Get-Content $cfg -Raw).Replace('__RUNDIR__', "$dir\") | Set-Content $cfg -NoNewline -Encoding UTF8
    }
    return $dir
}
# One exact text edit of a file, which must match exactly once.
function Edit-Once([string]$file, [string]$old, [string]$new) {
    $text = [IO.File]::ReadAllText($file)
    $n = ([regex]::Matches($text, [regex]::Escape($old))).Count
    if ($n -ne 1) { throw "edit of ${file}: '$old' matches $n times, not once" }
    [IO.File]::WriteAllText($file, $text.Replace($old, $new), (New-Object Text.UTF8Encoding $false))
}
# Runs an executable with a hard time limit. Returns its exit code, or 'TIMEOUT' (which no check
# accepts) after killing it.
function Invoke-Solver([string]$exe, [string]$dir, [string[]]$argv, [int]$limitSec = 300) {
    $p = Start-Process -FilePath $exe -ArgumentList $argv -WorkingDirectory $dir -NoNewWindow -PassThru `
        -RedirectStandardOutput (Join-Path $dir '_stdout.txt') -RedirectStandardError (Join-Path $dir '_stderr.txt')
    $null = $p.Handle   # keeps ExitCode readable once the process has ended
    if (-not $p.WaitForExit($limitSec * 1000)) {
        Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
        Write-Host "      | TIMEOUT: $exe in $dir ran over $limitSec s and was killed"
        return 'TIMEOUT'
    }
    $p.WaitForExit()
    return $p.ExitCode
}
function Get-Outputs([string]$dir, [string[]]$inputs) {
    $h = @{}
    Get-ChildItem $dir -Recurse -File |
        Where-Object { $_.Name -notin $inputs -and $_.Name -notlike '_std*.txt' } |
        ForEach-Object { $h[$_.FullName.Substring($dir.Length + 1)] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash }
    return $h
}
function Compare-Outputs($a, $b) {
    $keys = @($a.Keys) + @($b.Keys) | Sort-Object -Unique
    return @($keys | Where-Object { $a[$_] -ne $b[$_] })
}
# .csbin (RSBIN surface receivers) is written by dumping whole C structs, padding included, so two
# runs of the SAME executable differ in 2 bytes per 8-byte record (verified 2026-09-23). Bytes are
# meaningless there; M1 checks the same files at the same sizes, and M2 compares them decoded.
function Get-Sizes([string]$dir) {
    $h = @{}
    Get-ChildItem $dir -Recurse -File -Filter *.csbin | ForEach-Object { $h[$_.FullName.Substring($dir.Length + 1)] = $_.Length }
    return $h
}
function Get-Sha([string]$path) { (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLower() }

# A PE32+ file's bytes with its link timestamps zeroed: the COFF header's TimeDateStamp and each
# debug-directory entry's. Returns the section table too.
function Read-MaskedPe([string]$path) {
    $d = [IO.File]::ReadAllBytes($path)
    $pe = [BitConverter]::ToInt32($d, 0x3C)
    if ([BitConverter]::ToUInt32($d, $pe) -ne 0x4550) { throw "$path is not a PE file" }
    $coff = $pe + 4
    $nsec = [BitConverter]::ToUInt16($d, $coff + 2)
    $optSize = [BitConverter]::ToUInt16($d, $coff + 16)
    $opt = $coff + 20
    if ([BitConverter]::ToUInt16($d, $opt) -ne 0x20B) { throw "$path is not PE32+" }
    [Array]::Clear($d, $coff + 4, 4)
    $dbgRva = [BitConverter]::ToUInt32($d, $opt + 112 + 48)
    $dbgSize = [BitConverter]::ToUInt32($d, $opt + 112 + 52)
    $sections = @()
    for ($i = 0; $i -lt $nsec; $i++) {
        $s = $opt + $optSize + 40 * $i
        $sec = [pscustomobject]@{
            Name = [Text.Encoding]::ASCII.GetString($d, $s, 8).TrimEnd([char]0)
            VSize = [BitConverter]::ToUInt32($d, $s + 8); Va = [BitConverter]::ToUInt32($d, $s + 12)
            RSize = [BitConverter]::ToUInt32($d, $s + 16); RPtr = [BitConverter]::ToUInt32($d, $s + 20)
        }
        $sections += $sec
        if ($dbgSize -gt 0 -and $dbgRva -ge $sec.Va -and $dbgRva -lt $sec.Va + $sec.VSize) {
            $off = $sec.RPtr + ($dbgRva - $sec.Va)
            for ($k = 0; $k -lt [int][math]::Floor($dbgSize / 28); $k++) { [Array]::Clear($d, $off + 28 * $k + 4, 4) }
        }
    }
    [pscustomobject]@{ Bytes = $d; Sections = $sections }
}
# How many bytes two PE files differ in outside their link timestamps; -1 when their sizes differ.
function Compare-Pe([string]$a, [string]$b) {
    $x = (Read-MaskedPe $a).Bytes; $y = (Read-MaskedPe $b).Bytes
    if ($x.Length -ne $y.Length) { return -1 }
    $sha = [Security.Cryptography.SHA256]::Create()
    if ([BitConverter]::ToString($sha.ComputeHash($x)) -eq [BitConverter]::ToString($sha.ComputeHash($y))) { return 0 }
    $n = 0
    for ($i = 0; $i -lt $x.Length; $i++) { if ($x[$i] -ne $y[$i]) { $n++ } }
    return $n
}
# A copy of a PE file with the middle byte of its .text section inverted.
function Copy-Flipped([string]$from, [string]$to) {
    $text = (Read-MaskedPe $from).Sections | Where-Object { $_.Name -eq '.text' }
    $d = [IO.File]::ReadAllBytes($from)
    $i = $text.RPtr + [int]($text.RSize / 2)
    $d[$i] = $d[$i] -bxor 0xFF
    [IO.File]::WriteAllBytes($to, $d)
    return $to
}
# The git blob id of a file's bytes, as `git hash-object --no-filters` gives it.
function Get-BlobId([string]$path) {
    $body = [IO.File]::ReadAllBytes($path)
    $head = [Text.Encoding]::ASCII.GetBytes("blob $($body.Length)`0")
    $sha1 = [Security.Cryptography.SHA1]::Create()
    return ([BitConverter]::ToString($sha1.ComputeHash([byte[]]($head + $body))) -replace '-', '').ToLower()
}
# The files of a folder whose blob ids are not upstream 4db335c's; empty when all match.
function Get-BlobMismatches([string]$dir) {
    @($blobs4db.Keys | Where-Object { -not (Test-Path -LiteralPath (Join-Path $dir $_)) -or (Get-BlobId (Join-Path $dir $_)) -ne $blobs4db[$_] })
}
# SHA256SUMS of the committed tree, as an ordered map name -> sha256.
function Read-Sums {
    $m = [ordered]@{}
    foreach ($line in Get-Content (Join-Path $tgSrc 'SHA256SUMS')) {
        if ($line -notmatch '^([0-9a-f]{64})  (\S+)$') { throw "SHA256SUMS: unreadable line '$line'" }
        $m[$Matches[2]] = $Matches[1]
    }
    return $m
}
# The files SHA256SUMS lists that a folder lacks or holds with other bytes; empty when it holds
# all of them unchanged.
function Get-SumMismatches([string]$dir) {
    $sums = Read-Sums
    if ($sums.Count -ne 8) { throw "SHA256SUMS lists $($sums.Count) files, not the tarball's 8" }
    @($sums.Keys | Where-Object { -not (Test-Path -LiteralPath (Join-Path $dir $_)) -or (Get-Sha (Join-Path $dir $_)) -ne $sums[$_] })
}
# Whether a solver manifest records this build: the pinned commit, TetGen 1.5.0 from the WIAS
# tarball with upstream 4db335c's blobs, the vendored files' hashes, and the shipped tetgen's hash.
function Test-Manifest($m) {
    $t = $m.tetgen
    if ($null -eq $t -or $null -eq $t.files_sha256) { return $false }
    $sums = Read-Sums
    $listed = @($t.files_sha256.PSObject.Properties)
    $filesOk = ($listed.Count -eq $sums.Count) -and (@($sums.Keys | Where-Object { $t.files_sha256.$_ -ne $sums[$_] }).Count -eq 0)
    return ($m.upstream_commit -eq $commit) -and ($t.version -eq '1.5.0') -and ($t.tarball_sha256 -eq $tarballSha) -and
        ($t.same_blobs_as_upstream -eq $blobCommit) -and $filesOk -and ($t.exe_sha256 -eq $m.sha256.'tetgen.exe')
}
function Test-ManifestHash([string]$path, [string]$name) {
    (Test-Path -LiteralPath $path) -and ((Get-Sha $path) -eq $manifest.sha256.$name)
}
# `tetgen -h`: TetGen prints its banner in the help text (in 1.5.0, -v selects Voronoi output).
function Test-Banner150([string]$exe, [string]$label) {
    $dir = Join-Path $work "banner-$label"
    New-Item -ItemType Directory -Force $dir | Out-Null
    $code = Invoke-Solver $exe $dir @('-h') 30
    $head = @(Get-Content (Join-Path $dir '_stdout.txt') -TotalCount 4)
    return ($code -eq 0) -and ($head.Count -eq 4) -and ($head[2] -ceq 'Version 1.5') -and ($head[3] -ceq 'November 4, 2013')
}
# A file's lines as bytes (Latin-1, one char per byte), terminators kept.
function Read-Lines([string]$path) {
    $text = [Text.Encoding]::GetEncoding(28591).GetString([IO.File]::ReadAllBytes($path))
    return @([regex]::Split($text, '(?<=\n)') | Where-Object { $_.Length -gt 0 })
}
# TetGen outputs against the 2019 tutorial files: every byte equal except the one
# '# Generated by' line each file ends with, which names the exe and input path.
function Compare-TetgenOutputs([string]$runDir, [string]$refDir) {
    $res = [ordered]@{}
    foreach ($ext in 'node', 'ele', 'face', 'neigh', 'edge') {
        $a = Join-Path $runDir "scene_mesh.1.$ext"; $b = Join-Path $refDir "scene_mesh.1.$ext"
        if (-not (Test-Path $a)) { $res[$ext] = 'missing'; continue }
        $la = Read-Lines $a; $lb = Read-Lines $b
        $ta = @($la | Where-Object { $_.StartsWith('# Generated by') }); $tb = @($lb | Where-Object { $_.StartsWith('# Generated by') })
        $ba = -join @($la | Where-Object { -not $_.StartsWith('# Generated by') })
        $bb = -join @($lb | Where-Object { -not $_.StartsWith('# Generated by') })
        $res[$ext] = if ($ta.Count -ne 1 -or $tb.Count -ne 1) { "trailer lines $($ta.Count)/$($tb.Count), not 1/1" }
                     elseif ($ba.Length -eq 0) { 'empty' }
                     elseif ($ba -ceq $bb) { 'identical' } else { 'differs' }
    }
    return $res
}
function Test-AllIdentical($res) { @($res.Values | Where-Object { $_ -ne 'identical' }).Count -eq 0 -and $res.Count -eq 5 }
function Get-Header([string]$path) { if (Test-Path $path) { [int]((Get-Content $path -TotalCount 1).Trim() -split '\s+')[0] } else { -1 } }
# tetgen -pq2 -A -n on tutorial 1's input, as upstream's GUI runs it for the tutorial's SPPS core
# (projet_maillage.cpp:163-171; minratio 2, no -a, no -Y, the .var for the floor receiver).
function Invoke-Tut1([string]$exe, [string]$label, [switch]$NoVar) {
    $d = Join-Path $work "tut1-$label"
    New-Item -ItemType Directory -Force $d | Out-Null
    Copy-Item (Join-Path $fix 'tetgen\scene_mesh.poly') $d
    if (-not $NoVar) { Copy-Item (Join-Path $fix 'tetgen\scene_mesh.var') $d }
    $code = Invoke-Solver $exe $d @('-pq2', '-A', '-n', 'scene_mesh.poly') 120
    $cmp = Compare-TetgenOutputs $d $t2019
    [pscustomobject]@{
        Exit = $code; Nodes = (Get-Header (Join-Path $d 'scene_mesh.1.node')); Tets = (Get-Header (Join-Path $d 'scene_mesh.1.ele'))
        Files = $cmp; Identical = (Test-AllIdentical $cmp)
        Summary = (($cmp.GetEnumerator() | ForEach-Object { "$($_.Key) $($_.Value)" }) -join ', ')
    }
}
function Test-Tut1Counts($r) { ($r.Exit -eq 0) -and ($r.Nodes -eq 732) -and ($r.Tets -eq 2257) }
# A value computed outside a check: on an error, the message (which no check accepts) instead of
# ending the gate before the remaining checks have run.
function Safe([scriptblock]$body) {
    try { & $body } catch { Write-Host "      | error: $($_.Exception.Message)"; "error: $($_.Exception.Message)" }
}
function Format-Exit($code) { if ($code -is [int]) { '0x{0:X8}' -f $code } else { "$code" } }

# --- (1) What we built is what the manifest says --------------------------------------------------

foreach ($exeName in 'spps.exe', 'classicalTheory.exe', 'tetgen.exe', 'preprocess.exe') {
    Check "$exeName exists and matches manifest.json" { Test-ManifestHash (Join-Path $bin $exeName) $exeName }
}
$flipped = Safe { Copy-Flipped $new.spps (Join-Path $no 'spps-flipped.exe') }
Check "says NO: spps.exe with one .text byte inverted does not match manifest.json" {
    (Test-Path -LiteralPath $flipped) -and -not (Test-ManifestHash $flipped 'spps.exe')
}

Check "manifest.json: solvers from $($commit.Substring(0,7)); tetgen 1.5.0 from tarball $($tarballSha.Substring(0,8)), blobs of upstream $($blobCommit.Substring(0,7)), exe hash consistent" {
    Test-Manifest $manifest
}
$oldManifest = Safe { $s = (git -C $repo show 'a8a0889:solvers/manifest.json') -join "`n"; $s.Substring($s.IndexOf('{')) | ConvertFrom-Json }
Check "says NO: the manifest of the 1.6.0 build (a8a0889, tetgen $("$($oldManifest.sha256.'tetgen.exe')".PadRight(8).Substring(0,8))) is refused" {
    ($oldManifest -isnot [string]) -and -not (Test-Manifest $oldManifest)
}

# --- (2) spps, classicalTheory and preprocess are the reference build ---------------------------

function Get-Missing([string[]]$paths) { @($paths | Where-Object { -not (Test-Path -LiteralPath $_) }) }
Check "reference binaries present (spps, classicalTheory, preprocess, tetgen 1.6.0)" { (Get-Missing @($ref.Values)).Count -eq 0 }
Check "says NO: the presence check refuses a reference list holding a path that does not exist" {
    (Get-Missing @($ref.spps, (Join-Path $up 'build_solvers\src\spps\Release\spps-missing.exe'))).Count -eq 1
}
foreach ($k in 'spps', 'tcr', 'preprocess') {
    $n = Safe { Compare-Pe $new.$k $ref.$k }
    Check "$(Split-Path -Leaf $new.$k) equals the 2026-09-08 reference byte for byte outside the link timestamps ($n differ)" { $n -eq 0 }
}
$n = Safe { Compare-Pe $flipped $ref.spps }
Check "says NO: spps.exe with one .text byte inverted differs from the reference outside the link timestamps ($n byte)" { $n -eq 1 }

# --- (3) TetGen 1.5.0: source ---------------------------------------------------------------------

$badSums = @(Safe { Get-SumMismatches $tgSrc })
Check "third_party/tetgen-1.5.0 holds the 8 files of WIAS tetgen1.5.0.tar.gz, unmodified (SHA256SUMS; $($badSums.Count) differ)" { $badSums.Count -eq 0 }
$badCopy = @(Safe {
    $srcCopy = Join-Path $no 'tetgen-src'
    New-Item -ItemType Directory -Force $srcCopy | Out-Null
    Copy-Item (Join-Path $tgSrc '*') $srcCopy
    [IO.File]::AppendAllText((Join-Path $srcCopy 'tetgen.h'), ' ')
    Get-SumMismatches $srcCopy
})
Check "says NO: a copy with one space appended to tetgen.h fails SHA256SUMS on tetgen.h alone ($($badCopy -join ', '))" {
    ($badCopy.Count -eq 1) -and ($badCopy[0] -eq 'tetgen.h')
}

$bad = @(Safe { Get-BlobMismatches $tgSrc })
Check "third_party/tetgen-1.5.0 holds upstream $($blobCommit.Substring(0,7))'s src/tetgen blobs: $($blobs4db.Keys -join ', ') ($($bad.Count) differ)" { $bad.Count -eq 0 }
$bad16 = @(Safe { Get-BlobMismatches (Join-Path $up 'src\tetgen') })
Check "says NO: upstream's src/tetgen at $($commit.Substring(0,7)) (TetGen 1.6.0) is refused ($($bad16 -join ', ') differ)" {
    (Test-Path -LiteralPath (Join-Path $up 'src\tetgen\tetgen.cxx')) -and ($bad16 -contains 'tetgen.cxx')
}

# --- (4) TetGen 1.5.0: build ----------------------------------------------------------------------

$refCmds = @(Safe { Get-BuildCommands (Join-Path $bld 'src\tetgen') (Join-Path $usrc 'src\tetgen') })
$cmdDiff = @(Safe { Compare-BuildCommands $refCmds (Get-BuildCommands $tgBld $tgSrc) })
Check "tetgen.exe was compiled and linked with the command lines of upstream's tetgen target ($($refCmds.Count) records, $($cmdDiff.Count) differ)" {
    ($refCmds.Count -eq 3) -and ($refCmds[0] -like 'CL ^*') -and ($cmdDiff.Count -eq 0)
}
$mutDiff = @(Safe {
    $mutTlog = Join-Path $no 'tetgen.tlog'
    Copy-Item (Join-Path $tgBld 'tetgen.dir\Release\tetgen.tlog') $mutTlog -Recurse
    $clLog = Join-Path $mutTlog 'CL.command.1.tlog'
    [IO.File]::WriteAllText($clLog, [IO.File]::ReadAllText($clLog).Replace(' /O2 ', ' /OD '), [Text.Encoding]::Unicode)
    Compare-BuildCommands $refCmds (Get-BuildCommands $tgBld $tgSrc $mutTlog)
})
Check "says NO: the same records with /O2 turned into /Od differ in both compile lines ($($mutDiff.Count) records)" {
    ($mutDiff.Count -eq 4) -and (@($mutDiff | Where-Object { $_.StartsWith('> CL') -and $_.Contains(' /OD ') }).Count -eq 2)
}

# A from-scratch build of the vendored source in this gate run must give bin\tetgen.exe again.
$rb = Join-Path $work 'tetgen-rebuild'
$rbLog = Join-Path $work 'tetgen-rebuild.log'
$rbExe = Join-Path $rb 'Release\tetgen.exe'
$ErrorActionPreference = 'Continue'   # native stderr must not throw under Windows PowerShell 5.1
& cmake -S (Join-Path $repo 'solvers\tetgen') -B $rb -G 'Visual Studio 17 2022' -A x64 -DCMAKE_BUILD_TYPE=Release "-DTETGEN_SOURCE_DIR=$tgSrc" 2>&1 | ForEach-Object { "$_" } | Set-Content $rbLog
$rbConfigure = $LASTEXITCODE
& cmake --build $rb --config Release --parallel --target tetgen 2>&1 | ForEach-Object { "$_" } | Add-Content $rbLog
$rbBuild = $LASTEXITCODE
$ErrorActionPreference = 'Stop'
$n = if (Test-Path $rbExe) { Safe { Compare-Pe $rbExe $new.tetgen } } else { 'no exe' }
Check "a from-scratch build of third_party/tetgen-1.5.0 (configure $rbConfigure, build $rbBuild) gives bin\tetgen.exe byte for byte outside the link timestamps ($n differ)" {
    ($rbConfigure -eq 0) -and ($rbBuild -eq 0) -and ($n -eq 0)
}
$n16 = Safe { Compare-Pe $tg16 $new.tetgen }
Check "says NO: upstream's 1.6.0 tetgen from the same build is not bin\tetgen.exe (compare gives $n16)" { ($n16 -is [int]) -and ($n16 -ne 0) }
$rbDiff = @(if (Test-Path $rbExe) { Safe { Compare-BuildCommands $refCmds (Get-BuildCommands $rb $tgSrc) } } else { 'no build' })
Check "the from-scratch build used the command lines of upstream's tetgen target ($($rbDiff.Count) differ)" { $rbDiff.Count -eq 0 }
$sppsCmdDiff = @(Safe {
    $sppsTlog = Join-Path $bld 'src\spps\spps.dir\Release\spps.tlog'
    Compare-BuildCommands $refCmds (Get-BuildCommands (Join-Path $bld 'src\spps') (Join-Path $usrc 'src\spps') $sppsTlog)
})
Check "says NO: the command-line comparison refuses the spps target's records read as tetgen's ($($sppsCmdDiff.Count) records differ)" {
    ($sppsCmdDiff.Count -gt 0) -and -not ("$($sppsCmdDiff[0])".StartsWith('error:'))
}

# --- (5) TetGen 1.5.0: behaviour ------------------------------------------------------------------

Check "tetgen.exe -h prints 'Version 1.5' and 'November 4, 2013'" { Test-Banner150 $new.tetgen 'ours' }
Check "says NO: upstream's 1.6.0 tetgen from the same build is refused (it prints 'Version 1.6')" { -not (Test-Banner150 $tg16 'upstream160') }

# The 2019 tutorial-1 mesh, from upstream's tutorial_1.proj, read at gate time.
$t2019 = Join-Path $work 'tut1-2019'
$null = Safe {
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $proj = Join-Path $up 'src\isimpa\resources\doc\tutorial\tutorial 1\tutorial_1.proj'
    New-Item -ItemType Directory -Force $t2019 | Out-Null
    $zip = [IO.Compression.ZipFile]::OpenRead($proj)
    try {
        foreach ($e in $zip.Entries) {
            if ($e.FullName -match '^instance2/temp/([^/]+)$') {
                [IO.Compression.ZipFileExtensions]::ExtractToFile($e, (Join-Path $t2019 $Matches[1]), $true)
            }
        }
    } finally { $zip.Dispose() }
}
function Test-SameBytes([string]$a, [string]$b) { (Test-Path -LiteralPath $a) -and (Test-Path -LiteralPath $b) -and ((Get-Sha $a) -eq (Get-Sha $b)) }
Check "tutorial 1: the fixture's .poly and .var are the 2019 project's temp files, byte for byte" {
    (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.poly') (Join-Path $t2019 'scene_mesh.poly')) -and
    (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.var') (Join-Path $t2019 'scene_mesh.var'))
}
$varCrlf = Safe {
    $p = Join-Path $no 'scene_mesh.var'
    Copy-Item (Join-Path $t2019 'scene_mesh.var') $p
    [IO.File]::AppendAllText($p, "`r`n")
    $p
}
Check "says NO: the byte comparison refuses the 2019 .var with a final CRLF added" {
    (Test-Path -LiteralPath $varCrlf) -and -not (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.var') $varCrlf)
}

# Each refusal below comes from a TetGen that ran and exited 0: it is refused for its mesh.
function Test-Refused($r) { ($r -isnot [string]) -and ($r.Exit -eq 0) -and (-not (Test-Tut1Counts $r)) -and (-not $r.Identical) }
$t1 = Safe { Invoke-Tut1 $new.tetgen 'ours' }
Check "tutorial 1, tetgen.exe -pq2 -A -n with the .var: exit $($t1.Exit), $($t1.Nodes) nodes, $($t1.Tets) tets (2019: 732, 2257)" { Test-Tut1Counts $t1 }
Check "tutorial 1: .1.node/.ele/.face/.neigh/.edge equal the 2019 files byte for byte, trailer line aside ($($t1.Summary))" { $t1.Identical -eq $true }
$n1 = Safe { Invoke-Tut1 $tg16 'upstream160' }
Check "says NO: upstream's 1.6.0 tetgen from the same build (exit $($n1.Exit)) is refused by both: $($n1.Nodes) nodes, $($n1.Tets) tets; $($n1.Summary)" { Test-Refused $n1 }
$n2 = Safe { Invoke-Tut1 $ref.tetgen16 'reference160' }
Check "says NO: the pinned 1.6.0 reference tetgen (exit $($n2.Exit)) is refused by both: $($n2.Nodes) nodes, $($n2.Tets) tets" { Test-Refused $n2 }
$n3 = Safe { Invoke-Tut1 $new.tetgen 'ours-novar' -NoVar }
Check "says NO: tetgen.exe without the .var, no area bound on the floor (exit $($n3.Exit)), is refused by both: $($n3.Nodes) nodes, $($n3.Tets) tets" { Test-Refused $n3 }

# --- (6) SPPS, seeded, new against reference ------------------------------------------------------

# Each says-NO input is a run that happened (an integer exit code): it is refused for what it
# produced, never because it failed to start.
function Ran($code) { $code -is [int] }
$sppsInputs = @('config.xml', 'mesh.cbin', 'tetramesh.mbin', 'expected.json')
function Invoke-Run([string]$exe, [string]$from, [string]$label, $edit) {
    Safe {
        $dir = New-RunFrom $from $label
        if ($edit) { Edit-Once (Join-Path $dir 'config.xml') $edit[0] $edit[1] }
        $code = Invoke-Solver $exe $dir @('config.xml')
        [pscustomobject]@{ Dir = $dir; Exit = $code; Out = (Get-Outputs $dir $sppsInputs); Sizes = (Get-Sizes $dir) }
    }
}
$fixRuns = Join-Path $repo 'tests\fixtures\runs'
$sNew = Invoke-Run $new.spps (Join-Path $fix 'spps') 'spps-new'
$sRef = Invoke-Run $ref.spps (Join-Path $fix 'spps') 'spps-ref'
# says-NO inputs: the committed crash fixture (source outside the cube), and seed 2
$sOut = Invoke-Run $new.spps (Join-Path $fixRuns 'spps_srcout') 'spps-srcout'
$sSeed2 = Invoke-Run $new.spps (Join-Path $fix 'spps') 'spps-seed2' @('random_seed="1"', 'random_seed="2"')
$tNew = Invoke-Run $new.tcr (Join-Path $fix 'tcr') 'tcr-new'
$tRef = Invoke-Run $ref.tcr (Join-Path $fix 'tcr') 'tcr-ref'
# says-NO inputs: the committed no-mesh fixture, and the tutorial with its source moved 0.5 m
$tNoMesh = Invoke-Run $new.tcr (Join-Path $fixRuns 'tcr_nomesh') 'tcr-nomesh'
$tMoved = Invoke-Run $new.tcr (Join-Path $fix 'tcr') 'tcr-source-moved' @('name="Source 1" x="3"', 'name="Source 1" x="3.5"')

function Test-SppsBanner($r) { (Get-Content (Join-Path $r.Dir '_stdout.txt') -TotalCount 1) -match '^SPPS version 2\.2\.1' }
function Test-End($r) { Select-String -Path (Join-Path $r.Dir '_stdout.txt') -Pattern '^End of calculation' -Quiet }
function Test-Produced($a, $b) { ($a.Out.Count -gt 0) -and ($b.Out.Count -eq $a.Out.Count) }
function Get-StatDiff($diff) { @($diff | Where-Object { $_ -like '*.recp' -or $_ -like '*particle statistics.gabe' }) }
function Get-NonCsbin($diff) { @($diff | Where-Object { $_ -notlike '*.csbin' }) }
function Test-SameSizes($a, $b) { @(Compare-Outputs $a.Sizes $b.Sizes).Count -eq 0 }

Check "SPPS banner is version 2.2.1" { Test-SppsBanner $sNew }
Check "says NO: the banner check refuses TCR's first stdout line" { (Ran $tNew.Exit) -and -not (Test-SppsBanner $tNew) }
Check "SPPS exits 0 on both (new $($sNew.Exit), reference $($sRef.Exit))" { $sNew.Exit -eq 0 -and $sRef.Exit -eq 0 }
Check "says NO: SPPS on tests/fixtures/runs/spps_srcout exits $(Format-Exit $sOut.Exit), and the exit check refuses it" { (Ran $sOut.Exit) -and -not ($sOut.Exit -eq 0) }
Check "SPPS reaches 'End of calculation' on both" { (Test-End $sNew) -and (Test-End $sRef) }
Check "says NO: the spps_srcout run never reaches it" { (Ran $sOut.Exit) -and -not (Test-End $sOut) }
Check "SPPS produced output on both (new $($sNew.Out.Count), reference $($sRef.Out.Count) files)" { Test-Produced $sNew $sRef }
Check "says NO: the spps_srcout run is refused ($($sOut.Out.Count) output files)" { (Ran $sOut.Exit) -and -not (Test-Produced $sOut $sRef) }
$diff = @(Compare-Outputs $sNew.Out $sRef.Out)
$diff2 = @(Compare-Outputs $sSeed2.Out $sRef.Out)
# The seed-2 run must be a complete run (exit 0, the reference's file set) refused for its values.
$seed2Whole = ($sSeed2.Exit -eq 0) -and ($sSeed2.Out.Count -eq $sRef.Out.Count) -and ($sSeed2.Out.Count -gt 0)
Check "SPPS stats GABE and every .recp byte-identical" { (Get-StatDiff $diff).Count -eq 0 }
Check "says NO: the seed-2 run (exit $($sSeed2.Exit), $($sSeed2.Out.Count) files) differs from the reference in them ($((Get-StatDiff $diff2).Count) files)" { $seed2Whole -and (Get-StatDiff $diff2).Count -gt 0 }
Check "SPPS every non-.csbin output byte-identical ($((Get-NonCsbin $diff).Count) differ)" { (Get-NonCsbin $diff).Count -eq 0 }
Check "says NO: the seed-2 run is refused ($((Get-NonCsbin $diff2).Count) differ)" { $seed2Whole -and (Get-NonCsbin $diff2).Count -gt 0 }
Check "SPPS .csbin: same files at the same sizes ($($sNew.Sizes.Count) files)" { ($sNew.Sizes.Count -gt 0) -and (Test-SameSizes $sNew $sRef) }
Check "says NO: the spps_srcout run's .csbin set is refused ($($sOut.Sizes.Count) files)" { (Ran $sOut.Exit) -and -not (Test-SameSizes $sOut $sRef) }

# --- (7) TCR, deterministic, new against reference ------------------------------------------------

Check "TCR exits 0 on both (new $($tNew.Exit), reference $($tRef.Exit))" { $tNew.Exit -eq 0 -and $tRef.Exit -eq 0 }
Check "says NO: TCR on tests/fixtures/runs/tcr_nomesh exits $(Format-Exit $tNoMesh.Exit), and the exit check refuses it" { (Ran $tNoMesh.Exit) -and -not ($tNoMesh.Exit -eq 0) }
Check "TCR produced output on both (new $($tNew.Out.Count), reference $($tRef.Out.Count) files)" { Test-Produced $tNew $tRef }
Check "says NO: the tcr_nomesh run is refused ($($tNoMesh.Out.Count) output files)" { (Ran $tNoMesh.Exit) -and -not (Test-Produced $tNoMesh $tRef) }
$diff = @(Compare-Outputs $tNew.Out $tRef.Out)
$diffMoved = @(Compare-Outputs $tMoved.Out $tRef.Out)
$movedWhole = ($tMoved.Exit -eq 0) -and ($tMoved.Out.Count -eq $tRef.Out.Count) -and ($tMoved.Out.Count -gt 0)
Check "TCR every non-.csbin output byte-identical ($((Get-NonCsbin $diff).Count) differ)" { (Get-NonCsbin $diff).Count -eq 0 }
Check "says NO: the run with the source moved 0.5 m (exit $($tMoved.Exit), $($tMoved.Out.Count) files) is refused ($((Get-NonCsbin $diffMoved).Count) differ)" { $movedWhole -and (Get-NonCsbin $diffMoved).Count -gt 0 }
Check "TCR .csbin: same files at the same sizes ($($tNew.Sizes.Count) files)" { ($tNew.Sizes.Count -gt 0) -and (Test-SameSizes $tNew $tRef) }
Check "says NO: the tcr_nomesh run's .csbin set is refused ($($tNoMesh.Sizes.Count) files)" { (Ran $tNoMesh.Exit) -and -not (Test-SameSizes $tNoMesh $tRef) }

# --- (8) The upstream checkout was not touched ----------------------------------------------------

function Test-Clean($lines) { @($lines | Where-Object { $_ }).Count -eq 0 }
$trackedAfter = @(git -C $up status --porcelain --untracked-files=no)
Check "upstream tracked files untouched (before $($trackedBefore.Count), after $($trackedAfter.Count) changed)" { (Test-Clean $trackedBefore) -and (Test-Clean $trackedAfter) }
Check "says NO: the cleanliness check refuses a listing with one modified file" { -not (Test-Clean @(' M src/spps/main.cpp')) }
$upHead = git -C $up rev-parse HEAD
Check "upstream HEAD still $($commit.Substring(0,7))" { $upHead -eq $commit }
$ownHead = git -C $repo rev-parse HEAD
Check "says NO: the HEAD check refuses this repo's own HEAD ($($ownHead.Substring(0,7)))" { -not ($ownHead -eq $commit) }

Write-Host "`nrun folders: $work"
Write-Host "$script:checks checks, $($failures.Count) failed"
if ($failures.Count) { Write-Host "M1 FAILED: $($failures.Count) check(s)"; exit 1 }
Write-Host "M1 PASSED"; exit 0
