# M1 gate: the solvers we build are upstream's unchanged solvers, and the mesher is TetGen 1.5.0.
# - bin\ is solvers/manifest.json's build by code sha256 (solvers/pe-fingerprint.ps1): the sha256
#   with the link timestamps zeroed. MSVC writes the link time into the COFF header and the debug
#   directory, and nowhere else in these builds, so every build of the same code has the manifest's
#   code sha256 and its own sha256; the gate holds bin\ to the first and prints the second.
# - spps, classicalTheory and preprocess come from the pinned commit 929a5c8 and must equal the
#   2026-09-08 reference build byte for byte outside the link timestamps, and
#   produce the reference's outputs from identical, seeded inputs.
# - tetgen.exe is WIAS TetGen 1.5.0 from third_party/tetgen-1.5.0, the TetGen upstream shipped in
#   1.3.3 and 1.3.4 (decision of 2026-09-23, target/investigate/DECISIONS.md). It is checked by
#   its source (the committed WIAS tarball, hashed and read member by member in this run, and
#   upstream 4db335c's blobs), by its build (upstream's tetgen command lines, case-sensitive, and
#   a from-scratch rebuild in this gate run that must give bin\tetgen.exe again), and by what it
#   does: upstream's tutorial 1 and 3 inputs must mesh to the 2019 tutorial files byte for byte,
#   the '# Generated by' trailer line aside. (Tutorial 2 is measured in PROVENANCE.md, not here:
#   its outputs are 19 MB a run, and its .node text depends on the printf rounding a binary was
#   linked with, which upstream's own 1.3.3 and 1.3.4 builds already differ in.)
# Every check that can pass has a "says NO" partner: an input it must refuse. The TetGen checks
# refuse upstream's own 1.6.0 tetgen, built in the same run by solvers/build.ps1.
# Each run writes a new folder under target\gates\m1 and deletes nothing; the last line says how
# much the kept runs hold.
# Run from anywhere: powershell -File tools/gates/m1.ps1 [-Solvers <folder>]
param(
    # The build under test, a folder this checkout's solvers/build.ps1 built into (its -Root):
    # bin\, the build trees (named by solvers/manifest.json) and src-929a5c8\. Default
    # <repo>\target\solvers. Another checkout's build fails the TetGen command-line check: its
    # records name that checkout's third_party folder, which is not the one read here.
    [string]$Solvers = ''
)
$ErrorActionPreference = 'Stop'
$failures = @(); $script:checks = 0
# A check body returns exactly one bool. Anything else (no value, several values, a non-bool)
# is a FAIL: a stray value leaking into the pipeline must never turn into a PASS.
function Check($name, [scriptblock]$body) {
    $script:checks++
    try {
        $r = @(& $body)
        if ($r.Count -eq 1 -and $r[0] -is [bool] -and $r[0]) {
            Write-Host "PASS  $name"
        } elseif ($r.Count -eq 1 -and $r[0] -is [bool]) {
            Write-Host "FAIL  $name"; $script:failures += $name
        } else {
            Write-Host "FAIL  $name :: the check returned $($r.Count) values, not one bool"; $script:failures += $name
        }
    } catch {
        Write-Host "FAIL  $name :: $($_.Exception.Message)"; $script:failures += $name
    }
}

$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$up = 'B:\repos\I-Simpa-upstream'
$commit = '929a5c8e5f590b189f29155faeff8670f3699479'
$solvers = if ($Solvers) { [IO.Path]::GetFullPath($Solvers) } else { Join-Path $repo 'target\solvers' }
$bin = Join-Path $solvers 'bin'
Write-Host "solvers: $solvers"
$fix = Join-Path $repo 'tests\fixtures\upstream\tutorial1'
$tgSrc = Join-Path $repo 'third_party\tetgen-1.5.0'
$tarball = Join-Path $tgSrc 'tetgen1.5.0.tar.gz'
$manifest = Get-Content (Join-Path $repo 'solvers\manifest.json') -Raw | ConvertFrom-Json
$bld = Join-Path $solvers $manifest.build_dir
$tgBld = Join-Path $solvers $manifest.tetgen.build_dir
$usrc = Join-Path $solvers ('src-' + $commit.Substring(0, 7))
# upstream's own 1.6.0 tetgen target, built by solvers/build.ps1 beside ours and never shipped
$tg16 = Join-Path $bld 'src\tetgen\Release\tetgen.exe'
$ref = @{
    spps       = Join-Path $up 'build_solvers\src\spps\Release\spps.exe'
    tcr        = Join-Path $up 'build_solvers\src\ctr\Release\classicalTheory.exe'
    preprocess = Join-Path $up 'build_solvers\src\preprocess\Release\preprocess.exe'
    tetgen16   = Join-Path $up 'build_solvers\src\tetgen\Release\tetgen.exe'
}
$new = @{
    spps       = Join-Path $bin 'spps.exe'
    tcr        = Join-Path $bin 'classicalTheory.exe'
    preprocess = Join-Path $bin 'preprocess.exe'
    tetgen     = Join-Path $bin 'tetgen.exe'
}
# The git blob ids of upstream's src/tetgen at 4db335c (2016-08-11, "Build tetgen from sources";
# unchanged up to a0d4d43, the parent of the 1.6 update ef2f764). WIAS's tarball sha256 is
# $TetgenTarballSha256, from solvers/tetgen/source.ps1, the one place it is written.
$blobCommit = '4db335c123eb54986015dbd8192aa8a7e0ec0969'
$blobs4db = [ordered]@{
    'tetgen.cxx'     = 'da4ef3d73513af1acad895153b65e5d80f66842b'
    'tetgen.h'       = '3196e031f5318369c6842296cf58fa45a2af611b'
    'predicates.cxx' = '33817d7999cf04ee831bcae75e053a39d9b783cb'
    'LICENSE'        = 'e253c3d965ddda3797c1ce80fedde3c84c54ecd4'
    'README'         = 'bc5cfa04c0e901cb5c5890b9783a781fa31eda1a'
}
. (Join-Path $repo 'solvers\tetgen\build-commands.ps1')
. (Join-Path $repo 'solvers\tetgen\source.ps1')
. (Join-Path $repo 'solvers\pe-fingerprint.ps1')
Add-Type -AssemblyName System.IO.Compression.FileSystem

# Fresh folder per gate run, so no earlier output is ever reused or needs deleting.
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$work = Join-Path $repo "target\gates\m1\$stamp"
$no = Join-Path $work 'says-no'
New-Item -ItemType Directory -Force $work, $no | Out-Null
# A checkout's changed tracked files, one porcelain line each. A git failure is a line too, so a
# folder git cannot read never passes for a clean one.
function Get-TrackedChanges([string]$path) {
    $ErrorActionPreference = 'Continue'
    $out = @(& git -C $path status --porcelain --untracked-files=no 2>&1 | ForEach-Object { "$_" })
    if ($LASTEXITCODE -ne 0) { return @("git status exited $LASTEXITCODE") + $out }
    return $out
}
# A checkout's HEAD commit, or a 'no HEAD' text when git cannot name one.
function Get-Head([string]$path) {
    $ErrorActionPreference = 'Continue'
    $h = @(& git -C $path rev-parse --verify -q HEAD 2>$null)
    if ($LASTEXITCODE -ne 0 -or $h.Count -ne 1) { return "no HEAD (git exit $LASTEXITCODE)" }
    return "$($h[0])"
}
$trackedBefore = @(Get-TrackedChanges $up)

# --- Helpers ----------------------------------------------------------------------------------

function New-RunFrom([string]$from, [string]$label) {
    $dir = Join-Path $work $label
    New-Item -ItemType Directory -Force $dir | Out-Null
    Copy-Item (Join-Path $from '*') $dir -Recurse
    $cfg = Join-Path $dir 'config.xml'
    if (Test-Path $cfg) {
        (Get-Content $cfg -Raw).Replace('__RUNDIR__', "$dir\") | Set-Content $cfg -NoNewline -Encoding UTF8
    }
    return $dir
}
# One exact text edit of a file, which must match exactly once.
function Edit-Once([string]$file, [string]$old, [string]$new) {
    $text = [IO.File]::ReadAllText($file)
    $n = ([regex]::Matches($text, [regex]::Escape($old))).Count
    if ($n -ne 1) { throw "edit of ${file}: '$old' matches $n times, not once" }
    [IO.File]::WriteAllText($file, $text.Replace($old, $new), (New-Object Text.UTF8Encoding $false))
}
# Runs an executable with a hard time limit. Returns its exit code, or 'TIMEOUT' (which no check
# accepts) after killing it.
function Invoke-Solver([string]$exe, [string]$dir, [string[]]$argv, [int]$limitSec = 300) {
    $p = Start-Process -FilePath $exe -ArgumentList $argv -WorkingDirectory $dir -NoNewWindow -PassThru `
        -RedirectStandardOutput (Join-Path $dir '_stdout.txt') -RedirectStandardError (Join-Path $dir '_stderr.txt')
    $null = $p.Handle   # keeps ExitCode readable once the process has ended
    if (-not $p.WaitForExit($limitSec * 1000)) {
        Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
        Write-Host "      | TIMEOUT: $exe in $dir ran over $limitSec s and was killed"
        return 'TIMEOUT'
    }
    $p.WaitForExit()
    return $p.ExitCode
}
function Get-Outputs([string]$dir, [string[]]$inputs) {
    $h = @{}
    Get-ChildItem $dir -Recurse -File |
        Where-Object { $_.Name -notin $inputs -and $_.Name -notlike '_std*.txt' } |
        ForEach-Object { $h[$_.FullName.Substring($dir.Length + 1)] = (Get-FileHash $_.FullName -Algorithm SHA256).Hash }
    return $h
}
function Compare-Outputs($a, $b) {
    $keys = @($a.Keys) + @($b.Keys) | Sort-Object -Unique
    return @($keys | Where-Object { $a[$_] -ne $b[$_] })
}
# .csbin (RSBIN surface receivers) is written by dumping whole C structs, padding included, so two
# runs of the SAME executable differ in 2 bytes per 8-byte record (verified 2026-09-23). Bytes are
# meaningless there; M1 checks the same files at the same sizes, and M2 compares them decoded.
function Get-Sizes([string]$dir) {
    $h = @{}
    Get-ChildItem $dir -Recurse -File -Filter *.csbin | ForEach-Object { $h[$_.FullName.Substring($dir.Length + 1)] = $_.Length }
    return $h
}
function Get-Sha([string]$path) { Get-RawSha256 $path }
# The first 16 hex digits of a hash, or what came instead (an error text) as it is.
function Short($h) { if ("$h" -match '^[0-9a-f]{64}$') { "$h".Substring(0, 16) } else { "$h" } }

# How many bytes two PE files differ in outside their link timestamps (the fields the code sha256
# zeroes, solvers/pe-fingerprint.ps1); -1 when their sizes differ.
function Compare-Pe([string]$a, [string]$b) {
    $x = Get-PeCodeBytes $a; $y = Get-PeCodeBytes $b
    if ($x.Length -ne $y.Length) { return -1 }
    if ((ConvertTo-Sha256Hex $x) -eq (ConvertTo-Sha256Hex $y)) { return 0 }
    $n = 0
    for ($i = 0; $i -lt $x.Length; $i++) { if ($x[$i] -ne $y[$i]) { $n++ } }
    return $n
}
# A copy of a PE file with the middle byte of its .text section inverted.
function Copy-Flipped([string]$from, [string]$to) { Copy-PeFlippedText $from $to }
# A copy of any file with its middle byte inverted.
function Copy-FlippedFile([string]$from, [string]$to) {
    $d = [IO.File]::ReadAllBytes($from)
    $i = [int]($d.Length / 2)
    $d[$i] = $d[$i] -bxor 0xFF
    [IO.File]::WriteAllBytes($to, $d)
    return $to
}
# The git blob id of a file's bytes, as `git hash-object --no-filters` gives it.
function Get-BlobId([string]$path) {
    $body = [IO.File]::ReadAllBytes($path)
    $head = [Text.Encoding]::ASCII.GetBytes("blob $($body.Length)`0")
    $sha1 = [Security.Cryptography.SHA1]::Create()
    return ([BitConverter]::ToString($sha1.ComputeHash([byte[]]($head + $body))) -replace '-', '').ToLower()
}
# The files of a folder whose blob ids are not upstream 4db335c's; empty when all match.
function Get-BlobMismatches([string]$dir) {
    @($blobs4db.Keys | Where-Object { -not (Test-Path -LiteralPath (Join-Path $dir $_)) -or (Get-BlobId (Join-Path $dir $_)) -ne $blobs4db[$_] })
}
# Whether a solver manifest records this build: the pinned commit; TetGen 1.5.0 whose tarball
# sha256 is the one this run computed from the committed tarball (and that is WIAS's); the
# member hashes this run read out of that tarball; upstream 4db335c's blobs; the shipped
# tetgen's hashes; and a code sha256 for each of the four executables and the 1.6.0 reference.
function Test-Manifest($m) {
    $t = $m.tetgen
    if ($null -eq $t -or $null -eq $t.files_sha256 -or $tarMembers -isnot [Collections.IDictionary]) { return $false }
    $listed = @($t.files_sha256.PSObject.Properties)
    $filesOk = ($listed.Count -eq $tarMembers.Count) -and (@($tarMembers.Keys | Where-Object { $t.files_sha256.$_ -ne $tarMembers[$_] }).Count -eq 0)
    $hex = '^[0-9a-f]{64}$'
    $codeOk = ($null -ne $m.code_sha256) -and (@($m.code_sha256.PSObject.Properties).Count -eq 4) -and
        (@('spps.exe', 'classicalTheory.exe', 'tetgen.exe', 'preprocess.exe' | Where-Object { "$($m.code_sha256.$_)" -notmatch $hex }).Count -eq 0) -and
        ("$($t.upstream_160_reference_code_sha256)" -match $hex)
    return ($m.upstream_commit -eq $commit) -and ($t.version -eq '1.5.0') -and ($tarSha -eq $TetgenTarballSha256) -and
        ($t.tarball_sha256 -eq $tarSha) -and ($t.same_blobs_as_upstream -eq $blobCommit) -and $filesOk -and
        ($t.exe_sha256 -eq $m.sha256.'tetgen.exe') -and $codeOk -and ($t.exe_code_sha256 -eq $m.code_sha256.'tetgen.exe')
}
# Whether a file is the manifest's build of `name`: its code sha256 is the manifest's. Its sha256,
# which every link changes, is not held; see Get-LinkNote.
function Test-ManifestHash([string]$path, [string]$name) {
    (Test-Path -LiteralPath $path) -and ("$($manifest.code_sha256.$name)" -match '^[0-9a-f]{64}$') -and
        ((Get-CodeSha256 $path) -eq $manifest.code_sha256.$name)
}
# The file's sha256 against the manifest's: the same link, or another link of it.
function Get-LinkNote([string]$path, [string]$name) {
    $raw = Get-RawSha256 $path
    if ($raw -eq $manifest.sha256.$name) { "sha256 $(Short $raw), the manifest's link" }
    else { "sha256 $(Short $raw), another link than the manifest's $(Short $manifest.sha256.$name)" }
}
# `tetgen -h`: TetGen prints its banner in the help text (in 1.5.0, -v selects Voronoi output).
function Test-Banner150([string]$exe, [string]$label) {
    $dir = Join-Path $work "banner-$label"
    New-Item -ItemType Directory -Force $dir | Out-Null
    $code = Invoke-Solver $exe $dir @('-h') 30
    $head = @(Get-Content (Join-Path $dir '_stdout.txt') -TotalCount 4)
    return ($code -eq 0) -and ($head.Count -eq 4) -and ($head[2] -ceq 'Version 1.5') -and ($head[3] -ceq 'November 4, 2013')
}
# A file's lines as bytes (Latin-1, one char per byte), terminators kept.
function Read-Lines([string]$path) {
    $text = [Text.Encoding]::GetEncoding(28591).GetString([IO.File]::ReadAllBytes($path))
    return @([regex]::Split($text, '(?<=\n)') | Where-Object { $_.Length -gt 0 })
}
# TetGen outputs against the 2019 tutorial files: every byte equal except the one
# '# Generated by' line each file ends with, which names the exe and input path.
function Compare-TetgenOutputs([string]$runDir, [string]$refDir) {
    $res = [ordered]@{}
    foreach ($ext in 'node', 'ele', 'face', 'neigh', 'edge') {
        $a = Join-Path $runDir "scene_mesh.1.$ext"; $b = Join-Path $refDir "scene_mesh.1.$ext"
        if (-not (Test-Path $a)) { $res[$ext] = 'missing'; continue }
        $la = Read-Lines $a; $lb = Read-Lines $b
        $ta = @($la | Where-Object { $_.StartsWith('# Generated by') }); $tb = @($lb | Where-Object { $_.StartsWith('# Generated by') })
        $ba = -join @($la | Where-Object { -not $_.StartsWith('# Generated by') })
        $bb = -join @($lb | Where-Object { -not $_.StartsWith('# Generated by') })
        $res[$ext] = if ($ta.Count -ne 1 -or $tb.Count -ne 1) { "trailer lines $($ta.Count)/$($tb.Count), not 1/1" }
                     elseif ($ba.Length -eq 0) { 'empty' }
                     elseif ($ba -ceq $bb) { 'identical' } else { 'differs' }
    }
    return $res
}
function Test-AllIdentical($res) { @($res.Values | Where-Object { $_ -ne 'identical' }).Count -eq 0 -and $res.Count -eq 5 }
function Get-Header([string]$path) { if (Test-Path $path) { [int]((Get-Content $path -TotalCount 1).Trim() -split '\s+')[0] } else { -1 } }
# A tutorial's 2019 temp folder, read out of upstream's tutorial_<n>.proj (a zip) at gate time:
# the .poly (and .var) upstream's GUI gave TetGen, and the .1.* files TetGen gave back.
function Get-Tutorial2019([int]$n) {
    $dir = Join-Path $work "tut$n-2019"
    New-Item -ItemType Directory -Force $dir | Out-Null
    $proj = Join-Path $up "src\isimpa\resources\doc\tutorial\tutorial $n\tutorial_$n.proj"
    $zip = [IO.Compression.ZipFile]::OpenRead($proj)
    try {
        $temp = @($zip.Entries | Where-Object { $_.FullName -match '^instance\d+/temp/[^/]+$' })
        $inst = @($temp | ForEach-Object { $_.FullName.Split('/')[0] } | Sort-Object -Unique)
        if ($inst.Count -ne 1) { throw "tutorial_$n.proj has temp files under $($inst.Count) instances, not 1" }
        foreach ($e in $temp) { [IO.Compression.ZipFileExtensions]::ExtractToFile($e, (Join-Path $dir $e.Name), $true) }
    } finally { $zip.Dispose() }
    return $dir
}
# tetgen -pq2 -A -n on a tutorial's 2019 input, as upstream's GUI ran it (projet_maillage.cpp:
# 163-171, and the trailer of every 2019 .1.* file; minratio 2, no -a, no -Y). The .var, where
# the tutorial has one, carries the surface receiver's area bound.
function Invoke-Tut([int]$n, [string]$exe, [string]$label, [switch]$NoVar) {
    $refDir = $y2019[$n]
    $d = Join-Path $work "tut$n-$label"
    New-Item -ItemType Directory -Force $d | Out-Null
    Copy-Item (Join-Path $refDir 'scene_mesh.poly') $d
    if (-not $NoVar -and (Test-Path (Join-Path $refDir 'scene_mesh.var'))) { Copy-Item (Join-Path $refDir 'scene_mesh.var') $d }
    $code = Invoke-Solver $exe $d @('-pq2', '-A', '-n', 'scene_mesh.poly') 120
    $cmp = Compare-TetgenOutputs $d $refDir
    [pscustomobject]@{
        Exit = $code; Nodes = (Get-Header (Join-Path $d 'scene_mesh.1.node')); Tets = (Get-Header (Join-Path $d 'scene_mesh.1.ele'))
        Files = $cmp; Identical = (Test-AllIdentical $cmp)
        Summary = (($cmp.GetEnumerator() | ForEach-Object { "$($_.Key) $($_.Value)" }) -join ', ')
    }
}
# The 2019 node and tet counts (the first number of each .1.node and .1.ele header).
$counts2019 = @{ 1 = @(732, 2257); 3 = @(835, 3285) }
function Test-TutCounts([int]$n, $r) { ($r.Exit -eq 0) -and ($r.Nodes -eq $counts2019[$n][0]) -and ($r.Tets -eq $counts2019[$n][1]) }
# A value computed outside a check: on an error, the message (which no check accepts) instead of
# ending the gate before the remaining checks have run.
function Safe([scriptblock]$body) {
    try { & $body } catch { Write-Host "      | error: $($_.Exception.Message)"; "error: $($_.Exception.Message)" }
}
function Format-Exit($code) { if ($code -is [int]) { '0x{0:X8}' -f $code } else { "$code" } }

# The committed tarball, hashed and read (member name -> sha256) once, for (1) and (3).
$tarSha = Safe { Get-Sha $tarball }
$tarMembers = Safe { Read-TetgenTarball $tarball }

# --- (1) What we built is what the manifest says --------------------------------------------------

foreach ($exeName in 'spps.exe', 'classicalTheory.exe', 'tetgen.exe', 'preprocess.exe') {
    $p = Join-Path $bin $exeName
    $code = Safe { Get-CodeSha256 $p }; $link = Safe { Get-LinkNote $p $exeName }
    Check "$exeName exists and its code sha256 $(Short $code) is manifest.json's ($link)" { Test-ManifestHash $p $exeName }
}
$flipped = Safe { Copy-Flipped $new.spps (Join-Path $no 'spps-flipped.exe') }
$flippedCode = Safe { Get-CodeSha256 $flipped }
Check "says NO: spps.exe with one .text byte inverted (code sha256 $(Short $flippedCode)) is not manifest.json's" {
    (Test-Path -LiteralPath $flipped) -and ("$flippedCode" -match '^[0-9a-f]{64}$') -and -not (Test-ManifestHash $flipped 'spps.exe')
}
# The same code linked at another time, as a rebuild gives it: every link-time field set to
# 2000-01-01 00:00:00 UTC.
$restamped = Safe { Copy-PeRestamped $new.spps (Join-Path $no 'spps-restamped.exe') 946684800 }
$restampedRaw = Safe { Get-Sha $restamped }
$sppsRaw = Safe { Get-Sha $new.spps }
Check "spps.exe with its link timestamps set to 2000-01-01 has another sha256 ($(Short $restampedRaw), not $(Short $sppsRaw)) and is still manifest.json's by code sha256" {
    ("$restampedRaw" -match '^[0-9a-f]{64}$') -and ($restampedRaw -ne $sppsRaw) -and (Test-ManifestHash $restamped 'spps.exe')
}

Check "manifest.json records this build: solvers from $($commit.Substring(0,7)); tetgen 1.5.0 with the tarball sha256 and member hashes this run computed, upstream $($blobCommit.Substring(0,7))'s blobs, and the shipped exe's hashes; a code sha256 for each executable" {
    Test-Manifest $manifest
}
$noCode = Safe { $m2 = $manifest | ConvertTo-Json -Depth 6 | ConvertFrom-Json; $m2.code_sha256.PSObject.Properties.Remove('tetgen.exe'); $m2 }
Check "says NO: manifest.json without the code sha256 of tetgen.exe is refused" {
    ($noCode -isnot [string]) -and ($null -eq $noCode.code_sha256.'tetgen.exe') -and -not (Test-Manifest $noCode)
}
$ref16Code = Safe { Get-CodeSha256 $tg16 }
Check "the build tree's upstream TetGen 1.6.0 (code sha256 $(Short $ref16Code)) is manifest.json's 1.6.0 reference, the one the parity bed refuses with" {
    ("$ref16Code" -match '^[0-9a-f]{64}$') -and ($ref16Code -eq $manifest.tetgen.upstream_160_reference_code_sha256)
}
Check "says NO: bin\tetgen.exe is not manifest.json's 1.6.0 reference by code sha256" {
    (Test-Path -LiteralPath $new.tetgen) -and ((Get-CodeSha256 $new.tetgen) -ne $manifest.tetgen.upstream_160_reference_code_sha256)
}
$oldManifest = Safe { $s = (git -C $repo show 'a8a0889:solvers/manifest.json') -join "`n"; $s.Substring($s.IndexOf('{')) | ConvertFrom-Json }
Check "says NO: the manifest of the 1.6.0 build (a8a0889, tetgen $("$($oldManifest.sha256.'tetgen.exe')".PadRight(8).Substring(0,8))) is refused" {
    ($oldManifest -isnot [string]) -and -not (Test-Manifest $oldManifest)
}

# --- (2) spps, classicalTheory and preprocess are the reference build ---------------------------

# Not a check: every reference binary is read by a check below, which fails when it is missing.
$missing = @($ref.Values | Where-Object { -not (Test-Path -LiteralPath $_) })
if ($missing.Count) { Write-Host "      | missing reference binaries (the checks that read them fail): $($missing -join ', ')" }
foreach ($k in 'spps', 'tcr', 'preprocess') {
    $n = Safe { Compare-Pe $new.$k $ref.$k }
    Check "$(Split-Path -Leaf $new.$k) equals the 2026-09-08 reference byte for byte outside the link timestamps ($n differ)" { $n -eq 0 }
}
$n = Safe { Compare-Pe $flipped $ref.spps }
Check "says NO: spps.exe with one .text byte inverted differs from the reference outside the link timestamps ($n byte)" { $n -eq 1 }

# --- (3) TetGen 1.5.0: source ---------------------------------------------------------------------

Check "third_party/tetgen-1.5.0/tetgen1.5.0.tar.gz is WIAS's tarball as downloaded 2026-09-23: sha256 $("$tarSha".PadRight(16).Substring(0,16)) (WIAS $($TetgenTarballSha256.Substring(0,16)))" {
    $tarSha -eq $TetgenTarballSha256
}
$flippedTar = Safe { Copy-FlippedFile $tarball (Join-Path $no 'tetgen1.5.0-flipped.tar.gz') }
Check "says NO: a copy of the tarball with its middle byte inverted is refused" {
    (Test-Path -LiteralPath $flippedTar) -and ((Get-Sha $flippedTar) -ne $TetgenTarballSha256)
}
$memberCount = if ($tarMembers -is [Collections.IDictionary]) { $tarMembers.Count } else { 0 }
$badTar = @(Safe { Get-TarballMismatches $tarMembers $tgSrc })
Check "third_party/tetgen-1.5.0 holds the tarball's $memberCount files byte for byte, read out of the tarball in this run ($($badTar.Count) differ)" {
    ($memberCount -eq 8) -and ($badTar.Count -eq 0)
}
$badCopy = @(Safe {
    $srcCopy = Join-Path $no 'tetgen-src'
    New-Item -ItemType Directory -Force $srcCopy | Out-Null
    Copy-Item (Join-Path $tgSrc '*') $srcCopy
    [IO.File]::AppendAllText((Join-Path $srcCopy 'tetgen.h'), ' ')
    Get-TarballMismatches $tarMembers $srcCopy
})
Check "says NO: a copy of the folder with one space appended to tetgen.h differs from the tarball in tetgen.h alone ($($badCopy -join ', '))" {
    ($badCopy.Count -eq 1) -and ($badCopy[0] -eq 'tetgen.h')
}

$bad = @(Safe { Get-BlobMismatches $tgSrc })
Check "third_party/tetgen-1.5.0 holds upstream $($blobCommit.Substring(0,7))'s src/tetgen blobs: $($blobs4db.Keys -join ', ') ($($bad.Count) differ)" { $bad.Count -eq 0 }
$bad16 = @(Safe { Get-BlobMismatches (Join-Path $up 'src\tetgen') })
Check "says NO: upstream's src/tetgen at $($commit.Substring(0,7)) (TetGen 1.6.0) is refused ($($bad16 -join ', ') differ)" {
    (Test-Path -LiteralPath (Join-Path $up 'src\tetgen\tetgen.cxx')) -and ($bad16 -contains 'tetgen.cxx')
}

# --- (4) TetGen 1.5.0: build ----------------------------------------------------------------------

$refCmds = @(Safe { Get-BuildCommands (Join-Path $bld 'src\tetgen') (Join-Path $usrc 'src\tetgen') })
$cmdDiff = @(Safe { Compare-BuildCommands $refCmds (Get-BuildCommands $tgBld $tgSrc) })
Check "tetgen.exe was compiled and linked with the command lines of upstream's tetgen target ($($refCmds.Count) records, $($cmdDiff.Count) differ)" {
    ($refCmds.Count -eq 3) -and ($refCmds[0] -like 'CL ^*') -and ($cmdDiff.Count -eq 0)
}
# Our records with one compile flag edited, read through the same comparison.
function Get-MutatedDiff([string]$label, [string]$old, [string]$new) {
    $mutTlog = Join-Path $no "tetgen.tlog-$label"
    New-Item -ItemType Directory -Force $mutTlog | Out-Null
    Copy-Item (Join-Path $tgBld 'tetgen.dir\Release\tetgen.tlog\*') $mutTlog
    $clLog = Join-Path $mutTlog 'CL.command.1.tlog'
    $text = [IO.File]::ReadAllText($clLog)
    if (([regex]::Matches($text, [regex]::Escape($old))).Count -ne 2) { throw "'$old' is not in both compile records" }
    [IO.File]::WriteAllText($clLog, $text.Replace($old, $new), [Text.Encoding]::Unicode)
    Compare-BuildCommands $refCmds (Get-BuildCommands $tgBld $tgSrc $mutTlog)
}
function Test-BothCompilesDiffer($d, [string]$flag) {
    ($d.Count -eq 4) -and (@($d | Where-Object { $_.StartsWith('> CL') -and $_.Contains($flag) }).Count -eq 2)
}
$mutDiff = @(Safe { Get-MutatedDiff 'od' ' /O2 ' ' /Od ' })
Check "says NO: the same records with /O2 turned into /Od differ in both compile lines ($($mutDiff.Count) records)" {
    Test-BothCompilesDiffer $mutDiff ' /Od '
}
# cl flags are case-sensitive: /Gr (__fastcall by default) is not /GR (RTTI).
$caseDiff = @(Safe { Get-MutatedDiff 'gr' ' /GR ' ' /Gr ' })
Check "says NO: the same records with /GR turned into /Gr differ in both compile lines, case counts ($($caseDiff.Count) records)" {
    Test-BothCompilesDiffer $caseDiff ' /Gr '
}

# A from-scratch build of the vendored source in this gate run must give bin\tetgen.exe again.
$rb = Join-Path $work 'tetgen-rebuild'
$rbLog = Join-Path $work 'tetgen-rebuild.log'
$rbExe = Join-Path $rb 'Release\tetgen.exe'
$ErrorActionPreference = 'Continue'   # native stderr must not throw under Windows PowerShell 5.1
& cmake -S (Join-Path $repo 'solvers\tetgen') -B $rb -G 'Visual Studio 17 2022' -A x64 -DCMAKE_BUILD_TYPE=Release "-DTETGEN_SOURCE_DIR=$tgSrc" 2>&1 | ForEach-Object { "$_" } | Set-Content $rbLog
$rbConfigure = $LASTEXITCODE
& cmake --build $rb --config Release --parallel --target tetgen 2>&1 | ForEach-Object { "$_" } | Add-Content $rbLog
$rbBuild = $LASTEXITCODE
$ErrorActionPreference = 'Stop'
$n = if (Test-Path $rbExe) { Safe { Compare-Pe $rbExe $new.tetgen } } else { 'no exe' }
Check "a from-scratch build of third_party/tetgen-1.5.0 (configure $rbConfigure, build $rbBuild) gives bin\tetgen.exe byte for byte outside the link timestamps ($n differ)" {
    ($rbConfigure -eq 0) -and ($rbBuild -eq 0) -and ($n -eq 0)
}
# Two from-scratch links of one source: different sha256, one code sha256, the manifest's.
$rbRaw = if (Test-Path $rbExe) { Safe { Get-Sha $rbExe } } else { 'no exe' }
$rbCode = if (Test-Path $rbExe) { Safe { Get-CodeSha256 $rbExe } } else { 'no exe' }
$binRaw = Safe { Get-Sha $new.tetgen }; $binCode = Safe { Get-CodeSha256 $new.tetgen }
Check "the rebuild and bin\tetgen.exe: sha256 $(Short $rbRaw) and $(Short $binRaw) differ, code sha256 $(Short $rbCode) and $(Short $binCode) are equal and manifest.json's" {
    ("$rbRaw" -match '^[0-9a-f]{64}$') -and ($rbRaw -ne $binRaw) -and ($rbCode -eq $binCode) -and (Test-ManifestHash $rbExe 'tetgen.exe')
}
$n16 = Safe { Compare-Pe $tg16 $new.tetgen }
Check "says NO: upstream's 1.6.0 tetgen from the same build is not bin\tetgen.exe (compare gives $n16)" { ($n16 -is [int]) -and ($n16 -ne 0) }
$rbDiff = @(if (Test-Path $rbExe) { Safe { Compare-BuildCommands $refCmds (Get-BuildCommands $rb $tgSrc) } } else { 'no build' })
Check "the from-scratch build used the command lines of upstream's tetgen target ($($rbDiff.Count) differ)" { $rbDiff.Count -eq 0 }
$sppsCmdDiff = @(Safe {
    $sppsTlog = Join-Path $bld 'src\spps\spps.dir\Release\spps.tlog'
    Compare-BuildCommands $refCmds (Get-BuildCommands (Join-Path $bld 'src\spps') (Join-Path $usrc 'src\spps') $sppsTlog)
})
Check "says NO: the command-line comparison refuses the spps target's records read as tetgen's ($($sppsCmdDiff.Count) records differ)" {
    ($sppsCmdDiff.Count -gt 0) -and -not ("$($sppsCmdDiff[0])".StartsWith('error:'))
}

# --- (5) TetGen 1.5.0: behaviour ------------------------------------------------------------------

Check "tetgen.exe -h prints 'Version 1.5' and 'November 4, 2013'" { Test-Banner150 $new.tetgen 'ours' }
Check "says NO: upstream's 1.6.0 tetgen from the same build is refused (it prints 'Version 1.6')" { -not (Test-Banner150 $tg16 'upstream160') }

# The 2019 tutorial meshes, from upstream's tutorial .proj files, read at gate time.
$y2019 = @{}
foreach ($t in 1, 3) { $y2019[$t] = Safe { Get-Tutorial2019 $t } }
$t2019 = $y2019[1]
function Test-SameBytes([string]$a, [string]$b) { (Test-Path -LiteralPath $a) -and (Test-Path -LiteralPath $b) -and ((Get-Sha $a) -eq (Get-Sha $b)) }
Check "tutorial 1: the fixture's .poly and .var are the 2019 project's temp files, byte for byte" {
    (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.poly') (Join-Path $t2019 'scene_mesh.poly')) -and
    (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.var') (Join-Path $t2019 'scene_mesh.var'))
}
$varCrlf = Safe {
    $p = Join-Path $no 'scene_mesh.var'
    Copy-Item (Join-Path $t2019 'scene_mesh.var') $p
    [IO.File]::AppendAllText($p, "`r`n")
    $p
}
Check "says NO: the byte comparison refuses the 2019 .var with a final CRLF added" {
    (Test-Path -LiteralPath $varCrlf) -and -not (Test-SameBytes (Join-Path $fix 'tetgen\scene_mesh.var') $varCrlf)
}

# Each refusal below comes from a TetGen that ran and exited 0: it is refused for its mesh.
function Test-Refused([int]$n, $r) { ($r -isnot [string]) -and ($r.Exit -eq 0) -and (-not (Test-TutCounts $n $r)) -and (-not $r.Identical) }
$t1 = Safe { Invoke-Tut 1 $new.tetgen 'ours' }
Check "tutorial 1, tetgen.exe -pq2 -A -n with the .var: exit $($t1.Exit), $($t1.Nodes) nodes, $($t1.Tets) tets (2019: 732, 2257)" { Test-TutCounts 1 $t1 }
Check "tutorial 1: .1.node/.ele/.face/.neigh/.edge equal the 2019 files byte for byte, trailer line aside ($($t1.Summary))" { $t1.Identical -eq $true }
$n1 = Safe { Invoke-Tut 1 $tg16 'upstream160' }
Check "says NO: upstream's 1.6.0 tetgen from the same build (exit $($n1.Exit)) is refused by both: $($n1.Nodes) nodes, $($n1.Tets) tets; $($n1.Summary)" { Test-Refused 1 $n1 }
$n2 = Safe { Invoke-Tut 1 $ref.tetgen16 'reference160' }
Check "says NO: the pinned 1.6.0 reference tetgen (exit $($n2.Exit)) is refused by both: $($n2.Nodes) nodes, $($n2.Tets) tets" { Test-Refused 1 $n2 }
$n3 = Safe { Invoke-Tut 1 $new.tetgen 'ours-novar' -NoVar }
Check "says NO: tetgen.exe without the .var, no area bound on the floor (exit $($n3.Exit)), is refused by both: $($n3.Nodes) nodes, $($n3.Tets) tets" { Test-Refused 1 $n3 }

# Tutorial 3: another room, no .var, the same TetGen flags.
$t3 = Safe { Invoke-Tut 3 $new.tetgen 'ours' }
Check "tutorial 3, tetgen.exe -pq2 -A -n: exit $($t3.Exit), $($t3.Nodes) nodes, $($t3.Tets) tets (2019: 835, 3285)" { Test-TutCounts 3 $t3 }
Check "tutorial 3: .1.node/.ele/.face/.neigh/.edge equal the 2019 files byte for byte, trailer line aside ($($t3.Summary))" { $t3.Identical -eq $true }
$n4 = Safe { Invoke-Tut 3 $tg16 'upstream160' }
Check "says NO: upstream's 1.6.0 tetgen from the same build (exit $($n4.Exit)) is refused by both on tutorial 3: $($n4.Nodes) nodes, $($n4.Tets) tets; $($n4.Summary)" { Test-Refused 3 $n4 }

# --- (6) SPPS, seeded, new against reference ------------------------------------------------------

# Each says-NO input is a run that happened (an integer exit code): it is refused for what it
# produced, never because it failed to start.
function Ran($code) { $code -is [int] }
$sppsInputs = @('config.xml', 'mesh.cbin', 'tetramesh.mbin', 'expected.json')
function Invoke-Run([string]$exe, [string]$from, [string]$label, $edit) {
    Safe {
        $dir = New-RunFrom $from $label
        if ($edit) { Edit-Once (Join-Path $dir 'config.xml') $edit[0] $edit[1] }
        $code = Invoke-Solver $exe $dir @('config.xml')
        [pscustomobject]@{ Dir = $dir; Exit = $code; Out = (Get-Outputs $dir $sppsInputs); Sizes = (Get-Sizes $dir) }
    }
}
$fixRuns = Join-Path $repo 'tests\fixtures\runs'
$sNew = Invoke-Run $new.spps (Join-Path $fix 'spps') 'spps-new'
$sRef = Invoke-Run $ref.spps (Join-Path $fix 'spps') 'spps-ref'
# says-NO inputs: the committed crash fixture (source outside the cube), and seed 2
$sOut = Invoke-Run $new.spps (Join-Path $fixRuns 'spps_srcout') 'spps-srcout'
$sSeed2 = Invoke-Run $new.spps (Join-Path $fix 'spps') 'spps-seed2' @('random_seed="1"', 'random_seed="2"')
$tNew = Invoke-Run $new.tcr (Join-Path $fix 'tcr') 'tcr-new'
$tRef = Invoke-Run $ref.tcr (Join-Path $fix 'tcr') 'tcr-ref'
# says-NO inputs: the committed no-mesh fixture, and the tutorial with its source moved 0.5 m
$tNoMesh = Invoke-Run $new.tcr (Join-Path $fixRuns 'tcr_nomesh') 'tcr-nomesh'
$tMoved = Invoke-Run $new.tcr (Join-Path $fix 'tcr') 'tcr-source-moved' @('name="Source 1" x="3"', 'name="Source 1" x="3.5"')

function Test-SppsBanner($r) { (Get-Content (Join-Path $r.Dir '_stdout.txt') -TotalCount 1) -match '^SPPS version 2\.2\.1' }
function Test-End($r) { Select-String -Path (Join-Path $r.Dir '_stdout.txt') -Pattern '^End of calculation' -Quiet }
function Test-Produced($a, $b) { ($a.Out.Count -gt 0) -and ($b.Out.Count -eq $a.Out.Count) }
function Get-StatDiff($diff) { @($diff | Where-Object { $_ -like '*.recp' -or $_ -like '*particle statistics.gabe' }) }
function Get-NonCsbin($diff) { @($diff | Where-Object { $_ -notlike '*.csbin' }) }
function Test-SameSizes($a, $b) { @(Compare-Outputs $a.Sizes $b.Sizes).Count -eq 0 }

Check "SPPS banner is version 2.2.1" { Test-SppsBanner $sNew }
Check "says NO: the banner check refuses TCR's first stdout line" { (Ran $tNew.Exit) -and -not (Test-SppsBanner $tNew) }
Check "SPPS exits 0 on both (new $($sNew.Exit), reference $($sRef.Exit))" { $sNew.Exit -eq 0 -and $sRef.Exit -eq 0 }
Check "says NO: SPPS on tests/fixtures/runs/spps_srcout exits $(Format-Exit $sOut.Exit), and the exit check refuses it" { (Ran $sOut.Exit) -and -not ($sOut.Exit -eq 0) }
Check "SPPS reaches 'End of calculation' on both" { (Test-End $sNew) -and (Test-End $sRef) }
Check "says NO: the spps_srcout run never reaches it" { (Ran $sOut.Exit) -and -not (Test-End $sOut) }
Check "SPPS produced output on both (new $($sNew.Out.Count), reference $($sRef.Out.Count) files)" { Test-Produced $sNew $sRef }
Check "says NO: the spps_srcout run is refused ($($sOut.Out.Count) output files)" { (Ran $sOut.Exit) -and -not (Test-Produced $sOut $sRef) }
$diff = @(Compare-Outputs $sNew.Out $sRef.Out)
$diff2 = @(Compare-Outputs $sSeed2.Out $sRef.Out)
# The seed-2 run must be a complete run (exit 0, the reference's file set) refused for its values.
$seed2Whole = ($sSeed2.Exit -eq 0) -and ($sSeed2.Out.Count -eq $sRef.Out.Count) -and ($sSeed2.Out.Count -gt 0)
Check "SPPS stats GABE and every .recp byte-identical" { (Get-StatDiff $diff).Count -eq 0 }
Check "says NO: the seed-2 run (exit $($sSeed2.Exit), $($sSeed2.Out.Count) files) differs from the reference in them ($((Get-StatDiff $diff2).Count) files)" { $seed2Whole -and (Get-StatDiff $diff2).Count -gt 0 }
Check "SPPS every non-.csbin output byte-identical ($((Get-NonCsbin $diff).Count) differ)" { (Get-NonCsbin $diff).Count -eq 0 }
Check "says NO: the seed-2 run is refused ($((Get-NonCsbin $diff2).Count) differ)" { $seed2Whole -and (Get-NonCsbin $diff2).Count -gt 0 }
Check "SPPS .csbin: same files at the same sizes ($($sNew.Sizes.Count) files)" { ($sNew.Sizes.Count -gt 0) -and (Test-SameSizes $sNew $sRef) }
Check "says NO: the spps_srcout run's .csbin set is refused ($($sOut.Sizes.Count) files)" { (Ran $sOut.Exit) -and -not (Test-SameSizes $sOut $sRef) }

# --- (7) TCR, deterministic, new against reference ------------------------------------------------

Check "TCR exits 0 on both (new $($tNew.Exit), reference $($tRef.Exit))" { $tNew.Exit -eq 0 -and $tRef.Exit -eq 0 }
Check "says NO: TCR on tests/fixtures/runs/tcr_nomesh exits $(Format-Exit $tNoMesh.Exit), and the exit check refuses it" { (Ran $tNoMesh.Exit) -and -not ($tNoMesh.Exit -eq 0) }
Check "TCR produced output on both (new $($tNew.Out.Count), reference $($tRef.Out.Count) files)" { Test-Produced $tNew $tRef }
Check "says NO: the tcr_nomesh run is refused ($($tNoMesh.Out.Count) output files)" { (Ran $tNoMesh.Exit) -and -not (Test-Produced $tNoMesh $tRef) }
$diff = @(Compare-Outputs $tNew.Out $tRef.Out)
$diffMoved = @(Compare-Outputs $tMoved.Out $tRef.Out)
$movedWhole = ($tMoved.Exit -eq 0) -and ($tMoved.Out.Count -eq $tRef.Out.Count) -and ($tMoved.Out.Count -gt 0)
Check "TCR every non-.csbin output byte-identical ($((Get-NonCsbin $diff).Count) differ)" { (Get-NonCsbin $diff).Count -eq 0 }
Check "says NO: the run with the source moved 0.5 m (exit $($tMoved.Exit), $($tMoved.Out.Count) files) is refused ($((Get-NonCsbin $diffMoved).Count) differ)" { $movedWhole -and (Get-NonCsbin $diffMoved).Count -gt 0 }
Check "TCR .csbin: same files at the same sizes ($($tNew.Sizes.Count) files)" { ($tNew.Sizes.Count -gt 0) -and (Test-SameSizes $tNew $tRef) }
Check "says NO: the tcr_nomesh run's .csbin set is refused ($($tNoMesh.Sizes.Count) files)" { (Ran $tNoMesh.Exit) -and -not (Test-SameSizes $tNoMesh $tRef) }

# --- (8) The upstream checkout was not touched ----------------------------------------------------

function Test-Clean($lines) { @($lines | Where-Object { $_ }).Count -eq 0 }
$trackedAfter = @(Get-TrackedChanges $up)
Check "upstream tracked files untouched (before $($trackedBefore.Count), after $($trackedAfter.Count) changed)" { (Test-Clean $trackedBefore) -and (Test-Clean $trackedAfter) }
# A real checkout with a tracked change: a new repository with one file staged, read by the same
# git call.
$staged = @(Safe {
    $g = Join-Path $no 'git-staged'
    New-Item -ItemType Directory -Force $g | Out-Null
    $ErrorActionPreference = 'Continue'
    & git -C $g init -q 2>&1 | Out-Null
    [IO.File]::WriteAllText((Join-Path $g 'main.cpp'), "int main() { return 0; }`n")
    & git -C $g -c core.autocrlf=false add main.cpp 2>&1 | Out-Null
    Get-TrackedChanges $g
})
Check "says NO: the cleanliness check refuses a checkout with one file staged (git says '$($staged -join '; ')')" {
    -not (Test-Clean $staged) -and (@($staged | Where-Object { $_ -match '^A  main\.cpp$' }).Count -eq 1)
}
$upHead = Get-Head $up
Check "upstream HEAD still $($commit.Substring(0,7))" { $upHead -eq $commit }
# The refusal of a pinned-hash equality is a real checkout at another commit; this repo is one.
$ownHead = Get-Head $repo
Check "says NO: the HEAD check refuses this repo's checkout, at $("$ownHead".Substring(0,7))" { ($ownHead -match '^[0-9a-f]{40}$') -and -not ($ownHead -eq $commit) }

# Nothing is deleted: each run keeps its folder, and this says what the kept runs hold.
function Get-Mb([string]$dir) { [math]::Round((Get-ChildItem -LiteralPath $dir -Recurse -File -Force | Measure-Object Length -Sum).Sum / 1MB, 1) }
$runsDir = Split-Path -Parent $work
$kept = @(Get-ChildItem -LiteralPath $runsDir -Directory)
Write-Host "`nrun folders: $work ($(Get-Mb $work) MB)"
Write-Host "kept gate runs: $($kept.Count) folders in $runsDir, $(Get-Mb $runsDir) MB; the gate deletes none of them"
Write-Host "$script:checks checks, $($failures.Count) failed"
if ($failures.Count) { Write-Host "M1 FAILED: $($failures.Count) check(s)"; exit 1 }
Write-Host "M1 PASSED"; exit 0
