// Generates the ACL for the app's own commands: with an app manifest, each command is denied
// unless a capability grants its `allow-<command>` permission (capabilities/default.json).
fn main() {
    let commands = &[
        "ping",
        "panic_probe",
        "panic_probe_unguarded",
        "unguarded_panic_runs",
        "bench_prepare",
        "bench_take",
        "bench_clear",
        "run_events_probe",
        "exact_float_probe",
        "project_new",
        "project_load_text",
        "project_open",
        "project_info",
        "project_json",
        "project_apply",
        "project_undo",
        "project_redo",
        "app_startup",
        "selftest_report",
        "scene_state",
        "scene_new",
        "scene_new_box",
        "scene_open",
        "example_open",
        "model_import",
        "model_repair",
        "model_reimport",
        "project_save",
        "edit_apply",
        "advice_apply",
        "edit_reband",
        "edit_regroup",
        "edit_add_group",
        "edit_undo",
        "edit_redo",
        "scene_mesh",
        "mesh_now",
        "run_start",
        "run_cancel",
        "runs_list",
        "run_label",
        "run_open_folder",
        "run_delete",
        "run_results",
        "run_report",
        "run_data",
        "run_surface_map",
        "run_particles",
        "run_echogram",
        "run_auralize",
        "proj_import",
        "material_library",
        "spectrum_library",
        "solvers_status",
        "spps_gpu_status",
        "app_events",
        "app_quit",
        "export_write",
    ];
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(commands));
    tauri_build::try_build(attributes).expect("tauri-build failed");
}
