//! The parity bed (`docs/m5-m6-design.md`, decision 3): our build against original I-Simpa on
//! upstream's three tutorials, from the `.proj` to the solvers' results.
//!
//! For each tutorial, through the built `simpa` as a user drives it:
//! 1. **Import** the `.proj` with `simpa import-proj`.
//! 2. **Mesh** it with `simpa mesh` (TetGen 1.5.0, the M1 build found through `common/paths.rs`:
//!    `$SIMPA_SOLVERS_DIR`, else the dev tree; a missing build panics, nothing skips).
//! 3. **Compare our inputs with the files original I-Simpa wrote** into the `.proj`: `.poly` and
//!    `.var` byte for byte; TetGen's `.1.{node,ele,face,neigh,edge}` byte for byte, the trailer
//!    (`# Generated by ...`, which names the program and folder) excluded (for tutorial 2, the
//!    `.poly` and `.node` lines printed at decimal ties are counted and pinned, their values
//!    equal: [`TUTORIAL2_TIES`]); the `.mbin` byte for byte, `idVolume` included (both sides write
//!    TetGen's region attribute unchanged, decision 1, and the import pins upstream's element ids,
//!    decision 13, so a fitting's seed carries upstream's id on both sides and no id is mapped);
//!    `mesh.cbin` and `config.xml` as `crates/simpa-core/tests/parity_inputs.rs` defines equality
//!    (what the solver reads, value by value, ids included, with the listed differences by
//!    design), the helpers shared through `parity_support.rs`.
//! 4. **Run SPPS and TCR** (our M1 builds of upstream's 929a5c8 sources) on our inputs and on the
//!    original inputs, both edited alike: `random_seed` 1, 10,000 particles, and at most three
//!    computed bands (500, 1000 and 2000 Hz where a run computes more). Every output file must be
//!    the same: `.csbin` compared decoded (its struct padding is not deterministic, M1), the
//!    surface receivers' `xmlIndex` upstream's on both sides, every other file byte for byte, which
//!    makes `.gabe` and `.recp` values bit-exact. A difference names the file and its first
//!    differing value, from the canonical dump. The one difference allowed is named with its
//!    cause and proven: tutorial 1's two `Advanced sound level.gap`, from the receiver directions
//!    a `.proj` stores with 6 digits, which match once our config carries the run's own. It is
//!    not a difference from what original I-Simpa writes from this `.proj`: its GUI saves a
//!    direction with `ostream`'s default 6 digits (`e_data_float.h:163, 249-257`), reads that
//!    text back on load (`:65-66`), and recomputes a direction only when a position is edited, never
//!    on load (`e_scene_recepteursp_recepteur.h:63, 105, 195-219`); the runs were written in the
//!    2019 session, before the save ([`directions_of`]).
//!
//! What each tutorial holds decides what can be compared (`parity_inputs.rs::what_the_tutorials_hold`):
//! - **tutorial 1**: TetGen's files under `temp/` and two run folders (SPPS, TCR): everything;
//! - **tutorial 2**: TetGen's files under `temp/` (no `.var`: its project constrains no surface) and
//!   no run folder: the mesher's inputs and outputs only. There is no original `.mbin`, `.cbin`,
//!   `config.xml` or result to compare with. Its settings ask for `preprocess.exe`, which gives
//!   up on the hall and saves nothing; the mesher then meshes the `.poly` it wrote, as upstream's
//!   GUI does, records the abort in `mesh.json`, and our geometry check gates that `.poly`; the
//!   files are compared as the `.proj` meshes them;
//! - **tutorial 3**: TetGen's files under `temp/` and three SPPS run folders, end to end.
//!   `simpa import-proj` reads it, fitting zones, per-band laws and transmission, source groups
//!   and the mesh settings' "preprocess" included, and records upstream's element ids beside the
//!   entities they became; `simpa mesh --parity` takes it through our `.poly`, `preprocess.exe`,
//!   our geometry check, TetGen 1.5.0 and our builder (`docs/m5-m6-design.md`, decision 12); the
//!   `.poly` `preprocess.exe` saves, TetGen's `.1.*` and the `.mbin` are compared with upstream's,
//!   each run's `config.xml` and `mesh.cbin` with ours from the `.proj` read with that run's saved
//!   project, all byte for byte or value for value with no id map (the import pins upstream's
//!   element ids, Burhan's decision of 2026-09-24 14:11, `docs/m5-m6-design.md`, decision 13),
//!   and the runs on our own mesh ([`tutorial_3_same_seed_runs`]).
//!
//! Every comparison has a refusal beside it, the input that makes it say no
//! (`the_comparisons_say_no`).

mod support;

// simpa-core's parity helpers, which bring their own copy of `common/paths.rs` (the CLI's `support`
// has one too): the same finder twice, by design.
#[allow(clippy::duplicate_mod)]
#[path = "../../simpa-core/tests/parity_support.rs"]
mod parity;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};

use parity::{Tutorial, edit_attr, entry, has_entry, tutorial};
use serde_json::Value;
use simpa_core::config_xml::{SolverIds, SolverKind};
use simpa_core::formats::{cbin, csbin, gabe, mbin};
use simpa_core::geometry::import::{ProjReport, UpstreamKind};
use simpa_core::schema::{FittingZoneId, PointReceiverId, Project, SurfaceReceiverId};
use support::{json, simpa_run, solver_exe};

// ---------------------------------------------------------------------------------------------
// Folders and CLI calls

/// A new folder under `<repo>/target/parity-bed/`, short enough that the deepest solver output
/// stays well under Windows' 260-character path limit (a longer path is skipped by the solvers
/// with exit 0 and no message, `config_xml_solver.rs`). Never reused, never deleted.
fn bed_dir(label: &str) -> PathBuf {
    static N: AtomicUsize = AtomicUsize::new(0);
    let dir = support::paths::repo_root()
        .join("target/parity-bed")
        .join(format!(
            "{}-{}-{label}",
            std::process::id(),
            N.fetch_add(1, Ordering::SeqCst)
        ));
    std::fs::create_dir_all(&dir).unwrap();
    let deepest = dir.as_os_str().len()
        + "/Punctual receivers/Receiver 1/Punctual receiver intensity.gabe".len();
    assert!(deepest < 240, "{} is too deep for MAX_PATH", dir.display());
    dir
}

/// `simpa import-proj <tutorial> <dir>/project.simpa`: must exit 0.
fn import_proj(rel: &str, dir: &Path) -> PathBuf {
    let proj = support::paths::upstream_file(rel);
    let out = dir.join("project.simpa");
    let o = simpa_run(&[
        "import-proj".to_string(),
        proj.display().to_string(),
        out.display().to_string(),
    ]);
    assert_eq!(o.code, 0, "import-proj {rel}: {o:#?}");
    out
}

/// `simpa mesh <project> --out <dir> --json`: must exit 0 with status OK.
fn mesh(project: &Path, out: &Path) -> Value {
    let o = simpa_run(&[
        "mesh".to_string(),
        project.display().to_string(),
        "--out".into(),
        out.display().to_string(),
        "--json".into(),
    ]);
    assert_eq!(o.code, 0, "simpa mesh {}: {o:#?}", project.display());
    let m = json(&o);
    assert_eq!(m["status"], "OK", "{m:#}");
    m
}

/// `simpa export-config <project> <dir> --solver <kind>`: our `config.xml` and `mesh.cbin`.
fn export_config(project: &Path, dir: &Path, kind: SolverKind) -> (String, Vec<u8>) {
    let o = simpa_run(&[
        "export-config".to_string(),
        project.display().to_string(),
        dir.display().to_string(),
        "--solver".into(),
        solver_name(kind).into(),
    ]);
    assert_eq!(o.code, 0, "export-config: {o:#?}");
    (
        std::fs::read_to_string(dir.join("config.xml")).unwrap(),
        std::fs::read(dir.join("mesh.cbin")).unwrap(),
    )
}

fn solver_name(kind: SolverKind) -> &'static str {
    match kind {
        SolverKind::Spps => "spps",
        SolverKind::Tcr => "tcr",
    }
}

// ---------------------------------------------------------------------------------------------
// The comparisons

/// The first difference between two files' bytes: `None` when they are equal.
fn byte_difference(ours: &[u8], theirs: &[u8]) -> Option<String> {
    if ours == theirs {
        return None;
    }
    let at = ours
        .iter()
        .zip(theirs)
        .position(|(a, b)| a != b)
        .unwrap_or(ours.len().min(theirs.len()));
    Some(format!(
        "{} bytes against the original's {}; first difference at byte {at}: ours {:?}, the \
         original's {:?}",
        ours.len(),
        theirs.len(),
        ours.get(at),
        theirs.get(at)
    ))
}

/// TetGen's `.1.*` files compared line by line, the trailer (`# Generated by ...`) excluded.
#[derive(Debug, Default)]
struct TetgenDiff {
    /// Lines whose text differs.
    text_lines: usize,
    /// Of those, lines whose values differ: a token that is not the same number (as `f64`) or not
    /// the same word, or a line one file lacks.
    value_lines: usize,
    /// The first line whose values differ.
    first_value: Option<String>,
    /// The first line whose text differs.
    first_text: Option<String>,
}

fn is_trailer(line: &str) -> bool {
    line.starts_with("# Generated by ")
}

fn tetgen_difference(ours: &[u8], theirs: &[u8]) -> TetgenDiff {
    let lines = |b: &[u8]| -> Vec<String> {
        String::from_utf8_lossy(b)
            .lines()
            .filter(|l| !is_trailer(l))
            .map(str::to_string)
            .collect()
    };
    let (o, t) = (lines(ours), lines(theirs));
    let mut d = TetgenDiff::default();
    let same_values = |a: &str, b: &str| {
        let (x, y): (Vec<&str>, Vec<&str>) = (
            a.split_whitespace().collect(),
            b.split_whitespace().collect(),
        );
        x.len() == y.len()
            && x.iter().zip(&y).all(|(p, q)| {
                p == q
                    || matches!((p.parse::<f64>(), q.parse::<f64>()), (Ok(u), Ok(v)) if u.to_bits() == v.to_bits())
            })
    };
    for k in 0..o.len().max(t.len()) {
        let (a, b) = (o.get(k), t.get(k));
        if a == b {
            continue;
        }
        d.text_lines += 1;
        let line = format!(
            "line {}: ours {:?}, the original's {:?}",
            k + 1,
            a.map(String::as_str).unwrap_or("(none)"),
            b.map(String::as_str).unwrap_or("(none)")
        );
        if d.first_text.is_none() {
            d.first_text = Some(line.clone());
        }
        let equal = matches!((a, b), (Some(a), Some(b)) if same_values(a, b));
        if !equal {
            d.value_lines += 1;
            if d.first_value.is_none() {
                d.first_value = Some(line);
            }
        }
    }
    d
}

/// Our `.mbin` against the original's, byte for byte, once each of the original's tetrahedra has
/// its `idVolume` read through `ids` (the original's id to ours; an id missing from the map is
/// left as it is, so it shows). The original is decoded and written again by our writer, which
/// must give back its exact bytes first.
fn mbin_difference(ours: &[u8], theirs: &[u8], ids: &BTreeMap<i32, i32>) -> Option<String> {
    let mut t = match mbin::read(theirs) {
        Ok(m) => m,
        Err(e) => return Some(format!("the original does not read: {e}")),
    };
    if mbin::write(&t) != theirs {
        return Some("the original does not survive a read and a write".to_string());
    }
    for tet in &mut t.tetrahedra {
        if let Some(&o) = ids.get(&tet.id_volume) {
            tet.id_volume = o;
        }
    }
    let mapped = mbin::write(&t);
    if mapped == ours {
        return None;
    }
    // Name the first differing value from the canonical dumps.
    let dump_ours = match mbin::read(ours) {
        Ok(m) => mbin::dump(&m),
        Err(e) => return Some(format!("ours does not read: {e}")),
    };
    Some(
        first_dump_difference(&dump_ours, &mbin::dump(&t))
            .unwrap_or_else(|| byte_difference(ours, &mapped).unwrap_or_default()),
    )
}

/// The first line where two canonical dumps differ.
fn first_dump_difference(ours: &str, theirs: &str) -> Option<String> {
    let (o, t): (Vec<&str>, Vec<&str>) = (ours.lines().collect(), theirs.lines().collect());
    (0..o.len().max(t.len())).find_map(|k| {
        let (a, b) = (o.get(k), t.get(k));
        (a != b).then(|| {
            format!(
                "dump line {}: ours `{}`, the original's `{}`",
                k + 1,
                a.unwrap_or(&"(none)"),
                b.unwrap_or(&"(none)")
            )
        })
    })
}

/// The output files of one run, by path relative to its folder.
type Outputs = BTreeMap<String, Vec<u8>>;

/// Every difference between the original's run and ours, one line per file: a file only one run
/// wrote, or the first value that differs. A `.csbin` is compared decoded, the original's
/// receivers' `xmlIndex` read through `rs_ids`; every other file byte for byte, its first
/// differing value named from the GABE dump when it reads as one.
fn output_differences(
    theirs: &Outputs,
    ours: &Outputs,
    rs_ids: &BTreeMap<i32, i32>,
) -> Vec<String> {
    let mut out = Vec::new();
    for k in theirs.keys().filter(|k| !ours.contains_key(*k)) {
        out.push(format!("{k}: only the original's run wrote it"));
    }
    for k in ours.keys().filter(|k| !theirs.contains_key(*k)) {
        out.push(format!("{k}: only our run wrote it"));
    }
    for (k, t) in theirs {
        let Some(o) = ours.get(k) else { continue };
        let found = if k.ends_with(".csbin") {
            match (csbin::read(t), csbin::read(o)) {
                (Ok(t), Ok(o)) => csbin_difference(t, &o, rs_ids),
                (t, o) => Some(format!(
                    "does not decode: original {:?}, ours {:?}",
                    t.err(),
                    o.err()
                )),
            }
        } else if t == o {
            None
        } else {
            match (gabe::read(t), gabe::read(o)) {
                (Ok(t), Ok(o)) => first_dump_difference(&gabe::dump(&o), &gabe::dump(&t)),
                _ => byte_difference(o, t),
            }
            .or_else(|| byte_difference(o, t))
        };
        if let Some(d) = found {
            out.push(format!("{k}: {d}"));
        }
    }
    out.sort();
    out
}

/// Two decoded `.csbin`, the original's receivers' `xmlIndex` read through `rs_ids` first: the
/// first line where their canonical dumps differ (every value in hexadecimal, so bit for bit).
fn csbin_difference(
    mut theirs: csbin::Csbin,
    ours: &csbin::Csbin,
    rs_ids: &BTreeMap<i32, i32>,
) -> Option<String> {
    for r in &mut theirs.receivers {
        r.xml_index = *rs_ids.get(&r.xml_index).unwrap_or(&r.xml_index);
    }
    first_dump_difference(&csbin::dump(ours), &csbin::dump(&theirs))
}

// ---------------------------------------------------------------------------------------------
// Runs

/// The same edits on the original's `config.xml` and ours: `parity::repeatable` (SPPS: seed 1,
/// 10,000 particles) and at most three computed bands, 500, 1000 and 2000 Hz, when the config
/// computes more.
fn short_run(config: &str, kind: SolverKind) -> String {
    let text = parity::repeatable(config, kind);
    let doc = roxmltree::Document::parse(&text).unwrap();
    let computed: Vec<String> = doc
        .descendants()
        .filter(|n| {
            n.has_tag_name("bfreq") && n.parent().is_some_and(|p| p.has_tag_name("freq_enum"))
        })
        .filter(|n| n.attribute("docalc") == Some("1"))
        .map(|n| n.attribute("freq").unwrap().to_string())
        .collect();
    drop(doc);
    if computed.len() <= 3 {
        return text;
    }
    let keep = ["500", "1000", "2000"];
    assert!(
        keep.iter().all(|f| computed.iter().any(|c| c == f)),
        "{computed:?}"
    );
    let mut out = text;
    for f in computed.iter().filter(|f| !keep.contains(&f.as_str())) {
        let from = format!("<bfreq freq=\"{f}\" docalc=\"1\"/>");
        let to = format!("<bfreq freq=\"{f}\" docalc=\"0\"/>");
        assert_eq!(out.matches(&from).count(), 1, "{from}");
        out = out.replace(&from, &to);
    }
    out
}

/// Runs `kind` (our M1 build) in the new folder `dir` on `config` (its working directory set to
/// that folder), the scene mesh `cbin` and the tetrahedral mesh `mbin`. It must exit 0 and print
/// its completion line. Returns its output files.
fn run(dir: &Path, kind: SolverKind, config: &str, cbin: &[u8], mbin: &[u8]) -> Outputs {
    std::fs::create_dir_all(dir).unwrap();
    let wd = simpa_core::config_xml::working_directory(dir).unwrap();
    let text = edit_attr(config, "<configuration ", "workingdirectory", &wd);
    std::fs::write(dir.join("config.xml"), text).unwrap();
    std::fs::write(dir.join("mesh.cbin"), cbin).unwrap();
    std::fs::write(dir.join("tetramesh.mbin"), mbin).unwrap();
    let exe = solver_exe(match kind {
        SolverKind::Spps => "spps.exe",
        SolverKind::Tcr => "classicalTheory.exe",
    });
    let r = parity::support::run_solver(&exe, dir);
    assert_eq!(r.exit, Some(0), "{}: {}", dir.display(), r.stderr);
    let done = match kind {
        SolverKind::Spps => "End of calculation.",
        SolverKind::Tcr => "Step 3/3",
    };
    assert!(r.has_line(done), "{}:\n{}", dir.display(), r.stdout);
    parity::support::outputs(dir, &["config.xml", "mesh.cbin", "tetramesh.mbin"])
}

/// The original's run and ours on the same edits: the output differences, and how many files each
/// wrote. Their `.csbin` receiver ids are read through `rs_ids`.
#[allow(clippy::too_many_arguments)]
fn same_seed(
    label: &str,
    kind: SolverKind,
    original: (&str, &[u8], &[u8]),
    ours: (&str, &[u8], &[u8]),
    rs_ids: &BTreeMap<i32, i32>,
) -> (Outputs, Vec<String>) {
    let root = bed_dir(label);
    let theirs = run(
        &root.join("original"),
        kind,
        &short_run(original.0, kind),
        original.1,
        original.2,
    );
    let mine = run(
        &root.join("ours"),
        kind,
        &short_run(ours.0, kind),
        ours.1,
        ours.2,
    );
    assert!(
        !theirs.is_empty(),
        "{label}: the original's run wrote nothing"
    );
    let d = output_differences(&theirs, &mine, rs_ids);
    println!(
        "{label}: {} output files from the original's inputs, {} from ours; {} differ{}",
        theirs.len(),
        mine.len(),
        d.len(),
        if d.is_empty() {
            String::new()
        } else {
            format!(":\n  {}", d.join("\n  "))
        }
    );
    (theirs, d)
}

// ---------------------------------------------------------------------------------------------
// The mesher's files

/// The TetGen output files a mesh folder holds.
const TETGEN_FILES: [&str; 5] = ["node", "ele", "face", "neigh", "edge"];

/// Lines of a tutorial's files that differ from ours in text only: a coordinate at an exact decimal
/// tie in the 17th significant digit, printed rounded to even by ours and up by the 2019 build
/// (see [`TUTORIAL2_TIES`]). `(.poly lines, .1.node lines)`.
type Ties = (usize, usize);

/// Our `name` against the original's, line by line: no line may differ in value, and exactly
/// `text_only` lines may differ in text. One line for the summary; panics otherwise, naming the
/// first line that differs.
fn compare_text(name: &str, ours: &[u8], theirs: &[u8], text_only: usize, label: &str) -> String {
    let d = tetgen_difference(ours, theirs);
    assert_eq!(d.value_lines, 0, "{label}: {name}: {:?}", d.first_value);
    assert_eq!(
        d.text_lines, text_only,
        "{label}: {name}: {} lines differ in text, {text_only} expected; first {:?}",
        d.text_lines, d.first_text
    );
    if d.text_lines == 0 {
        format!("{name}: byte-identical, trailer excluded")
    } else {
        format!(
            "{name}: {} lines differ in text only, every value equal as f64 (first {})",
            d.text_lines,
            d.first_text.unwrap()
        )
    }
}

/// Our mesh folder's `.poly`, `.var` and `.1.*` against a tutorial's `temp/`, with the lines
/// expected to differ in text only. Returns one line per file, for the summary; panics on any
/// other difference, naming it.
fn compare_mesher_files(t: &Tutorial, mesh_dir: &Path, ties: Ties, label: &str) -> Vec<String> {
    let mut report = Vec::new();
    let ours = |name: &str| {
        std::fs::read(mesh_dir.join(name)).unwrap_or_else(|e| panic!("{label}: {name}: {e}"))
    };
    // The .poly, which has no trailer: byte for byte but the ties.
    report.push(compare_text(
        "scene_mesh.poly",
        &ours("scene_mesh.poly"),
        &entry(t, "temp/scene_mesh.poly"),
        ties.0,
        label,
    ));
    if ties.0 == 0 {
        assert_eq!(
            byte_difference(&ours("scene_mesh.poly"), &entry(t, "temp/scene_mesh.poly")),
            None,
            "{label}: scene_mesh.poly"
        );
    }
    // The .var, byte for byte, or absent on both sides.
    let var_theirs = has_entry(t, "temp/scene_mesh.var");
    let var_ours = mesh_dir.join("scene_mesh.var").is_file();
    assert_eq!(var_ours, var_theirs, "{label}: a .var on one side only");
    if var_theirs {
        let var = byte_difference(&ours("scene_mesh.var"), &entry(t, "temp/scene_mesh.var"));
        assert_eq!(var, None, "{label}: scene_mesh.var");
        report.push("scene_mesh.var: byte-identical".to_string());
    } else {
        report.push("scene_mesh.var: none written, as the original wrote none".to_string());
    }
    // TetGen's output, trailer excluded.
    for ext in TETGEN_FILES {
        let name = format!("scene_mesh.1.{ext}");
        let text_only = if ext == "node" { ties.1 } else { 0 };
        report.push(compare_text(
            &name,
            &ours(&name),
            &entry(t, &format!("temp/{name}")),
            text_only,
            label,
        ));
    }
    report
}

fn print_report(label: &str, report: &[String]) {
    println!("{label}:");
    for r in report {
        println!("  {r}");
    }
}

// ---------------------------------------------------------------------------------------------
// Tutorial 1

/// Tutorial 1 (the 6 x 10 x 3 m box, one source, two point receivers, the floor a surface receiver
/// constrained to 0.1 m²): every input equal to original I-Simpa's, and every result of a same-seed
/// SPPS run and TCR run on our inputs equal to those on the original's.
#[test]
fn tutorial_1() {
    let t = tutorial(parity::TUTORIAL1);
    let dir = bed_dir("t1");
    let project = import_proj(parity::TUTORIAL1, &dir);
    let mesh_dir = dir.join("mesh");
    let m = mesh(&project, &mesh_dir);
    assert_eq!(
        m["tetgen"]["argv"],
        serde_json::json!(["-pq2", "-A", "-n", "scene_mesh.poly"]),
        "the original's flags, from the .proj's SPPS meshing settings"
    );
    // Its mesh settings ask for upstream's scene correction, as the original's did: on the box it
    // changes nothing, and the .poly TetGen reads is the one written, byte for byte.
    let pre = &m["preprocess"];
    assert_eq!(pre["input_sha256"], pre["output_sha256"], "{pre:#}");
    assert_eq!(pre["accounting"]["deleted"], serde_json::json!([]));
    assert_eq!(pre["accounting"]["split"], serde_json::json!([]));
    assert_eq!(pre["accounting"]["marker_changes"], serde_json::json!([]));
    let mut report = vec![format!(
        "preprocess.exe, which the .proj's mesh settings ask for: {}; the .poly it saved is the \
         one it was given, byte for byte",
        pre["summary"].as_str().unwrap()
    )];
    report.extend(compare_mesher_files(&t, &mesh_dir, (0, 0), "tutorial 1"));
    let our_mbin = std::fs::read(mesh_dir.join("tetramesh.mbin")).unwrap();

    assert_eq!(t.runs.len(), 2);
    for r in &t.runs {
        let kind = r.solver;
        let name = solver_name(kind);
        // The .proj as a user opens it: its elements pinned to the ids of the session that last
        // saved it (decision 13), not the 2019 session's the runs carry: upstream renumbers every
        // element on load. The ids are its only difference but the by-design ones.
        let (cli_config, _) =
            export_config(&project, &dir.join(format!("export-cli-{name}")), kind);
        let mut expected_cli = parity::by_design(kind);
        expected_cli.extend(parity::tutorial1_proj_ids());
        expected_cli.extend(parity::tutorial1_directions());
        expected_cli.push(format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&r.config),
            parity::working_folder(&cli_config)
        ));
        assert_eq!(
            parity::solver_differences(&r.config, &cli_config),
            parity::sorted(expected_cli),
            "{name}: the .proj's own ids"
        );
        // The run's own project: the .proj read with the snapshot upstream saved beside the run,
        // its elements pinned to that session's ids, saved as a project and exported by the CLI.
        let run_project = dir.join(format!("run-{name}.simpa"));
        let imported = simpa_core::geometry::import::import_proj_with_config(
            &t.bytes,
            r.project_file.as_bytes(),
        )
        .unwrap();
        simpa_core::schema::save(&imported.project, &run_project).unwrap();
        let (our_config, our_cbin) =
            export_config(&run_project, &dir.join(format!("export-{name}")), kind);
        // Upstream's ids, with no map: every element's id the run's own.
        for tag in ["recepteur_ponctuel", "recepteur_surfacique", "encombrement"] {
            let map = parity::id_map(&r.config, &our_config, tag);
            assert!(map.iter().all(|(a, b)| a == b), "{name}: {tag} ids {map:?}");
        }

        // The .mbin, byte for byte: no fitting; the room is TetGen's 1 on both sides.
        assert_eq!(
            byte_difference(&our_mbin, &r.tetra_bytes),
            None,
            "{name}: tetramesh.mbin"
        );
        report.push(format!(
            "{name} tetramesh.mbin: byte-identical, idVolume included ({} bytes)",
            our_mbin.len()
        ));

        // config.xml and mesh.cbin as parity_inputs.rs defines them; our working directory is our
        // export folder.
        let got = parity::solver_differences(&r.config, &our_config);
        let mut expected = parity::by_design(kind);
        expected.extend(parity::tutorial1_directions());
        expected.push(format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&r.config),
            parity::working_folder(&our_config)
        ));
        assert_eq!(got, parity::sorted(expected), "{name}: config.xml");
        report.push(format!(
            "{name} config.xml: every value the solver reads is the original's, ids included with \
             no map (3503, 3510, 3669, pinned from the run's snapshot), but the stored receiver \
             directions and the differences by design ({} lines, as parity_inputs.rs); the .proj's \
             own ids are its last session's (1792, 1473, 1632)",
            got.len()
        ));
        // Identity maps (asserted above): each id compared as written.
        let rs = parity::id_map(&r.config, &our_config, "recepteur_surfacique");
        let en = parity::id_map(&r.config, &our_config, "encombrement");
        let faces = parity::face_differences(&r.mesh, &cbin::read(&our_cbin).unwrap(), &rs, &en);
        assert_eq!(faces, Vec::<String>::new(), "{name}: mesh.cbin");
        report.push(format!(
            "{name} mesh.cbin: every face's corners (f32 bits), idMat, idRs and idEn the original's, \
             idRs {:?} as written; our {} bytes weld the original's 36 vertices into 8",
            rs.keys().collect::<Vec<_>>(),
            our_cbin.len()
        ));

        // The same-seed runs.
        let (theirs, d) = same_seed(
            &format!("t1-{name}"),
            kind,
            (&r.config, &r.mesh_bytes, &r.tetra_bytes),
            (&our_config, &our_cbin, &our_mbin),
            &rs,
        );
        if kind == SolverKind::Tcr {
            assert_eq!(d, Vec::<String>::new(), "{name}: results");
            report.push(format!(
                "{name} same-seed run: all {} output files equal to the original inputs' run",
                theirs.len()
            ));
            continue;
        }
        // SPPS: the receivers' stored directions (parity::tutorial1_directions) reach each point
        // receiver's `Advanced sound level.gap`, in the last bits; nothing else differs. The
        // proof: our config with the run's own directions gives the original's results exactly.
        let files: Vec<&str> = d.iter().map(|l| l.split(": ").next().unwrap()).collect();
        assert_eq!(
            files,
            [
                "Punctual receivers/Receiver 1/Advanced sound level.gap",
                "Punctual receivers/Receiver 2/Advanced sound level.gap"
            ],
            "{name}: results: {d:#?}"
        );
        let with_run_directions = directions_of(&our_config, &r.config);
        let (_, d2) = same_seed(
            &format!("t1-{name}-dirs"),
            kind,
            (&r.config, &r.mesh_bytes, &r.tetra_bytes),
            (&with_run_directions, &our_cbin, &our_mbin),
            &rs,
        );
        assert_eq!(
            d2,
            Vec::<String>::new(),
            "{name}: results with the run's receiver directions"
        );
        report.push(format!(
            "{name} same-seed run: {} of {} output files equal to the original inputs' run; the 2 \
             `Advanced sound level.gap` differ in the last bits (first: {}), from the receiver \
             directions the .proj stores with 6 digits: with the run's own directions, all {} equal",
            theirs.len() - d.len(),
            theirs.len(),
            d[0],
            theirs.len()
        ));
    }
    print_report("tutorial 1", &report);
}

/// `ours` with each point receiver's direction (`u`, `v`, `w`) replaced by `theirs`'s, receiver by
/// receiver in list order: the directions upstream's GUI held when it wrote the run, which its
/// project file keeps only to 6 significant digits.
fn directions_of(ours: &str, theirs: &str) -> String {
    let doc = roxmltree::Document::parse(theirs).unwrap();
    let stored: Vec<[String; 3]> = doc
        .descendants()
        .filter(|n| n.has_tag_name("recepteur_ponctuel"))
        .map(|n| ["u", "v", "w"].map(|a| n.attribute(a).unwrap().to_string()))
        .collect();
    let tag = "<recepteur_ponctuel ";
    assert_eq!(ours.matches(tag).count(), stored.len());
    let mut out = String::new();
    let mut rest = ours;
    for uvw in &stored {
        let at = rest.find(tag).unwrap();
        out.push_str(&rest[..at]);
        let end = at + rest[at..].find('>').unwrap() + 1;
        let mut element = rest[at..end].to_string();
        for (a, v) in ["u", "v", "w"].iter().zip(uvw) {
            element = edit_attr(&element, tag, a, v);
        }
        out.push_str(&element);
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

// ---------------------------------------------------------------------------------------------
// Tutorial 2

/// The lines of tutorial 2 whose text differs from the original's while every value is equal:
/// coordinates at an exact decimal tie in the 17th significant digit (the first is
/// 0.0977344512939453125, `...312` in ours, `...313` in 2019's). Programs built with Visual Studio
/// 2019 16.2 or later print such a tie rounded to even through the UCRT's `printf`, older ones
/// round it up. Our `.poly` writer rounds to even as a present build of upstream's GUI would, in
/// 307 lines of the `.poly`; TetGen 1.5.0, built as upstream's 929a5c8 builds it, in 1,036 lines
/// of the `.1.node`. Upstream's own 1.3.4 `tetgen.exe` prints the `.node` as ours does, its 1.3.3
/// as the 2019 file does (`third_party/tetgen-1.5.0/PROVENANCE.md`). TetGen reads the `.poly`, and
/// the `.mbin` builder the `.node`, as the same `f64` either way.
const TUTORIAL2_TIES: Ties = (307, 1036);

/// Tutorial 2 (the Elmia hall, 7,860 faces): the mesher's inputs and TetGen's output equal to
/// original I-Simpa's. It holds no run folder, so there is no original `.mbin`, `.cbin`,
/// `config.xml` or result to compare: said, not skipped.
///
/// Its mesh settings ask for upstream's scene correction, and on this hall `preprocess.exe` gives
/// up: its splitting loop runs out of its 100 passes, it prints `Mesh reparation has been
/// aborted`, saves nothing, and exits 0. Upstream's GUI does not look, and meshes the `.poly` it
/// wrote (its stored `temp/scene_mesh.poly` is that file). Ours does the same, loudly: `simpa
/// mesh` meshes the `.poly` as written, says so on stderr, records the abort and its reason in
/// `mesh.json` (`preprocess.outcome` `aborted`), and holds that `.poly` to the geometry check
/// before TetGen, which it passes. The `.proj` as it is then meshes to upstream's files. The
/// say-no of the fallback (an aborted `.poly` the check refuses is refused) is in
/// `mesh_project.rs` and `tools/gates/m5.ps1` (h).
#[test]
fn tutorial_2() {
    let t = tutorial(parity::TUTORIAL2);
    assert!(
        t.runs.is_empty(),
        "tutorial 2 now holds run folders: compare them"
    );
    let dir = bed_dir("t2");
    let project = import_proj(parity::TUTORIAL2, &dir);
    let p = simpa_core::schema::load(&project).unwrap();
    assert!(
        p.solvers.meshing.preprocess,
        "the .proj asks for preprocess"
    );
    let mesh_dir = dir.join("mesh");
    let o = simpa_run(&[
        "mesh".to_string(),
        project.display().to_string(),
        "--out".into(),
        mesh_dir.display().to_string(),
        "--json".into(),
    ]);
    assert_eq!(o.code, 0, "{o:#?}");
    let m = json(&o);
    assert_eq!(m["status"], "OK", "{m:#}");
    let pre = &m["preprocess"];
    assert_eq!(pre["outcome"], "aborted", "{pre:#}");
    assert_eq!(pre["printed"]["aborted"], true);
    assert!(
        pre["aborted_reason"].as_str().unwrap().contains("gave up"),
        "{pre:#}"
    );
    // TetGen read the .poly as written: its hash is the input's, and the geometry check on it
    // passed before TetGen ran.
    assert_eq!(m["files"]["poly"], pre["input_sha256"]);
    assert_eq!(
        m["geometry"]["checked"],
        "written, preprocess.exe having given up"
    );
    assert_eq!(m["geometry"]["verdict"], "ok");
    let said: Vec<&str> = o
        .stderr
        .lines()
        .filter(|l| l.starts_with("simpa: note: preprocess.exe"))
        .collect();
    assert_eq!(said.len(), 1, "{}", o.stderr);
    println!("tutorial 2: TetGen argv {}", m["tetgen"]["argv"]);
    let mut report = vec![format!(
        "simpa mesh on the .proj as it is: OK; preprocess.exe gives up after {} splits and saves \
         nothing, and the .poly as written is meshed, as upstream's GUI meshes it; stderr: {}",
        pre["printed"]["split_lines"], said[0]
    )];
    report.extend(compare_mesher_files(
        &t,
        &mesh_dir,
        TUTORIAL2_TIES,
        "tutorial 2",
    ));
    report.push(
        "tetramesh.mbin, mesh.cbin, config.xml, results: the .proj holds no run folder, so no \
         original to compare with"
            .to_string(),
    );
    print_report("tutorial 2", &report);
}

// ---------------------------------------------------------------------------------------------
// Tutorial 3

/// Upstream's stored `temp/scene_mesh.poly` of tutorial 3, as `preprocess.exe` saved it: its size
/// and the first 8 hex digits of its sha256.
const T3_POLY: (usize, &str) = (4_889, "74b8f831");

/// Each of tutorial 3's stored runs' `tetramesh.mbin`: its size and the first 8 hex digits of its
/// sha256.
const T3_MBIN: (usize, &str) = (338_528, "bc2f0904");

/// Upstream's element id to our solver id, per `config.xml` element (`encombrement`,
/// `recepteur_ponctuel`, `recepteur_surfacique_coupe`, ...): the explicit, recorded map through
/// which upstream's files and ours are compared while a project does not keep upstream's ids
/// (Burhan's open decision 1; `geometry::import::proj`, "Element ids").
type IdMap = BTreeMap<&'static str, BTreeMap<i32, i32>>;

/// The map a `.proj` import recorded (`ProjReport::upstream_ids`: upstream's id beside the entity
/// it became), composed with the solver ids our export gives those entities
/// (`SolverIds::assign`). Sources are left out: the solvers read no source id
/// (`docs/formats/config_xml.md`). Panics unless each element's map is one-to-one.
fn recorded_ids(report: &ProjReport, project: &Project) -> IdMap {
    let solver = SolverIds::assign(project).unwrap();
    let mut out = IdMap::new();
    for u in &report.upstream_ids {
        let ours = match u.kind {
            UpstreamKind::Source => continue,
            UpstreamKind::PointReceiver => solver.point_receiver_id(PointReceiverId(u.entity)),
            UpstreamKind::SurfaceReceiver | UpstreamKind::CuttingPlane => {
                solver.surface_receiver_id(SurfaceReceiverId(u.entity))
            }
            UpstreamKind::FittingZone => solver.fitting_zone_id(FittingZoneId(u.entity)),
        };
        let ours =
            ours.unwrap_or_else(|| panic!("{} `{}` has no solver id", u.kind.name(), u.name));
        let upstream = i32::try_from(u.upstream).unwrap();
        let map = out.entry(u.kind.config_element()).or_default();
        assert!(
            map.insert(upstream, ours).is_none(),
            "upstream id {upstream} recorded twice"
        );
    }
    for (element, map) in &out {
        let ours: BTreeSet<&i32> = map.values().collect();
        assert_eq!(ours.len(), map.len(), "{element}: not one-to-one: {map:?}");
    }
    out
}

/// `simpa import-proj <tutorial> <dir>/project.simpa --json`: must exit 0. The project's path and
/// the JSON it printed (the summary, the recorded upstream ids and the notes).
fn import_proj_json(rel: &str, dir: &Path) -> (PathBuf, Value) {
    let proj = support::paths::upstream_file(rel);
    let out = dir.join("project.simpa");
    let o = simpa_run(&[
        "import-proj".to_string(),
        proj.display().to_string(),
        out.display().to_string(),
        "--json".into(),
    ]);
    assert_eq!(o.code, 0, "import-proj {rel}: {o:#?}");
    (out, json(&o))
}

/// `simpa mesh <project> --out <out> --json` with `extra` options: its exit code and manifest.
fn mesh_with(project: &Path, out: &Path, extra: &[&str]) -> (i32, Value) {
    let mut args = vec![
        "mesh".to_string(),
        project.display().to_string(),
        "--out".into(),
        out.display().to_string(),
        "--json".into(),
    ];
    args.extend(extra.iter().map(|s| s.to_string()));
    let o = simpa_run(&args);
    (o.code, json(&o))
}

/// A manifest's reason codes.
fn mesh_codes(m: &Value) -> Vec<String> {
    m["codes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c.as_str().unwrap().to_string())
        .collect()
}

/// The tetrahedra of `<dir>/scene_mesh.1.{node,ele}` as a `.mbin` mesh holds them (upstream's
/// corner order, each node through upstream's OpenGL round trip in `unitize`, `idVolume` the
/// region attribute), with no face data: for a TetGen 1.6.0 output that stopped, whose `.face` is
/// cut short and which wrote no `.neigh`, so no `.mbin` can be built from it. The region volume
/// check reads the corners and the ids only.
fn tetrahedra_only(dir: &Path, unitize: &simpa_core::mesh::Unitize) -> mbin::Mesh {
    use simpa_core::formats::tetgen as tg;
    let node = tg::read_node(&std::fs::read(dir.join("scene_mesh.1.node")).unwrap()).unwrap();
    let ele = tg::read_ele(&std::fs::read(dir.join("scene_mesh.1.ele")).unwrap()).unwrap();
    let face = mbin::TetraFace {
        vertices: [0, 0, 0],
        marker: -1,
        neighbor: -2,
    };
    mbin::Mesh {
        nodes: node
            .points
            .iter()
            .map(|p| unitize.round_trip(p.map(|c| c as f32)))
            .collect(),
        tetrahedra: (0..ele.len())
            .map(|k| {
                let c = ele.tet(k);
                let b = node.first;
                mbin::Tetrahedron {
                    vertices: simpa_core::mesh::upstream_order([
                        c[0] - b,
                        c[1] - b,
                        c[2] - b,
                        c[3] - b,
                    ]),
                    id_volume: *ele.tet_attributes(k).last().unwrap() as i32,
                    faces: [face; 4],
                }
            })
            .collect(),
    }
}

/// The region volume check's reference, built as the mesher builds it: `geometry::check` on a
/// `.poly`'s nodes and facet list, its facet markers, and the project's fitting zones.
struct Reference {
    model: simpa_core::formats::poly::Model,
    facets: Vec<[u32; 3]>,
    markers: Vec<u32>,
    check: simpa_core::geometry::check::CheckReport,
    fittings: Vec<simpa_core::mesh::FittingRegion>,
}

impl Reference {
    fn of(poly: &[u8], project: &Project) -> Self {
        let model = simpa_core::formats::poly::read(poly).unwrap();
        let group = simpa_core::schema::GroupId::from_u128(0);
        let geometry = simpa_core::schema::Geometry {
            vertices: model
                .model_vertices
                .iter()
                .map(|&v| simpa_core::schema::Vec3::from(v))
                .collect(),
            faces: model
                .model_faces
                .iter()
                .map(|f| simpa_core::schema::Face {
                    vertices: f.vertices,
                    group,
                })
                .collect(),
        };
        let check = simpa_core::geometry::check::check(&geometry);
        assert!(check.is_ok(), "{:?}", check.reasons);
        Reference {
            facets: model.model_faces.iter().map(|f| f.vertices).collect(),
            markers: model.model_faces.iter().map(|f| f.face_index).collect(),
            fittings: simpa_core::mesh::project_input(project).unwrap().fittings,
            check,
            model,
        }
    }

    fn get(&self) -> simpa_core::mesh::verify::Reference<'_> {
        simpa_core::mesh::verify::Reference {
            vertices: &self.model.model_vertices,
            facets: &self.facets,
            markers: &self.markers,
            check: &self.check,
            fittings: &self.fittings,
        }
    }
}

/// Tutorial 3 made ready for the bed: the `.proj`; per stored run, its project (the `.proj` read
/// with the `projet_config.xml` upstream saved beside that run, `import_proj_with_config`: the
/// three runs differ in `nbparticules` and `trans_calc` only), saved as `.simpa`, and the id map
/// its import recorded ([`recorded_ids`]), the identity since imports pin upstream's ids
/// (decision 13); the `.proj` imported by `simpa import-proj` as a user
/// does it, and meshed by `simpa mesh --parity` end to end: our `.poly`, `preprocess.exe`, our
/// geometry check, TetGen 1.5.0 and our `.mbin`, with `preprocess.exe`'s facet markers kept as
/// upstream's GUI meshes them.
struct Tutorial3 {
    t: Tutorial,
    dir: PathBuf,
    projects: Vec<PathBuf>,
    ids: Vec<IdMap>,
    /// `simpa import-proj`'s project, and the JSON it printed.
    imported: PathBuf,
    summary: Value,
    /// The parity mesh folder and its manifest.
    parity_dir: PathBuf,
    parity: Value,
    /// Our `.mbin` from the parity mesh, as written: upstream's ids, pinned.
    built: mbin::Mesh,
}

fn tutorial3(label: &str) -> Tutorial3 {
    let t = tutorial(parity::TUTORIAL3);
    let dir = bed_dir(label);
    assert_eq!(t.runs.len(), 3);
    let mut projects = Vec::new();
    let mut ids = Vec::new();
    for (i, r) in t.runs.iter().enumerate() {
        let imported = simpa_core::geometry::import::import_proj_with_config(
            &t.bytes,
            r.project_file.as_bytes(),
        )
        .unwrap_or_else(|e| panic!("run {i}: {} ({e})", e.code()));
        ids.push(recorded_ids(&imported.report, &imported.project));
        let path = dir.join(format!("run{i}.simpa"));
        simpa_core::schema::save(&imported.project, &path).unwrap();
        projects.push(path);
    }
    let (imported, summary) = import_proj_json(parity::TUTORIAL3, &dir);
    let p = simpa_core::schema::load(&imported).unwrap();
    assert!(
        p.solvers.meshing.preprocess,
        "tutorial 3's mesh settings ask for preprocess"
    );
    let parity_dir = dir.join("mesh-parity");
    let (code, parity) = mesh_with(&imported, &parity_dir, &["--parity"]);
    // Parity mode keeps preprocess.exe's markers, so the mesh fails verification, by name, and its
    // .mbin is written for the comparison only.
    assert_eq!(code, 4, "{parity:#}");
    assert_eq!(
        mesh_codes(&parity),
        [
            "mesh_invalid",
            "marker_geometry_mismatches",
            "uncovered_scene_faces"
        ],
        "{parity:#}"
    );
    assert_eq!(parity["parity"], true);
    let built = mbin::read_file(&parity_dir.join("tetramesh.mbin")).unwrap();
    Tutorial3 {
        t,
        dir,
        projects,
        ids,
        imported,
        summary,
        parity_dir,
        parity,
        built,
    }
}

/// Tutorial 3 (a room with two fitting zones, a scene-fitted one and a box, six sources in two
/// source groups, five point receivers and a cutting plane), from its `.proj`, end to end:
/// - **`simpa import-proj`** reads it: the zones (the box's corners as upstream stores them, not
///   ordered), material 100's reflection law and materials 100 and 101's transmission per band,
///   the sources through their groups, and the mesh settings' "preprocess". Its say-no: the same
///   `.proj` with the box's element type made unknown is refused by name;
/// - **`simpa mesh --parity`** meshes it as upstream's GUI does (`projet_maillage.cpp:206-213`):
///   our `.poly`, the box in its user facet list, through `preprocess.exe`, our geometry check,
///   TetGen 1.5.0 and our builder. `preprocess.exe`'s `.poly` is upstream's `temp/scene_mesh.poly`
///   byte for byte (4,889 bytes, sha256 `74b8f831...`), TetGen's `.1.*` its `temp/` files, and
///   the `.mbin` each run's `tetramesh.mbin` (338,528 bytes, `bc2f0904...`), all with no id map:
///   the import pins upstream's ids (decision 13), the fittings 1930 and 2083, and TetGen numbers
///   the room's parts 2084 to 2086 above them. Measured: `preprocess.exe`'s reader gives every
///   box facet marker 88 (`poly.cpp:418-423`), and verification names what that does (280 marker
///   mismatches, faces 90 to 99 uncovered), so the parity mesh never passes;
/// - **`simpa mesh`**, the default mode: the same, the markers restored and zone 1's seed, which
///   lies on its top face, moved inside it; it verifies clean, each region's volume its cell's;
/// - **each stored run's `config.xml` and `mesh.cbin`**, against ours from the `.proj` read with
///   that run's saved project: every value the solver reads is the original's, ids included with
///   no map, the differences by design aside; the `.cbin` byte for byte, the box's 12 triangles as
///   faces 88 to 99.
///
/// Its say-nos: without preprocess the box standing on the floor is refused (our check's 20 pairs,
/// and TetGen's); TetGen 1.6.0's mesh of the raw scene, the wrong room, fails the region volume
/// check, and 1.6.0 on the parity `.poly` puts zone 1 on the hall; upstream's `.poly` with one
/// region line changed gives another `.mbin`; zone 1 pinned to 1931 gives another `.poly` and
/// `.mbin`; both zones pinned to 1930 are refused before meshing; one band's law changed, the
/// box's triangles left out, and the ids unpinned.
#[test]
fn tutorial_3() {
    let Tutorial3 {
        t,
        dir,
        projects,
        ids,
        imported,
        summary,
        parity_dir,
        parity: pm,
        built,
    } = tutorial3("t3");

    // The import, as a user meets it.
    let p = simpa_core::schema::load(&imported).unwrap();
    assert_eq!(
        (
            p.geometry.vertices.len(),
            p.geometry.faces.len(),
            p.sources.len(),
            p.point_receivers.len(),
            p.surface_receivers.len(),
            p.fitting_zones.len(),
        ),
        (40, 88, 6, 5, 1, 2)
    );
    let zones: Vec<String> = p
        .fitting_zones
        .iter()
        .map(|z| format!("{} {}", z.name, serde_json::to_string(&z.shape).unwrap()))
        .collect();
    let recorded: Vec<(String, String)> = summary["upstream_ids"]
        .as_array()
        .unwrap()
        .iter()
        .map(|u| {
            (
                u["kind"].as_str().unwrap().to_string(),
                format!("{} = {}", u["name"], u["upstream"]),
            )
        })
        .collect();
    assert_eq!(recorded.len(), 6 + 5 + 1 + 2, "{recorded:#?}");
    let fittings: Vec<&String> = recorded
        .iter()
        .filter(|(kind, _)| kind == "fitting zone")
        .map(|(_, u)| u)
        .collect();
    let mut report = vec![
        format!(
            "import-proj: exit 0; {} faces, {} vertices, {} sources, zones {zones:?}; {} upstream \
             ids recorded, the fittings {:?}; mesh settings preprocess = {}",
            p.geometry.faces.len(),
            p.geometry.vertices.len(),
            p.sources.len(),
            recorded.len(),
            fittings,
            p.solvers.meshing.preprocess
        ),
        format!("import-proj notes: {}", summary["notes"]),
    ];
    // The CLI's project is the last run's (the .proj's own project file is saved with it): the
    // same config.xml and mesh.cbin, but the working folder.
    let cli = export_config(&imported, &dir.join("export-cli"), SolverKind::Spps);
    let run2 = export_config(&projects[2], &dir.join("export-run2"), SolverKind::Spps);
    assert_eq!(
        parity::solver_differences(&cli.0, &run2.0),
        vec![format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&cli.0),
            parity::working_folder(&run2.0)
        )]
    );
    assert_eq!(cli.1, run2.1, "mesh.cbin");

    // The validator on the project as imported (Burhan, 2026-09-24 14:11): the two source groups
    // each hold `Source 1` to `Source 3`, which is allowed within their groups; Receiver 1 lies on
    // the x = 0 wall, which stays refused, by its own code, naming the wall. Nothing else.
    let v = simpa_run(&["validate".to_string(), imported.display().to_string()]);
    assert_eq!(v.code, 2, "{v:#?}");
    let errors: Vec<&str> = v
        .stdout
        .lines()
        .chain(v.stderr.lines())
        .filter(|l| l.starts_with("error "))
        .collect();
    assert_eq!(errors.len(), 1, "{v:#?}");
    assert!(
        errors[0].starts_with("error receiver_on_surface at /point_receivers/0/position")
            && errors[0].contains("'Receiver 1'")
            && errors[0].contains("surface group 'diff_wall'")
            && errors[0].contains("move it inside the room"),
        "{}",
        errors[0]
    );
    let groups: BTreeSet<Option<&str>> = p.sources.iter().map(|s| s.group.as_deref()).collect();
    assert_eq!(
        groups,
        BTreeSet::from([Some("Milling Machine"), Some("Milling Machine 2")])
    );
    report.push(format!(
        "simpa validate on the import: exit 2, {}",
        errors[0]
    ));

    // Says no: the box's element type 56 made 57 (no element type upstream knows).
    let unknown = parity::with_entry(&t, "instance1/projet_config.xml", |xml| {
        let xml = String::from_utf8(xml.to_vec()).unwrap();
        let from = "eid=\"56\" wxid=\"2083\"";
        assert_eq!(xml.matches(from).count(), 1);
        xml.replace(from, "eid=\"57\" wxid=\"2083\"").into_bytes()
    });
    let unknown_path = dir.join("unknown_zone_type.proj");
    std::fs::write(&unknown_path, unknown).unwrap();
    let o = simpa_run(&[
        "import-proj".to_string(),
        unknown_path.display().to_string(),
        dir.join("refused.simpa").display().to_string(),
    ]);
    assert_eq!(o.code, 2, "{o:#?}");
    assert!(
        o.stderr.contains("proj_fitting_type_unknown"),
        "{}",
        o.stderr
    );
    report.push(format!(
        "import-proj says no: the box's element type made 57: exit 2, {}",
        o.stderr.trim()
    ));

    // Upstream's ids, pinned on import (decision 13): the map the import records is the identity
    // for every element, and the imported project's zones are upstream's 1930 and 2083.
    for (i, m) in ids.iter().enumerate() {
        for (element, map) in m {
            assert!(
                map.iter().all(|(a, b)| a == b),
                "run {i}: {element} ids {map:?}"
            );
        }
    }
    let pinned: Vec<Option<u32>> = p.fitting_zones.iter().map(|z| z.solver_id).collect();
    assert_eq!(pinned, [Some(1930), Some(2083)]);
    let region_ids: BTreeSet<i32> = mbin::read(&t.runs[2].tetra_bytes)
        .unwrap()
        .tetrahedra
        .iter()
        .map(|t| t.id_volume)
        .collect();
    assert_eq!(
        region_ids,
        BTreeSet::from([1930, 2083, 2084, 2085, 2086]),
        "upstream's fittings, and TetGen's room parts above them"
    );

    // --- The parity mesh, end to end. ---
    let pre = &pm["preprocess"];
    let printed = &pre["printed"];
    assert_eq!(
        (
            printed["vertices_merged"].as_u64(),
            printed["faces_destroyed"].as_u64(),
            printed["faces_split"].as_u64()
        ),
        (Some(28), Some(2), Some(31)),
        "{pre:#}"
    );
    let acc = &pre["accounting"];
    assert_eq!(
        acc["deleted"],
        serde_json::json!([88, 89]),
        "the box's bottom"
    );
    assert_eq!(acc["marker_changes"].as_array().unwrap().len(), 19);
    assert!(
        acc["marker_changes"]
            .as_array()
            .unwrap()
            .iter()
            .all(|c| c["written"] == 88 && (90..100).contains(&c["restored"].as_u64().unwrap())),
        "every box facet written 88, each in one of 90 to 99: {acc:#}"
    );
    assert_eq!(pre["markers_rewritten"], false, "parity keeps them");
    assert_eq!(pm["geometry"]["verdict"], "ok");
    // The raw bytes, with no id map: the .poly preprocess.exe saved is upstream's, its region lines
    // included (1930 and 2083, pinned), and so is every TetGen file and the .mbin.
    let ours_poly = std::fs::read(parity_dir.join("scene_mesh.poly")).unwrap();
    let theirs_poly = entry(&t, "temp/scene_mesh.poly");
    assert_eq!(
        (
            theirs_poly.len(),
            &simpa_core::mesh::sha256_hex(&theirs_poly)[..8]
        ),
        (T3_POLY.0, T3_POLY.1),
        "upstream's stored temp/scene_mesh.poly"
    );
    assert_eq!(
        byte_difference(&ours_poly, &theirs_poly),
        None,
        "preprocess.exe's .poly, byte for byte with no id map"
    );
    let input_poly = std::fs::read(parity_dir.join("scene_mesh.input.poly")).unwrap();
    report.push(format!(
        "simpa mesh --parity: our .poly ({} bytes, {} facets, the box's 12 triangles in the user \
         facet list) through preprocess.exe ({}): {} bytes, sha256 {}, upstream's \
         temp/scene_mesh.poly byte for byte, with no id map",
        input_poly.len(),
        pm["preprocess"]["input"]["facets"],
        pm["messages"]
            .as_array()
            .unwrap()
            .iter()
            .find(|l| l.as_str().unwrap().starts_with("preprocess.exe"))
            .unwrap()
            .as_str()
            .unwrap(),
        ours_poly.len(),
        &simpa_core::mesh::sha256_hex(&ours_poly)[..16]
    ));
    for ext in TETGEN_FILES {
        let name = format!("scene_mesh.1.{ext}");
        let ours = std::fs::read(parity_dir.join(&name)).unwrap();
        report.push(format!(
            "{} (the parity mesh's TetGen, with no id map)",
            compare_text(
                &name,
                &ours,
                &entry(&t, &format!("temp/{name}")),
                0,
                "tutorial 3"
            )
        ));
    }
    let our_mbin = mbin::write(&built);
    assert!(
        our_mbin == std::fs::read(parity_dir.join("tetramesh.mbin")).unwrap(),
        "the .mbin the mesher wrote"
    );
    for (i, r) in t.runs.iter().enumerate() {
        assert_eq!(
            (
                r.tetra_bytes.len(),
                &simpa_core::mesh::sha256_hex(&r.tetra_bytes)[..8]
            ),
            (T3_MBIN.0, T3_MBIN.1),
            "run {i}: upstream's stored tetramesh.mbin"
        );
        assert_eq!(
            byte_difference(&our_mbin, &r.tetra_bytes),
            None,
            "run {i}: tetramesh.mbin, byte for byte with no id map"
        );
    }
    report.push(format!(
        "the parity mesh's tetramesh.mbin: each run's, byte for byte ({} bytes, sha256 {}), with \
         no id map; {} tetrahedra, idVolume {:?}",
        our_mbin.len(),
        &simpa_core::mesh::sha256_hex(&our_mbin)[..16],
        built.tetrahedra.len(),
        built
            .tetrahedra
            .iter()
            .map(|t| t.id_volume)
            .collect::<BTreeSet<i32>>()
    ));
    // Says no, decision 13: the same project with zone 1 pinned to 1931 instead of upstream's 1930
    // gives other bytes, its region line in the .poly and its tetrahedra's idVolume in the .mbin.
    let mut repinned = p.clone();
    repinned.fitting_zones[0].solver_id = Some(1931);
    let repinned_path = dir.join("repinned.simpa");
    simpa_core::schema::save(&repinned, &repinned_path).unwrap();
    let repinned_dir = dir.join("mesh-parity-repinned");
    let (code, rp) = mesh_with(&repinned_path, &repinned_dir, &["--parity"]);
    assert_eq!(code, 4, "{rp:#}");
    let other_poly = std::fs::read(repinned_dir.join("scene_mesh.poly")).unwrap();
    let other_mbin = std::fs::read(repinned_dir.join("tetramesh.mbin")).unwrap();
    let poly_says = byte_difference(&other_poly, &theirs_poly);
    let mbin_says = byte_difference(&other_mbin, &t.runs[0].tetra_bytes);
    assert!(
        poly_says.is_some() && mbin_says.is_some(),
        "a changed pin gave upstream's bytes"
    );
    report.push(format!(
        "says no, zone 1 pinned to 1931: the parity .poly {}; the .mbin {}",
        poly_says.unwrap(),
        mbin_says.unwrap()
    ));
    // Says no: two zones pinned to one id are refused before meshing, by name.
    let mut clash = p.clone();
    clash.fitting_zones[1].solver_id = Some(1930);
    let clash_path = dir.join("clash.simpa");
    std::fs::write(&clash_path, simpa_core::schema::to_json(&clash)).unwrap();
    let o = simpa_run(&[
        "mesh".to_string(),
        clash_path.display().to_string(),
        "--out".into(),
        dir.join("mesh-clash").display().to_string(),
    ]);
    assert_eq!(o.code, 2, "{o:#?}");
    assert!(
        o.stderr.contains("solver_id_mapping_invalid"),
        "{}",
        o.stderr
    );
    report.push(format!(
        "says no, both zones pinned to 1930: simpa mesh exits 2, {}",
        o.stderr.lines().next().unwrap_or("")
    ));

    let v = &pm["verify"];
    assert_eq!(v["marker_geometry_mismatches"], 280, "{v:#}");
    assert_eq!(
        v["uncovered_scene_faces_first"],
        serde_json::json!([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
    );
    assert_eq!(v["expected_unmeshed_faces"], serde_json::json!([88, 89]));
    assert_eq!(
        (
            v["region_volume_mismatch"].as_u64(),
            v["unmeshed_cells"].as_u64(),
            v["fitting_region_misplaced"].as_u64(),
            v["fitting_seed_ambiguous"].as_u64()
        ),
        (Some(0), Some(0), Some(0), Some(0)),
        "{v:#}"
    );
    report.push(format!(
        "the parity mesh's verification: FAIL, by name: 280 marker mismatches (the box's facets \
         all marker 88, upstream's reader), faces {} uncovered, 88 and 89 deleted by preprocess; \
         every region its cell's volume",
        v["uncovered_scene_faces_first"]
    ));

    // --- The default mode: markers restored, the seed on a face moved inside. ---
    let default_dir = dir.join("mesh-default");
    let (code, dm) = mesh_with(&imported, &default_dir, &[]);
    assert_eq!(code, 0, "{dm:#}");
    assert_eq!(dm["status"], "OK");
    assert_eq!(dm["preprocess"]["markers_rewritten"], true);
    let moved = dm["seeds_moved"].as_array().unwrap();
    assert_eq!(moved.len(), 1, "{dm:#}");
    assert_eq!(moved[0]["zone"], "Fitting zone 1");
    let dv = &dm["verify"];
    assert_eq!(dv["regions_checked"], true);
    let mut cells: Vec<(f64, i64)> = dv["regions"]
        .as_array()
        .unwrap()
        .iter()
        .map(|r| {
            let (v, c) = (
                r["volume_m3"].as_f64().unwrap(),
                r["cell_volume_m3"].as_f64().unwrap(),
            );
            assert!(
                (v - c).abs() <= r["tolerance_m3"].as_f64().unwrap(),
                "{r:#}"
            );
            (v, r["id"].as_i64().unwrap())
        })
        .collect();
    cells.sort_by(|a, b| a.0.total_cmp(&b.0));
    let volumes_m3: Vec<f64> = cells.iter().map(|c| (c.0 * 1e3).round() / 1e3).collect();
    assert_eq!(
        volumes_m3,
        [4.352, 18.0, 93.445, 106.895, 755.648],
        "zone 1, the box, room 2 without it, the corridor, the hall"
    );
    report.push(format!(
        "simpa mesh (default): OK; {} of preprocess.exe's markers restored; zone 1's seed {} moved \
         to {} (it lay on facet {}); {} tetrahedra; region volumes (id, m³) {:?}, each its cell's",
        dm["preprocess"]["accounting"]["marker_changes"]
            .as_array()
            .unwrap()
            .len(),
        moved[0]["from"],
        moved[0]["to"],
        moved[0]["on_facets"],
        dm["counts"]["build"]["tetrahedra"],
        cells.iter().map(|c| (c.1, c.0)).collect::<Vec<_>>()
    ));

    // --- Says no: without preprocess.exe the box stands on the floor. ---
    let off = dir.join("preprocess-off.simpa");
    let mut po = p.clone();
    po.solvers.meshing.preprocess = false;
    simpa_core::schema::save(&po, &off).unwrap();
    let (code, om) = mesh_with(&off, &dir.join("mesh-off"), &[]);
    assert_eq!(code, 4, "{om:#}");
    assert!(
        mesh_codes(&om).contains(&"tetgen_self_intersection".to_string()),
        "{om:#}"
    );
    let gate = &om["geometry"];
    assert_eq!(gate["verdict"], "refused");
    let ours_pairs: BTreeSet<(u64, u64)> = gate["pairs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| (p[0].as_u64().unwrap(), p[1].as_u64().unwrap()))
        .collect();
    let tetgen_pairs: BTreeSet<(u64, u64)> = om["self_intersection"]["pairs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| (p[0].as_u64().unwrap(), p[1].as_u64().unwrap()))
        .collect();
    // Every pair is the box (markers 88 to 99) against the floor, as TetGen names them. There are
    // 22 here, not the investigation's 20: without preprocessing the mesher triangulates the box
    // its own way (decision 5), not as upstream's BuildModel does.
    assert!(!ours_pairs.is_empty(), "{gate:#}");
    assert!(
        ours_pairs
            .iter()
            .all(|&(a, b)| a < 88 && (88..100).contains(&b)),
        "{ours_pairs:?}"
    );
    assert_eq!(
        ours_pairs, tetgen_pairs,
        "our check and TetGen 1.5.0 name the same pairs"
    );
    report.push(format!(
        "says no, preprocess off: exit 4, {}; our check on the .poly refuses it with \
         self_intersections, the same {} pairs TetGen 1.5.0's -d names, {:?}",
        mesh_codes(&om).join(", "),
        ours_pairs.len(),
        ours_pairs
    ));

    // --- Says no: TetGen 1.6.0. ---
    let tg160 = support::paths::tetgen160_exe();
    let tg160_arg = tg160.display().to_string();
    // (a) Its mesh of the raw scene (preprocess off): it skips facets and leaves a partial mesh,
    // the wrong room, which the mesher refuses for the skipped facets. Its tetrahedra, held to the
    // room's cells, fail the region volume check too: the check that sees a wrong room whatever
    // TetGen's exit code said.
    let raw160 = dir.join("mesh-off-tetgen160");
    let (code, rm) = mesh_with(&off, &raw160, &["--tetgen", &tg160_arg]);
    assert_eq!(code, 4, "{rm:#}");
    let room = simpa_core::config_xml::room_mesh(&po).unwrap();
    let unitize = simpa_core::mesh::Unitize::of_scene(&room).unwrap();
    let wrong = tetrahedra_only(&raw160, &unitize);
    let reference = Reference::of(&ours_poly, &p);
    let ids160 = simpa_core::mesh::verify::VolumeIds::tetgen(vec![1930, 2083]);
    let checked = simpa_core::mesh::verify::verify_mesh_with(
        &wrong,
        &room,
        &ids160,
        &simpa_core::mesh::verify::Expectations {
            unmeshed_faces: None,
            reference: Some(reference.get()),
        },
    );
    let total: f64 = checked.volume_by_id.values().sum();
    let room_total: f64 = reference.check.cells.iter().map(|c| c.volume_m3).sum();
    assert!(
        checked
            .codes
            .contains(&"region_volume_mismatch".to_string())
            && checked.codes.contains(&"unmeshed_cells".to_string()),
        "{:#?}",
        checked.regions
    );
    // Control: our own default mesh of the room passes the same check.
    let ours_default = mbin::read_file(&default_dir.join("tetramesh.mbin")).unwrap();
    let default_scene = cbin::read_file(&default_dir.join("mesh.cbin")).unwrap();
    let control = simpa_core::mesh::verify::verify_mesh_with(
        &ours_default,
        &default_scene,
        &simpa_core::mesh::verify::VolumeIds::tetgen(vec![1930, 2083]),
        &simpa_core::mesh::verify::Expectations {
            unmeshed_faces: Some(&[88, 89]),
            reference: Some(
                Reference::of(
                    &std::fs::read(default_dir.join("scene_mesh.poly")).unwrap(),
                    &p,
                )
                .get(),
            ),
        },
    );
    assert!(control.passed(), "{:?}", control.codes);
    report.push(format!(
        "says no, TetGen 1.6.0 on the raw scene: exit 4 ({}); its partial mesh, {} tetrahedra of \
         {:.1} m³ against the room's {:.1} m³ (idVolume {:?}), fails the region volume check: {} \
         (region_volume_mismatch {}, unmeshed_cells {}); our default mesh passes it",
        mesh_codes(&rm).join(", "),
        wrong.tetrahedra.len(),
        total,
        room_total,
        checked.volume_by_id,
        checked.codes.join(", "),
        checked.region_volume_mismatch,
        checked.unmeshed_cells
    ));
    // (b) 1.6.0 on the parity .poly, upstream's seed on zone 1's top face: it labels the hall as
    // zone 1, and the check names it.
    let (code, p160) = mesh_with(
        &imported,
        &dir.join("mesh-parity-tetgen160"),
        &["--parity", "--tetgen", &tg160_arg],
    );
    assert_eq!(code, 4, "{p160:#}");
    assert!(
        mesh_codes(&p160).contains(&"fitting_region_misplaced".to_string()),
        "{p160:#}"
    );
    report.push(format!(
        "says no, TetGen 1.6.0 in parity mode: {}; {}",
        mesh_codes(&p160).join(", "),
        p160["verify"]["regions"]
            .as_array()
            .unwrap()
            .iter()
            .filter(|r| !r["problems"].as_array().unwrap().is_empty())
            .map(|r| r["problems"].to_string())
            .collect::<Vec<_>>()
            .join("; ")
    ));
    // Measured, not asserted: 1.6.0 in the default mode, the seed moved inside zone 1.
    let (code, d160) = mesh_with(
        &imported,
        &dir.join("mesh-default-tetgen160"),
        &["--tetgen", &tg160_arg],
    );
    report.push(format!(
        "TetGen 1.6.0 in the default mode (measured): exit {code}, {} {}",
        d160["status"],
        mesh_codes(&d160).join(", ")
    ));

    // --- Says no: upstream's .poly with zone 1's region line changed (its seed 1 cm up, into the
    // hall) gives another .mbin. ---
    let mut changed = simpa_core::formats::poly::read(&theirs_poly).unwrap();
    assert_eq!(changed.model_regions[0].region_index, 1930);
    changed.model_regions[0].dot_in_region[2] += 0.01;
    let tg = dir.join("region-changed");
    std::fs::create_dir_all(&tg).unwrap();
    std::fs::write(
        tg.join("scene_mesh.poly"),
        simpa_core::formats::poly::write(&changed),
    )
    .unwrap();
    let ran = std::process::Command::new(solver_exe("tetgen.exe"))
        .args(["-pq2", "-A", "-n", "scene_mesh.poly"])
        .current_dir(&tg)
        .output()
        .unwrap();
    assert_eq!(ran.status.code(), Some(0));
    let out = simpa_core::mesh::TetgenOutput::read(&simpa_core::mesh::OutputPaths::new(
        &tg,
        "scene_mesh",
    ))
    .unwrap();
    let scene = simpa_core::config_xml::scene_mesh(&p).unwrap();
    let (other, _) = simpa_core::mesh::build_mbin(&out, scene.faces.len(), &unitize).unwrap();
    let none: BTreeMap<i32, i32> = BTreeMap::new();
    let d = mbin_difference(&mbin::write(&other), &t.runs[0].tetra_bytes, &none);
    assert!(d.is_some(), "a changed region line gave the stored .mbin");
    let relabelled = other
        .tetrahedra
        .iter()
        .zip(&mbin::read(&t.runs[0].tetra_bytes).unwrap().tetrahedra)
        .filter(|(a, b)| a.id_volume != b.id_volume)
        .count();
    report.push(format!(
        "says no, upstream's .poly with zone 1's seed 1 cm up: another .mbin, {relabelled} \
         tetrahedra with another idVolume ({})",
        d.unwrap()
    ));

    for (i, r) in t.runs.iter().enumerate() {
        let (our_config, our_cbin) = export_config(
            &projects[i],
            &dir.join(format!("export{i}")),
            SolverKind::Spps,
        );
        // The ids both files' list orders pair are the same numbers: no map.
        for (element, map) in &ids[i] {
            assert_eq!(
                map,
                &parity::id_map(&r.config, &our_config, element),
                "run {i}: {element}"
            );
        }
        // config.xml, value by value, upstream's as it is: the ids equal with no map.
        let theirs = r.config.clone();
        let got = parity::solver_differences(&theirs, &our_config);
        let mut expected = parity::tutorial3_by_design();
        expected.push(format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&r.config),
            parity::working_folder(&our_config)
        ));
        assert_eq!(got, parity::sorted(expected.clone()), "run {i}: config.xml");
        // mesh.cbin, byte for byte as upstream wrote it, and the mesh folder's the same bytes.
        assert_eq!(
            byte_difference(&our_cbin, &r.mesh_bytes),
            None,
            "run {i}: mesh.cbin, byte for byte with no id map"
        );
        assert_eq!(
            std::fs::read(parity_dir.join("mesh.cbin")).unwrap(),
            our_cbin,
            "the mesh folder's mesh.cbin"
        );
        let ours = cbin::read(&our_cbin).unwrap();
        let box_faces: BTreeSet<(u32, i32, i32)> = ours.faces[88..]
            .iter()
            .map(|f| (f.id_mat, f.id_rs, f.id_en))
            .collect();
        assert_eq!(
            box_faces,
            BTreeSet::from([(0, -1, 2083)]),
            "faces 88 to 99: the box, upstream's id"
        );
        report.push(format!(
            "run {i} config.xml: every value the solver reads is the original's, upstream's ids \
             equal with no map ({:?}), but the {} differences by design; mesh.cbin: byte for byte \
             ({} bytes), faces 88 to 99 the box's 12 triangles (idMat 0, idEn 2083)",
            ids[i]
                .iter()
                .map(|(e, m)| (*e, m.keys().copied().collect::<Vec<i32>>()))
                .collect::<Vec<_>>(),
            expected.len(),
            our_cbin.len()
        ));

        if i == t.runs.len() - 1 {
            // Says no, the config: material 100's law at 125 Hz, Lambert, written specular (one
            // law per material, as the importer held it before).
            let at = our_config.find("<type_surface id=\"100\"").unwrap();
            let band = at + our_config[at..].find("<bfreq freq=\"125\"").unwrap();
            let one_law = format!(
                "{}{}",
                &our_config[..band],
                edit_attr(&our_config[band..], "<bfreq", "loi", "0")
            );
            let mut with_edit = expected.clone();
            with_edit.push("type_surface[id=100]/bfreq[4]@loi: upstream 2, ours 0".to_string());
            assert_eq!(
                parity::solver_differences(&theirs, &one_law),
                parity::sorted(with_edit)
            );
            // Says no, the ids: the project with no pins (as one made here) writes our own
            // numbering, 8 ids apart from upstream's.
            let mut unpinned = simpa_core::schema::load(&projects[i]).unwrap();
            for z in &mut unpinned.fitting_zones {
                z.solver_id = None;
            }
            for x in &mut unpinned.point_receivers {
                x.solver_id = None;
            }
            for x in &mut unpinned.surface_receivers {
                x.solver_id = None;
            }
            let unpinned_path = dir.join(format!("run{i}-unpinned.simpa"));
            simpa_core::schema::save(&unpinned, &unpinned_path).unwrap();
            let (unpinned_config, unpinned_cbin) = export_config(
                &unpinned_path,
                &dir.join(format!("export{i}-unpinned")),
                SolverKind::Spps,
            );
            let unmapped = parity::solver_differences(&r.config, &unpinned_config);
            assert_eq!(unmapped.len(), got.len() + 8, "{unmapped:#?}");
            assert!(byte_difference(&unpinned_cbin, &r.mesh_bytes).is_some());
            // Says no, the scene mesh: the room's faces alone, without the box's triangles.
            let room =
                simpa_core::config_xml::room_mesh(&simpa_core::schema::load(&projects[i]).unwrap())
                    .unwrap();
            let faces =
                parity::face_differences(&r.mesh, &room, &BTreeMap::new(), &ids[i]["encombrement"]);
            assert_eq!(faces, ["faces: upstream 100, ours 88"]);
            report.push(format!(
                "run {i} says no: one band's law changed gives its line; the ids unpinned, {} \
                 lines and another mesh.cbin; the room's faces alone: {faces:?}",
                unmapped.len()
            ));
        }
    }
    print_report("tutorial 3", &report);
}

/// Tutorial 3's three SPPS runs, same seed, on the original inputs (unedited: `parity::repeatable`
/// only) and on ours: our `config.xml` and `mesh.cbin` from the `.proj` read with each run's saved
/// project, and our `.mbin` from `simpa mesh --parity` ([`tutorial3`]), as written: the fittings
/// under upstream's ids, pinned on import (decision 13), the room's parts as TetGen numbers them
/// above. Every output file must be the original's, the cutting plane's `.csbin` id included:
/// upstream's 951 on both sides, with no map.
///
/// **The input that makes it say no** is the room written 0, as this crate's builder wrote it
/// until decision 1 was reversed on 2026-09-24, on run 0. SPPS gives every tetrahedron with a
/// nonzero `idVolume` the fitting of that id, NULL for an unknown one, and hands it to the
/// tetrahedron's scene faces (`coreinitialisation.cpp:151-176`); a room written 0 is skipped, so
/// the faces a fitting's tetrahedra share with the room keep the fitting, where upstream's room
/// overwrites it. Measured on 2026-09-24: all 24 output files of each run differed that way, and
/// none with the room as TetGen numbers it.
#[test]
fn tutorial_3_same_seed_runs() {
    let Tutorial3 {
        t,
        dir,
        projects,
        ids,
        built,
        ..
    } = tutorial3("t3r");
    let our_mbin = mbin::write(&built);
    let mut report = Vec::new();
    for (i, r) in t.runs.iter().enumerate() {
        let (our_config, our_cbin) = export_config(
            &projects[i],
            &dir.join(format!("export{i}")),
            SolverKind::Spps,
        );
        let cut = ids[i]["recepteur_surfacique_coupe"].clone();
        assert_eq!(cut, BTreeMap::from([(951, 951)]), "upstream's id, pinned");
        let volumes: BTreeSet<i32> = built.tetrahedra.iter().map(|t| t.id_volume).collect();
        let (theirs, d) = same_seed(
            &format!("t3-{i}"),
            SolverKind::Spps,
            (&r.config, &r.mesh_bytes, &r.tetra_bytes),
            (&our_config, &our_cbin, &our_mbin),
            &cut,
        );
        assert_eq!(
            d,
            Vec::<String>::new(),
            "run {i}: results (idVolume {volumes:?}, cutting plane {cut:?})"
        );
        report.push(format!(
            "run {i}: all {} output files equal to the original inputs' run (our parity mesh's \
             .mbin, idVolume {volumes:?}, cutting plane {cut:?})",
            theirs.len()
        ));
        if i == 0 {
            // Says no: the room written 0, the fittings as before.
            let fittings: BTreeSet<i32> = ids[i]["encombrement"].values().copied().collect();
            let mut room_zero = built.clone();
            for tet in &mut room_zero.tetrahedra {
                if !fittings.contains(&tet.id_volume) {
                    tet.id_volume = 0;
                }
            }
            let (_, dz) = same_seed(
                "t3-0-room0",
                SolverKind::Spps,
                (&r.config, &r.mesh_bytes, &r.tetra_bytes),
                (&our_config, &our_cbin, &mbin::write(&room_zero)),
                &cut,
            );
            assert!(
                !dz.is_empty(),
                "run 0 with the room written 0 gave the original's results"
            );
            report.push(format!(
                "run 0 with the room written 0 (the builder before 2026-09-24): {} of {} files \
                 differ, first {}",
                dz.len(),
                theirs.len(),
                dz[0]
            ));
        }
    }
    print_report("tutorial 3, same-seed runs", &report);
}

// ---------------------------------------------------------------------------------------------
// Every comparison says no

/// Each comparison of the bed, fed the input that must make it fail.
#[test]
fn the_comparisons_say_no() {
    let t = tutorial(parity::TUTORIAL1);
    // Bytes: one byte changed, and one byte more.
    let poly = entry(&t, "temp/scene_mesh.poly");
    assert_eq!(byte_difference(&poly, &poly), None);
    let mut bent = poly.clone();
    bent[100] ^= 1;
    assert!(
        byte_difference(&bent, &poly)
            .unwrap()
            .contains("first difference at byte 100")
    );
    let mut longer = poly.clone();
    longer.push(b'\n');
    assert!(byte_difference(&longer, &poly).is_some());

    // TetGen's files: the trailer alone is ignored; a digit is a value; a tie printed the other
    // way is text only.
    let node = entry(&t, "temp/scene_mesh.1.node");
    let text = String::from_utf8(node.clone()).unwrap();
    let retrailed = text.replace("# Generated by", "# Generated by another tetgen.exe,");
    let d = tetgen_difference(retrailed.as_bytes(), &node);
    assert_eq!((d.text_lines, d.value_lines), (0, 0));
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    lines[1].push_str(" 9");
    let d = tetgen_difference(lines.join("\n").as_bytes(), &node);
    assert_eq!((d.text_lines, d.value_lines), (1, 1), "{d:?}");
    // Tutorial 2's first tie: 0.0977344512939453125 exactly, printed ...312 by ours and ...313
    // in 2019. Both are that f64; a digit further up is another number.
    let theirs_tie = b"1  0.097734451293945313 0 0\n";
    let d = tetgen_difference(b"1  0.097734451293945312 0 0\n", theirs_tie);
    assert_eq!(
        (d.text_lines, d.value_lines),
        (1, 0),
        "the same f64 printed two ways"
    );
    let d = tetgen_difference(b"1  0.097834451293945313 0 0\n", theirs_tie);
    assert_eq!((d.text_lines, d.value_lines), (1, 1), "a different number");

    // The .mbin: the room read through the map passes; without the map, and with one node moved,
    // it does not.
    let theirs = &t.runs[1].tetra_bytes;
    let mut ours = mbin::read(theirs).unwrap();
    for tet in &mut ours.tetrahedra {
        tet.id_volume = 0;
    }
    let ours_bytes = mbin::write(&ours);
    let map = BTreeMap::from([(1, 0)]);
    assert_eq!(mbin_difference(&ours_bytes, theirs, &map), None);
    let d = mbin_difference(&ours_bytes, theirs, &BTreeMap::new()).unwrap();
    assert!(d.contains("dump line"), "{d}");
    ours.nodes[5][1] = f32::from_bits(ours.nodes[5][1].to_bits() + 1);
    let d = mbin_difference(&mbin::write(&ours), theirs, &map).unwrap();
    assert!(d.contains("node"), "{d}");

    // config.xml: one value the solver reads, changed (the source's 1 kHz power one f32 step up).
    let r = &t.runs[1];
    let db = parity::attr_in(&r.config, "<bfreq freq=\"1000\" db=", "db");
    let bumped = parity::next_float_text(db);
    let edited = edit_attr(&r.config, "<bfreq freq=\"1000\" db=", "db", &bumped);
    assert_eq!(
        parity::solver_differences(&r.config, &r.config),
        Vec::<String>::new()
    );
    assert_eq!(parity::solver_differences(&r.config, &edited).len(), 1);

    // Results: the original's SPPS inputs run with seed 1 and with seed 2 differ, and the first
    // differing value is named; the same seed twice gives no difference. TCR draws no random
    // numbers: the source moved 0.5 m is the input that changes its results.
    let none = BTreeMap::new();
    let mut spps_run = None;
    for kind in [SolverKind::Spps, SolverKind::Tcr] {
        let r = t.runs.iter().find(|r| r.solver == kind).unwrap();
        let config = short_run(&r.config, kind);
        let changed = match kind {
            SolverKind::Spps => edit_attr(&config, "<simulation ", "random_seed", "2"),
            SolverKind::Tcr => {
                let x = parity::attr_in(&config, "<source ", "x");
                let moved = format!("{}", x.parse::<f64>().unwrap() + 0.5);
                edit_attr(&config, "<source ", "x", &moved)
            }
        };
        let name = solver_name(kind);
        let root = bed_dir(&format!("no-{name}"));
        let a = run(
            &root.join("a"),
            kind,
            &config,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        let b = run(
            &root.join("b"),
            kind,
            &config,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        assert_eq!(
            output_differences(&a, &b, &none),
            Vec::<String>::new(),
            "{name}: the same inputs twice"
        );
        let c = run(
            &root.join("c"),
            kind,
            &changed,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        let d = output_differences(&a, &c, &none);
        println!(
            "{name}, the input changed: {} files differ, first: {:?}",
            d.len(),
            d.first()
        );
        assert!(
            !d.is_empty(),
            "{name}: a changed input gave the same results"
        );
        assert!(
            d.iter()
                .all(|l| l.contains("dump line") || l.contains("byte") || l.contains("wrote it")),
            "{name}: each difference names its first value: {d:?}"
        );
        if kind == SolverKind::Spps {
            spps_run = Some(a);
        }
    }
    // A .csbin decoded: one energy one bit off is found, and the receiver id map is applied.
    let a = spps_run.unwrap();
    let bytes = a
        .iter()
        .find(|(k, _)| k.ends_with("Sound level.csbin"))
        .map(|(_, b)| b)
        .expect("a surface receiver file");
    let original = csbin::read(bytes).unwrap();
    assert_eq!(csbin_difference(original.clone(), &original, &none), None);
    let mut bent = original.clone();
    let face = bent.receivers[0]
        .faces
        .iter_mut()
        .find(|f| !f.records.is_empty())
        .unwrap();
    face.records[0].energy = f32::from_bits(face.records[0].energy.to_bits() ^ 1);
    let d = csbin_difference(original.clone(), &bent, &none).unwrap();
    assert!(d.starts_with("dump line"), "{d}");
    let index = original.receivers[0].xml_index;
    let mut renumbered = original.clone();
    renumbered.receivers[0].xml_index = index + 1000;
    assert!(csbin_difference(renumbered.clone(), &original, &none).is_some());
    let map = BTreeMap::from([(index + 1000, index)]);
    assert_eq!(csbin_difference(renumbered, &original, &map), None);

    // The shipped-solver spread: a difference among values far below the file's largest shows in
    // the ratio over every value and in f32 steps, where the floored ratio leaves it at 0.
    let mut s = Spread::default();
    s.file(&[(1000.0, 1000.0), (1e-3, 1e-3)]);
    assert_eq!((s.n, s.ulps), (0, 0));
    let mut s = Spread::default();
    s.file(&[
        (1000.0, 1000.0),
        (1e-3, f32::from_bits(1e-3f32.to_bits() + 12)),
    ]);
    assert_eq!((s.n, s.rel, s.ulps), (1, 0.0, 12), "{s:?}");
    // 12 steps of 2^-33 at 1e-3: 1.397e-6 relative.
    assert!(
        (s.rel_all - 12.0 * 2f64.powi(-33) / 1e-3).abs() < 1e-9,
        "{s:?}"
    );
}

// ---------------------------------------------------------------------------------------------
// Upstream's shipped 1.3.4 and 1.4.0 solvers against ours

/// How far two runs' numbers are apart, over every file both wrote. GABE float columns and `.csbin`
/// energies are compared value by value, per file; a file that does not decode counts as one
/// difference of NaN.
#[derive(Debug, Default)]
struct Spread {
    /// Values whose bits differ.
    n: usize,
    /// Of those, values that differ other than by a NaN's sign.
    numeric: usize,
    /// The largest absolute difference.
    abs: f64,
    /// The largest relative difference `|a - b| / max(|a|, |b|)` over every differing pair (a
    /// value against 0 counts 1).
    rel_all: f64,
    /// The same among values at least 1e-3 of their file's largest magnitude: near-zero intensity
    /// components give large ratios that say little. Both are reported, so a file whose
    /// differences all sit below that floor does not read as 0.
    rel: f64,
    /// The largest distance in `f32` steps between two finite values of the same sign.
    ulps: u32,
}

impl Spread {
    fn file(&mut self, pairs: &[(f32, f32)]) {
        let top = pairs
            .iter()
            .flat_map(|&(a, b)| [a, b])
            .filter(|v| v.is_finite())
            .fold(0f32, |m, v| m.max(v.abs()));
        for &(a32, b32) in pairs {
            if a32.to_bits() == b32.to_bits() {
                continue;
            }
            self.n += 1;
            if a32.is_nan() && b32.is_nan() {
                continue;
            }
            self.numeric += 1;
            if a32.is_finite()
                && b32.is_finite()
                && a32.is_sign_negative() == b32.is_sign_negative()
            {
                self.ulps = self.ulps.max(a32.to_bits().abs_diff(b32.to_bits()));
            }
            let (a, b) = (f64::from(a32), f64::from(b32));
            let d = (a - b).abs();
            self.abs = self.abs.max(d);
            let m = a.abs().max(b.abs());
            if m > 0.0 {
                self.rel_all = self.rel_all.max(d / m);
                if m >= 1e-3 * f64::from(top) {
                    self.rel = self.rel.max(d / m);
                }
            }
        }
    }
}

fn value_spread(theirs: &Outputs, ours: &Outputs) -> Spread {
    let mut s = Spread::default();
    for (k, t) in theirs {
        let Some(o) = ours.get(k) else { continue };
        if t == o {
            continue;
        }
        let mut pairs = Vec::new();
        if k.ends_with(".csbin") {
            if let (Ok(t), Ok(o)) = (csbin::read(t), csbin::read(o)) {
                for (rt, ro) in t.receivers.iter().zip(&o.receivers) {
                    for (ft, fo) in rt.faces.iter().zip(&ro.faces) {
                        for (a, b) in ft.records.iter().zip(fo.records.iter()) {
                            pairs.push((a.energy, b.energy));
                        }
                    }
                }
                s.file(&pairs);
                continue;
            }
        } else if let (Ok(t), Ok(o)) = (gabe::read(t), gabe::read(o)) {
            for (ct, co) in t.columns.iter().zip(&o.columns) {
                if let (
                    gabe::ColumnData::Float { values: vt, .. },
                    gabe::ColumnData::Float { values: vo, .. },
                ) = (&ct.data, &co.data)
                {
                    pairs.extend(vt.iter().copied().zip(vo.iter().copied()));
                }
            }
            s.file(&pairs);
            continue;
        }
        s.n += 1;
        s.numeric += 1;
        s.abs = f64::NAN;
        s.rel_all = f64::NAN;
    }
    s
}

/// Upstream's shipped solvers against ours, on tutorial 1's original inputs with the bed's edits
/// (seed 1, 10,000 particles, 500, 1000 and 2000 Hz): SPPS and TCR of v1.3.4 (2020-12-23, the last
/// stable release) and of v1.4.0 (2026-01-14, the pinned 929a5c8, whose sources ours are built
/// from). `$SIMPA_RELEASE_BINARIES` names the folder holding the installed releases,
/// `inst134\core\{spps,classical_theory}\` and `inst140\`: upstream's installers are not in this
/// repository, so this test is ignored in the plain suite and run by `tools/gates/parity.ps1`,
/// which passes the folder. It panics when the variable or a solver is missing.
///
/// The measured answer is in `docs/m5-m6-design.md`, decision 3.
#[test]
#[ignore = "needs upstream's installed 1.3.4 and 1.4.0 releases: tools/gates/parity.ps1 runs it with SIMPA_RELEASE_BINARIES"]
fn shipped_1_3_4_and_1_4_0_solvers_against_ours() {
    let root = std::env::var_os("SIMPA_RELEASE_BINARIES")
        .map(PathBuf::from)
        .expect("SIMPA_RELEASE_BINARIES must name the folder holding inst134 and inst140");
    let exe = |p: &str| {
        let p = root.join(p);
        assert!(p.is_file(), "{} is missing", p.display());
        p
    };
    let t = tutorial(parity::TUTORIAL1);
    let mut summary = Vec::new();
    for (kind, ours, v140, v134) in [
        (
            SolverKind::Spps,
            solver_exe("spps.exe"),
            exe("inst140/spps.exe"),
            exe("inst134/core/spps/spps.exe"),
        ),
        (
            SolverKind::Tcr,
            solver_exe("classicalTheory.exe"),
            exe("inst140/classicalTheory.exe"),
            exe("inst134/core/classical_theory/classicalTheory.exe"),
        ),
    ] {
        let r = t.runs.iter().find(|r| r.solver == kind).unwrap();
        let config = short_run(&r.config, kind);
        let name = solver_name(kind);
        let dir = bed_dir(&format!("shipped-{name}"));
        let mut runs: Vec<(&str, Outputs)> = Vec::new();
        for (label, program) in [("ours", &ours), ("1.4.0", &v140), ("1.3.4", &v134)] {
            let d = dir.join(label.replace('.', ""));
            std::fs::create_dir_all(&d).unwrap();
            let wd = simpa_core::config_xml::working_directory(&d).unwrap();
            std::fs::write(
                d.join("config.xml"),
                edit_attr(&config, "<configuration ", "workingdirectory", &wd),
            )
            .unwrap();
            std::fs::write(d.join("mesh.cbin"), &r.mesh_bytes).unwrap();
            std::fs::write(d.join("tetramesh.mbin"), &r.tetra_bytes).unwrap();
            let run = parity::support::run_solver(program, &d);
            println!(
                "{name} {label} ({}): exit {:?}",
                program.display(),
                run.exit
            );
            assert_eq!(
                run.exit,
                Some(0),
                "{name} {label}: {}\n{}",
                run.stdout,
                run.stderr
            );
            runs.push((
                label,
                parity::support::outputs(&d, &["config.xml", "mesh.cbin", "tetramesh.mbin"]),
            ));
        }
        for (a, b) in [(0, 1), (0, 2), (1, 2)] {
            let (la, oa) = &runs[a];
            let (lb, ob) = &runs[b];
            let d = output_differences(ob, oa, &BTreeMap::new());
            let s = value_spread(ob, oa);
            let same: Vec<&String> = oa.keys().filter(|k| oa.get(*k) == ob.get(*k)).collect();
            let line = format!(
                "{name}: {la} against {lb}: {} of {} files differ; {} values differ ({} other than \
                 by a NaN's sign), largest {:e} absolute, {:e} relative over every value, {:e} \
                 relative among values at least 1e-3 of their file's largest, {} f32 steps{}; \
                 identical: {same:?}",
                d.len(),
                oa.len().max(ob.len()),
                s.n,
                s.numeric,
                s.abs,
                s.rel_all,
                s.rel,
                s.ulps,
                if d.is_empty() {
                    String::new()
                } else {
                    format!("; first: {}", d[0])
                }
            );
            println!("{line}");
            for x in &d {
                println!("    {x}");
            }
            // Per file: how far apart, and for a surface receiver also each face's energy summed
            // over its time steps.
            for (k, t) in ob
                .iter()
                .filter(|(k, t)| oa.get(*k).is_some_and(|o| o != *t))
            {
                let one = BTreeMap::from([(k.clone(), t.clone())]);
                let other = BTreeMap::from([(k.clone(), oa[k].clone())]);
                let s = value_spread(&one, &other);
                let mut per_face = String::new();
                if k.ends_with(".csbin")
                    && let (Ok(x), Ok(y)) = (csbin::read(t), csbin::read(&oa[k]))
                {
                    let mut worst = 0f64;
                    for (rx, ry) in x.receivers.iter().zip(&y.receivers) {
                        for (fx, fy) in rx.faces.iter().zip(&ry.faces) {
                            let sx: f64 = fx.records.iter().map(|r| f64::from(r.energy)).sum();
                            let sy: f64 = fy.records.iter().map(|r| f64::from(r.energy)).sum();
                            let m = sx.abs().max(sy.abs());
                            if m > 0.0 {
                                worst = worst.max((sx - sy).abs() / m);
                            }
                        }
                    }
                    per_face = format!("; each face's energy summed over time: {worst:e} relative");
                }
                println!(
                    "      {k}: {} values differ, largest {:e} relative ({:e} among values at \
                     least 1e-3 of the file's largest), {} f32 steps, {:e} absolute{per_face}",
                    s.n, s.rel_all, s.rel, s.ulps, s.abs
                );
            }
            summary.push(line);
            if (a, b) == (0, 1) {
                // Ours is the pinned 929a5c8 sources built as upstream builds them: bit for bit.
                assert_eq!(
                    d,
                    Vec::<String>::new(),
                    "{name}: ours against the shipped 1.4.0"
                );
            } else {
                // 1.3.4 is another build of other sources: it must differ, or this bed cannot tell
                // two builds apart. How much is measured and reported.
                assert!(!d.is_empty(), "{name}: {la} against {lb}: bit-identical");
            }
        }
    }
    println!("\n{}", summary.join("\n"));
}
