//! The parity bed (`docs/m5-m6-design.md`, decision 3): our build against original I-Simpa on
//! upstream's three tutorials, from the `.proj` to the solvers' results.
//!
//! For each tutorial, through the built `simpa` as a user drives it:
//! 1. **Import** the `.proj` with `simpa import-proj`.
//! 2. **Mesh** it with `simpa mesh` (TetGen 1.5.0, the M1 build found through `common/paths.rs`:
//!    `$SIMPA_SOLVERS_DIR`, else the dev tree; a missing build panics, nothing skips).
//! 3. **Compare our inputs with the files original I-Simpa wrote** into the `.proj`: `.poly` and
//!    `.var` byte for byte; TetGen's `.1.{node,ele,face,neigh,edge}` byte for byte, the trailer
//!    (`# Generated by ...`, which names the program and folder) excluded; the `.mbin` byte for
//!    byte once each tetrahedron's `idVolume` is read through the id map (upstream writes TetGen's
//!    region attribute, 1 for a room, and its GUI's session ids for fittings; we write 0 and the
//!    project's ids, decision 1); `mesh.cbin` and `config.xml` as `crates/simpa-core/tests/
//!    parity_inputs.rs` defines equality (what the solver reads, value by value, with the ids and
//!    the listed differences by design), the helpers shared through `parity_support.rs`.
//! 4. **Run SPPS and TCR** (our M1 builds of upstream's 929a5c8 sources) on our inputs and on the
//!    original inputs, both edited alike: `random_seed` 1, 10,000 particles, and at most three
//!    computed bands (500, 1000 and 2000 Hz where a run computes more). Every output file must be
//!    the same: `.csbin` compared decoded (its struct padding is not deterministic, M1) with the
//!    surface receivers' `xmlIndex` read through the id map, every other file byte for byte, which
//!    makes `.gabe` and `.recp` values bit-exact. A difference names the file and its first
//!    differing value, from the canonical dump.
//!
//! What each tutorial holds decides what can be compared (`parity_inputs.rs::what_the_tutorials_hold`):
//! - **tutorial 1**: TetGen's files under `temp/` and two run folders (SPPS, TCR): everything;
//! - **tutorial 2**: TetGen's files under `temp/` (no `.var`: its project constrains no surface) and
//!   no run folder: the mesher's inputs and outputs only. There is no original `.mbin`, `.cbin`,
//!   `config.xml` or result to compare with;
//! - **tutorial 3**: TetGen's files under `temp/` and three SPPS run folders, but `simpa
//!   import-proj` refuses it: a `.proj`'s fitting zones are not imported. Checked as a refusal; the
//!   project is then taken from each run's `config.xml` and `mesh.cbin` with the two edits a
//!   project needs (`parity::importable`), saved, and driven through the same CLI.
//!
//! Every comparison has a refusal beside it, the input that makes it say no
//! (`the_comparisons_say_no`).

mod support;

// simpa-core's parity helpers, which bring their own copy of `common/paths.rs` (the CLI's `support`
// has one too): the same finder twice, by design.
#[allow(clippy::duplicate_mod)]
#[path = "../../simpa-core/tests/parity_support.rs"]
mod parity;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};

use parity::{Tutorial, edit_attr, entry, has_entry, tutorial};
use serde_json::Value;
use simpa_core::config_xml::SolverKind;
use simpa_core::formats::{cbin, csbin, gabe, mbin};
use support::{json, simpa_run, solver_exe};

// ---------------------------------------------------------------------------------------------
// Folders and CLI calls

/// A new folder under `<repo>/target/parity-bed/`, short enough that the deepest solver output
/// stays well under Windows' 260-character path limit (a longer path is skipped by the solvers
/// with exit 0 and no message, `config_xml_solver.rs`). Never reused, never deleted.
fn bed_dir(label: &str) -> PathBuf {
    static N: AtomicUsize = AtomicUsize::new(0);
    let dir = support::paths::repo_root()
        .join("target/parity-bed")
        .join(format!(
            "{}-{}-{label}",
            std::process::id(),
            N.fetch_add(1, Ordering::SeqCst)
        ));
    std::fs::create_dir_all(&dir).unwrap();
    let deepest = dir.as_os_str().len()
        + "/Punctual receivers/Receiver 1/Punctual receiver intensity.gabe".len();
    assert!(deepest < 240, "{} is too deep for MAX_PATH", dir.display());
    dir
}

/// `simpa import-proj <tutorial> <dir>/project.simpa`: must exit 0.
fn import_proj(rel: &str, dir: &Path) -> PathBuf {
    let proj = support::paths::upstream_file(rel);
    let out = dir.join("project.simpa");
    let o = simpa_run(&[
        "import-proj".to_string(),
        proj.display().to_string(),
        out.display().to_string(),
    ]);
    assert_eq!(o.code, 0, "import-proj {rel}: {o:#?}");
    out
}

/// `simpa mesh <project> --out <dir> --json`: must exit 0 with status OK.
fn mesh(project: &Path, out: &Path) -> Value {
    let o = simpa_run(&[
        "mesh".to_string(),
        project.display().to_string(),
        "--out".into(),
        out.display().to_string(),
        "--json".into(),
    ]);
    assert_eq!(o.code, 0, "simpa mesh {}: {o:#?}", project.display());
    let m = json(&o);
    assert_eq!(m["status"], "OK", "{m:#}");
    m
}

/// `simpa export-config <project> <dir> --solver <kind>`: our `config.xml` and `mesh.cbin`.
fn export_config(project: &Path, dir: &Path, kind: SolverKind) -> (String, Vec<u8>) {
    let o = simpa_run(&[
        "export-config".to_string(),
        project.display().to_string(),
        dir.display().to_string(),
        "--solver".into(),
        solver_name(kind).into(),
    ]);
    assert_eq!(o.code, 0, "export-config: {o:#?}");
    (
        std::fs::read_to_string(dir.join("config.xml")).unwrap(),
        std::fs::read(dir.join("mesh.cbin")).unwrap(),
    )
}

fn solver_name(kind: SolverKind) -> &'static str {
    match kind {
        SolverKind::Spps => "spps",
        SolverKind::Tcr => "tcr",
    }
}

// ---------------------------------------------------------------------------------------------
// The comparisons

/// The first difference between two files' bytes: `None` when they are equal.
fn byte_difference(ours: &[u8], theirs: &[u8]) -> Option<String> {
    if ours == theirs {
        return None;
    }
    let at = ours
        .iter()
        .zip(theirs)
        .position(|(a, b)| a != b)
        .unwrap_or(ours.len().min(theirs.len()));
    Some(format!(
        "{} bytes against the original's {}; first difference at byte {at}: ours {:?}, the \
         original's {:?}",
        ours.len(),
        theirs.len(),
        ours.get(at),
        theirs.get(at)
    ))
}

/// TetGen's `.1.*` files compared line by line, the trailer (`# Generated by ...`) excluded.
#[derive(Debug, Default)]
struct TetgenDiff {
    /// Lines whose text differs.
    text_lines: usize,
    /// Of those, lines whose values differ: a token that is not the same number (as `f64`) or not
    /// the same word, or a line one file lacks.
    value_lines: usize,
    /// The first line whose values differ.
    first_value: Option<String>,
    /// The first line whose text differs.
    first_text: Option<String>,
}

fn is_trailer(line: &str) -> bool {
    line.starts_with("# Generated by ")
}

fn tetgen_difference(ours: &[u8], theirs: &[u8]) -> TetgenDiff {
    let lines = |b: &[u8]| -> Vec<String> {
        String::from_utf8_lossy(b)
            .lines()
            .filter(|l| !is_trailer(l))
            .map(str::to_string)
            .collect()
    };
    let (o, t) = (lines(ours), lines(theirs));
    let mut d = TetgenDiff::default();
    let same_values = |a: &str, b: &str| {
        let (x, y): (Vec<&str>, Vec<&str>) = (
            a.split_whitespace().collect(),
            b.split_whitespace().collect(),
        );
        x.len() == y.len()
            && x.iter().zip(&y).all(|(p, q)| {
                p == q
                    || matches!((p.parse::<f64>(), q.parse::<f64>()), (Ok(u), Ok(v)) if u.to_bits() == v.to_bits())
            })
    };
    for k in 0..o.len().max(t.len()) {
        let (a, b) = (o.get(k), t.get(k));
        if a == b {
            continue;
        }
        d.text_lines += 1;
        let line = format!(
            "line {}: ours {:?}, the original's {:?}",
            k + 1,
            a.map(String::as_str).unwrap_or("(none)"),
            b.map(String::as_str).unwrap_or("(none)")
        );
        if d.first_text.is_none() {
            d.first_text = Some(line.clone());
        }
        let equal = matches!((a, b), (Some(a), Some(b)) if same_values(a, b));
        if !equal {
            d.value_lines += 1;
            if d.first_value.is_none() {
                d.first_value = Some(line);
            }
        }
    }
    d
}

/// Our `.mbin` against the original's, byte for byte, once each of the original's tetrahedra has
/// its `idVolume` read through `ids` (the original's id to ours; an id missing from the map is
/// left as it is, so it shows). The original is decoded and written again by our writer, which
/// must give back its exact bytes first.
fn mbin_difference(ours: &[u8], theirs: &[u8], ids: &BTreeMap<i32, i32>) -> Option<String> {
    let mut t = match mbin::read(theirs) {
        Ok(m) => m,
        Err(e) => return Some(format!("the original does not read: {e}")),
    };
    if mbin::write(&t) != theirs {
        return Some("the original does not survive a read and a write".to_string());
    }
    for tet in &mut t.tetrahedra {
        if let Some(&o) = ids.get(&tet.id_volume) {
            tet.id_volume = o;
        }
    }
    let mapped = mbin::write(&t);
    if mapped == ours {
        return None;
    }
    // Name the first differing value from the canonical dumps.
    let dump_ours = match mbin::read(ours) {
        Ok(m) => mbin::dump(&m),
        Err(e) => return Some(format!("ours does not read: {e}")),
    };
    Some(
        first_dump_difference(&dump_ours, &mbin::dump(&t))
            .unwrap_or_else(|| byte_difference(ours, &mapped).unwrap_or_default()),
    )
}

/// The first line where two canonical dumps differ.
fn first_dump_difference(ours: &str, theirs: &str) -> Option<String> {
    let (o, t): (Vec<&str>, Vec<&str>) = (ours.lines().collect(), theirs.lines().collect());
    (0..o.len().max(t.len())).find_map(|k| {
        let (a, b) = (o.get(k), t.get(k));
        (a != b).then(|| {
            format!(
                "dump line {}: ours `{}`, the original's `{}`",
                k + 1,
                a.unwrap_or(&"(none)"),
                b.unwrap_or(&"(none)")
            )
        })
    })
}

/// The output files of one run, by path relative to its folder.
type Outputs = BTreeMap<String, Vec<u8>>;

/// Every difference between the original's run and ours, one line per file: a file only one run
/// wrote, or the first value that differs. A `.csbin` is compared decoded, the original's
/// receivers' `xmlIndex` read through `rs_ids`; every other file byte for byte, its first
/// differing value named from the GABE dump when it reads as one.
fn output_differences(
    theirs: &Outputs,
    ours: &Outputs,
    rs_ids: &BTreeMap<i32, i32>,
) -> Vec<String> {
    let mut out = Vec::new();
    for k in theirs.keys().filter(|k| !ours.contains_key(*k)) {
        out.push(format!("{k}: only the original's run wrote it"));
    }
    for k in ours.keys().filter(|k| !theirs.contains_key(*k)) {
        out.push(format!("{k}: only our run wrote it"));
    }
    for (k, t) in theirs {
        let Some(o) = ours.get(k) else { continue };
        let found = if k.ends_with(".csbin") {
            match (csbin::read(t), csbin::read(o)) {
                (Ok(t), Ok(o)) => csbin_difference(t, &o, rs_ids),
                (t, o) => Some(format!(
                    "does not decode: original {:?}, ours {:?}",
                    t.err(),
                    o.err()
                )),
            }
        } else if t == o {
            None
        } else {
            match (gabe::read(t), gabe::read(o)) {
                (Ok(t), Ok(o)) => first_dump_difference(&gabe::dump(&o), &gabe::dump(&t)),
                _ => byte_difference(o, t),
            }
            .or_else(|| byte_difference(o, t))
        };
        if let Some(d) = found {
            out.push(format!("{k}: {d}"));
        }
    }
    out.sort();
    out
}

/// Two decoded `.csbin`, the original's receivers' `xmlIndex` read through `rs_ids` first: the
/// first line where their canonical dumps differ (every value in hexadecimal, so bit for bit).
fn csbin_difference(
    mut theirs: csbin::Csbin,
    ours: &csbin::Csbin,
    rs_ids: &BTreeMap<i32, i32>,
) -> Option<String> {
    for r in &mut theirs.receivers {
        r.xml_index = *rs_ids.get(&r.xml_index).unwrap_or(&r.xml_index);
    }
    first_dump_difference(&csbin::dump(ours), &csbin::dump(&theirs))
}

// ---------------------------------------------------------------------------------------------
// Runs

/// The same edits on the original's `config.xml` and ours: `parity::repeatable` (SPPS: seed 1,
/// 10,000 particles) and at most three computed bands, 500, 1000 and 2000 Hz, when the config
/// computes more.
fn short_run(config: &str, kind: SolverKind) -> String {
    let text = parity::repeatable(config, kind);
    let doc = roxmltree::Document::parse(&text).unwrap();
    let computed: Vec<String> = doc
        .descendants()
        .filter(|n| {
            n.has_tag_name("bfreq") && n.parent().is_some_and(|p| p.has_tag_name("freq_enum"))
        })
        .filter(|n| n.attribute("docalc") == Some("1"))
        .map(|n| n.attribute("freq").unwrap().to_string())
        .collect();
    drop(doc);
    if computed.len() <= 3 {
        return text;
    }
    let keep = ["500", "1000", "2000"];
    assert!(
        keep.iter().all(|f| computed.iter().any(|c| c == f)),
        "{computed:?}"
    );
    let mut out = text;
    for f in computed.iter().filter(|f| !keep.contains(&f.as_str())) {
        let from = format!("<bfreq freq=\"{f}\" docalc=\"1\"/>");
        let to = format!("<bfreq freq=\"{f}\" docalc=\"0\"/>");
        assert_eq!(out.matches(&from).count(), 1, "{from}");
        out = out.replace(&from, &to);
    }
    out
}

/// Runs `kind` (our M1 build) in the new folder `dir` on `config` (its working directory set to
/// that folder), the scene mesh `cbin` and the tetrahedral mesh `mbin`. It must exit 0 and print
/// its completion line. Returns its output files.
fn run(dir: &Path, kind: SolverKind, config: &str, cbin: &[u8], mbin: &[u8]) -> Outputs {
    std::fs::create_dir_all(dir).unwrap();
    let wd = simpa_core::config_xml::working_directory(dir).unwrap();
    let text = edit_attr(config, "<configuration ", "workingdirectory", &wd);
    std::fs::write(dir.join("config.xml"), text).unwrap();
    std::fs::write(dir.join("mesh.cbin"), cbin).unwrap();
    std::fs::write(dir.join("tetramesh.mbin"), mbin).unwrap();
    let exe = solver_exe(match kind {
        SolverKind::Spps => "spps.exe",
        SolverKind::Tcr => "classicalTheory.exe",
    });
    let r = parity::support::run_solver(&exe, dir);
    assert_eq!(r.exit, Some(0), "{}: {}", dir.display(), r.stderr);
    let done = match kind {
        SolverKind::Spps => "End of calculation.",
        SolverKind::Tcr => "Step 3/3",
    };
    assert!(r.has_line(done), "{}:\n{}", dir.display(), r.stdout);
    parity::support::outputs(dir, &["config.xml", "mesh.cbin", "tetramesh.mbin"])
}

/// The original's run and ours on the same edits: the output differences, and how many files each
/// wrote. Their `.csbin` receiver ids are read through `rs_ids`.
#[allow(clippy::too_many_arguments)]
fn same_seed(
    label: &str,
    kind: SolverKind,
    original: (&str, &[u8], &[u8]),
    ours: (&str, &[u8], &[u8]),
    rs_ids: &BTreeMap<i32, i32>,
) -> (Outputs, Vec<String>) {
    let root = bed_dir(label);
    let theirs = run(
        &root.join("original"),
        kind,
        &short_run(original.0, kind),
        original.1,
        original.2,
    );
    let mine = run(
        &root.join("ours"),
        kind,
        &short_run(ours.0, kind),
        ours.1,
        ours.2,
    );
    assert!(
        !theirs.is_empty(),
        "{label}: the original's run wrote nothing"
    );
    let d = output_differences(&theirs, &mine, rs_ids);
    println!(
        "{label}: {} output files from the original's inputs, {} from ours; {} differ{}",
        theirs.len(),
        mine.len(),
        d.len(),
        if d.is_empty() {
            String::new()
        } else {
            format!(":\n  {}", d.join("\n  "))
        }
    );
    (theirs, d)
}

// ---------------------------------------------------------------------------------------------
// The mesher's files

/// The TetGen output files a mesh folder holds.
const TETGEN_FILES: [&str; 5] = ["node", "ele", "face", "neigh", "edge"];

/// Lines of a tutorial's files that differ from ours in text only: a coordinate at an exact decimal
/// tie in the 17th significant digit, printed rounded to even by ours and up by the 2019 build
/// (see [`TUTORIAL2_TIES`]). `(.poly lines, .1.node lines)`.
type Ties = (usize, usize);

/// Our `name` against the original's, line by line: no line may differ in value, and exactly
/// `text_only` lines may differ in text. One line for the summary; panics otherwise, naming the
/// first line that differs.
fn compare_text(name: &str, ours: &[u8], theirs: &[u8], text_only: usize, label: &str) -> String {
    let d = tetgen_difference(ours, theirs);
    assert_eq!(d.value_lines, 0, "{label}: {name}: {:?}", d.first_value);
    assert_eq!(
        d.text_lines, text_only,
        "{label}: {name}: {} lines differ in text, {text_only} expected; first {:?}",
        d.text_lines, d.first_text
    );
    if d.text_lines == 0 {
        format!("{name}: byte-identical, trailer excluded")
    } else {
        format!(
            "{name}: {} lines differ in text only, every value equal as f64 (first {})",
            d.text_lines,
            d.first_text.unwrap()
        )
    }
}

/// Our mesh folder's `.poly`, `.var` and `.1.*` against a tutorial's `temp/`, with the lines
/// expected to differ in text only. Returns one line per file, for the summary; panics on any
/// other difference, naming it.
fn compare_mesher_files(t: &Tutorial, mesh_dir: &Path, ties: Ties, label: &str) -> Vec<String> {
    let mut report = Vec::new();
    let ours = |name: &str| {
        std::fs::read(mesh_dir.join(name)).unwrap_or_else(|e| panic!("{label}: {name}: {e}"))
    };
    // The .poly, which has no trailer: byte for byte but the ties.
    report.push(compare_text(
        "scene_mesh.poly",
        &ours("scene_mesh.poly"),
        &entry(t, "temp/scene_mesh.poly"),
        ties.0,
        label,
    ));
    if ties.0 == 0 {
        assert_eq!(
            byte_difference(&ours("scene_mesh.poly"), &entry(t, "temp/scene_mesh.poly")),
            None,
            "{label}: scene_mesh.poly"
        );
    }
    // The .var, byte for byte, or absent on both sides.
    let var_theirs = has_entry(t, "temp/scene_mesh.var");
    let var_ours = mesh_dir.join("scene_mesh.var").is_file();
    assert_eq!(var_ours, var_theirs, "{label}: a .var on one side only");
    if var_theirs {
        let var = byte_difference(&ours("scene_mesh.var"), &entry(t, "temp/scene_mesh.var"));
        assert_eq!(var, None, "{label}: scene_mesh.var");
        report.push("scene_mesh.var: byte-identical".to_string());
    } else {
        report.push("scene_mesh.var: none written, as the original wrote none".to_string());
    }
    // TetGen's output, trailer excluded.
    for ext in TETGEN_FILES {
        let name = format!("scene_mesh.1.{ext}");
        let text_only = if ext == "node" { ties.1 } else { 0 };
        report.push(compare_text(
            &name,
            &ours(&name),
            &entry(t, &format!("temp/{name}")),
            text_only,
            label,
        ));
    }
    report
}

/// The original's `idVolume` to ours: every id of the original's `.mbin` that is not one of its
/// config's fittings is the room's (TetGen's attribute for an unseeded region), which we write 0;
/// the fittings map through the configs' `encombrement` lists.
fn volume_ids(theirs_mbin: &[u8], theirs_config: &str, ours_config: &str) -> BTreeMap<i32, i32> {
    let fittings = parity::id_map(theirs_config, ours_config, "encombrement");
    let ids: BTreeSet<i32> = mbin::read(theirs_mbin)
        .unwrap()
        .tetrahedra
        .iter()
        .map(|t| t.id_volume)
        .collect();
    ids.into_iter()
        .map(|id| (id, *fittings.get(&id).unwrap_or(&0)))
        .collect()
}

fn print_report(label: &str, report: &[String]) {
    println!("{label}:");
    for r in report {
        println!("  {r}");
    }
}

// ---------------------------------------------------------------------------------------------
// Tutorial 1

/// Tutorial 1 (the 6 x 10 x 3 m box, one source, two point receivers, the floor a surface receiver
/// constrained to 0.1 m²): every input equal to original I-Simpa's, and every result of a same-seed
/// SPPS run and TCR run on our inputs equal to those on the original's.
#[test]
fn tutorial_1() {
    let t = tutorial(parity::TUTORIAL1);
    let dir = bed_dir("t1");
    let project = import_proj(parity::TUTORIAL1, &dir);
    let mesh_dir = dir.join("mesh");
    let m = mesh(&project, &mesh_dir);
    assert_eq!(
        m["tetgen"]["argv"],
        serde_json::json!(["-pq2", "-A", "-n", "scene_mesh.poly"]),
        "the original's flags, from the .proj's SPPS meshing settings"
    );
    let mut report = compare_mesher_files(&t, &mesh_dir, (0, 0), "tutorial 1");
    let our_mbin = std::fs::read(mesh_dir.join("tetramesh.mbin")).unwrap();

    assert_eq!(t.runs.len(), 2);
    for r in &t.runs {
        let kind = r.solver;
        let name = solver_name(kind);
        let (our_config, our_cbin) =
            export_config(&project, &dir.join(format!("export-{name}")), kind);

        // The .mbin, through the id map.
        let ids = volume_ids(&r.tetra_bytes, &r.config, &our_config);
        assert_eq!(ids, BTreeMap::from([(1, 0)]), "the room: TetGen's 1, our 0");
        assert_eq!(
            mbin_difference(&our_mbin, &r.tetra_bytes, &ids),
            None,
            "{name}: tetramesh.mbin"
        );
        report.push(format!(
            "{name} tetramesh.mbin: byte-identical once idVolume is read through {ids:?} ({} bytes)",
            our_mbin.len()
        ));

        // config.xml and mesh.cbin as parity_inputs.rs defines them; our working directory is our
        // export folder.
        let got = parity::solver_differences(&r.config, &our_config);
        let mut expected = parity::by_design(kind);
        expected.extend(parity::tutorial1_ids());
        expected.extend(parity::tutorial1_directions());
        expected.push(format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&r.config),
            parity::working_folder(&our_config)
        ));
        assert_eq!(got, parity::sorted(expected), "{name}: config.xml");
        report.push(format!(
            "{name} config.xml: every value the solver reads is the original's, but the ids, the \
             stored receiver directions and the differences by design ({} lines, as parity_inputs.rs)",
            got.len()
        ));
        let rs = parity::id_map(&r.config, &our_config, "recepteur_surfacique");
        let en = parity::id_map(&r.config, &our_config, "encombrement");
        let faces = parity::face_differences(&r.mesh, &cbin::read(&our_cbin).unwrap(), &rs, &en);
        assert_eq!(faces, Vec::<String>::new(), "{name}: mesh.cbin");
        report.push(format!(
            "{name} mesh.cbin: every face's corners (f32 bits), idMat, idRs and idEn the original's \
             (ids through {rs:?}); our {} bytes weld the original's 36 vertices into 8",
            our_cbin.len()
        ));

        // The same-seed runs.
        let (theirs, d) = same_seed(
            &format!("t1-{name}"),
            kind,
            (&r.config, &r.mesh_bytes, &r.tetra_bytes),
            (&our_config, &our_cbin, &our_mbin),
            &rs,
        );
        if kind == SolverKind::Tcr {
            assert_eq!(d, Vec::<String>::new(), "{name}: results");
            report.push(format!(
                "{name} same-seed run: all {} output files equal to the original inputs' run",
                theirs.len()
            ));
            continue;
        }
        // SPPS: the receivers' stored directions (parity::tutorial1_directions) reach each point
        // receiver's `Advanced sound level.gap`, in the last bits; nothing else differs. The
        // proof: our config with the run's own directions gives the original's results exactly.
        let files: Vec<&str> = d.iter().map(|l| l.split(": ").next().unwrap()).collect();
        assert_eq!(
            files,
            [
                "Punctual receivers/Receiver 1/Advanced sound level.gap",
                "Punctual receivers/Receiver 2/Advanced sound level.gap"
            ],
            "{name}: results: {d:#?}"
        );
        let with_run_directions = directions_of(&our_config, &r.config);
        let (_, d2) = same_seed(
            &format!("t1-{name}-dirs"),
            kind,
            (&r.config, &r.mesh_bytes, &r.tetra_bytes),
            (&with_run_directions, &our_cbin, &our_mbin),
            &rs,
        );
        assert_eq!(
            d2,
            Vec::<String>::new(),
            "{name}: results with the run's receiver directions"
        );
        report.push(format!(
            "{name} same-seed run: {} of {} output files equal to the original inputs' run; the 2 \
             `Advanced sound level.gap` differ in the last bits (first: {}), from the receiver \
             directions the .proj stores with 6 digits: with the run's own directions, all {} equal",
            theirs.len() - d.len(),
            theirs.len(),
            d[0],
            theirs.len()
        ));
    }
    print_report("tutorial 1", &report);
}

/// `ours` with each point receiver's direction (`u`, `v`, `w`) replaced by `theirs`'s, receiver by
/// receiver in list order: the directions upstream's GUI held when it wrote the run, which its
/// project file keeps only to 6 significant digits.
fn directions_of(ours: &str, theirs: &str) -> String {
    let doc = roxmltree::Document::parse(theirs).unwrap();
    let stored: Vec<[String; 3]> = doc
        .descendants()
        .filter(|n| n.has_tag_name("recepteur_ponctuel"))
        .map(|n| ["u", "v", "w"].map(|a| n.attribute(a).unwrap().to_string()))
        .collect();
    let tag = "<recepteur_ponctuel ";
    assert_eq!(ours.matches(tag).count(), stored.len());
    let mut out = String::new();
    let mut rest = ours;
    for uvw in &stored {
        let at = rest.find(tag).unwrap();
        out.push_str(&rest[..at]);
        let end = at + rest[at..].find('>').unwrap() + 1;
        let mut element = rest[at..end].to_string();
        for (a, v) in ["u", "v", "w"].iter().zip(uvw) {
            element = edit_attr(&element, tag, a, v);
        }
        out.push_str(&element);
        rest = &rest[end..];
    }
    out.push_str(rest);
    out
}

// ---------------------------------------------------------------------------------------------
// Tutorial 2

/// The lines of tutorial 2 whose text differs from the original's while every value is equal:
/// coordinates at an exact decimal tie in the 17th significant digit (the first is
/// 0.0977344512939453125, `...312` in ours, `...313` in 2019's). Programs built with Visual Studio
/// 2019 16.2 or later print such a tie rounded to even through the UCRT's `printf`, older ones
/// round it up. Our `.poly` writer rounds to even as a present build of upstream's GUI would, in
/// 307 lines of the `.poly`; TetGen 1.5.0, built as upstream's 929a5c8 builds it, in 1,036 lines
/// of the `.1.node`. Upstream's own 1.3.4 `tetgen.exe` prints the `.node` as ours does, its 1.3.3
/// as the 2019 file does (`third_party/tetgen-1.5.0/PROVENANCE.md`). TetGen reads the `.poly`, and
/// the `.mbin` builder the `.node`, as the same `f64` either way.
const TUTORIAL2_TIES: Ties = (307, 1036);

/// Tutorial 2 (the Elmia hall, 7,860 faces): the mesher's inputs and TetGen's output equal to
/// original I-Simpa's. It holds no run folder, so there is no original `.mbin`, `.cbin`,
/// `config.xml` or result to compare: said, not skipped.
#[test]
fn tutorial_2() {
    let t = tutorial(parity::TUTORIAL2);
    assert!(
        t.runs.is_empty(),
        "tutorial 2 now holds run folders: compare them"
    );
    let dir = bed_dir("t2");
    let project = import_proj(parity::TUTORIAL2, &dir);
    let mesh_dir = dir.join("mesh");
    let m = mesh(&project, &mesh_dir);
    println!("tutorial 2: TetGen argv {}", m["tetgen"]["argv"]);
    let mut report = compare_mesher_files(&t, &mesh_dir, TUTORIAL2_TIES, "tutorial 2");
    report.push(
        "tetramesh.mbin, mesh.cbin, config.xml, results: the .proj holds no run folder, so no \
         original to compare with"
            .to_string(),
    );
    print_report("tutorial 2", &report);
}

// ---------------------------------------------------------------------------------------------
// Tutorial 3

/// Tutorial 3 made ready for the bed: the `.proj`, each run's project (from its `config.xml` and
/// `mesh.cbin` with `parity::importable`'s two edits, saved as `.simpa`), and the `.mbin` our TetGen
/// and our builder make of upstream's own `.poly` (see [`tutorial_3`] for why that `.poly`).
struct Tutorial3 {
    t: Tutorial,
    dir: PathBuf,
    projects: Vec<PathBuf>,
    /// Our `.mbin` with TetGen's region attributes as they came (upstream's ids).
    built: mbin::Mesh,
    report: Vec<String>,
}

fn tutorial3(label: &str) -> Tutorial3 {
    let t = tutorial(parity::TUTORIAL3);
    let dir = bed_dir(label);
    assert_eq!(t.runs.len(), 3);
    let projects: Vec<PathBuf> = t
        .runs
        .iter()
        .enumerate()
        .map(|(i, r)| {
            let project = simpa_core::config_xml::import_upstream_with_mesh(
                &parity::importable(&r.config),
                &r.mesh,
            )
            .unwrap_or_else(|e| panic!("run {i}: {e}"));
            let path = dir.join(format!("run{i}.simpa"));
            simpa_core::schema::save(&project, &path).unwrap();
            path
        })
        .collect();
    let mut report = Vec::new();

    // TetGen 1.5.0 (ours) on upstream's own .poly, with the flags its trailer records.
    let tg = dir.join("tetgen");
    std::fs::create_dir_all(&tg).unwrap();
    std::fs::write(
        tg.join("scene_mesh.poly"),
        entry(&t, "temp/scene_mesh.poly"),
    )
    .unwrap();
    let trailer = String::from_utf8(entry(&t, "temp/scene_mesh.1.face")).unwrap();
    let call = simpa_core::mesh::trailer_command(&trailer).expect("a trailer");
    assert_eq!(call.flags, ["-pq2", "-A", "-n"]);
    let ran = std::process::Command::new(solver_exe("tetgen.exe"))
        .args(&call.flags)
        .arg("scene_mesh.poly")
        .current_dir(&tg)
        .output()
        .unwrap();
    assert_eq!(
        ran.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&ran.stdout)
    );
    for ext in TETGEN_FILES {
        let name = format!("scene_mesh.1.{ext}");
        let ours = std::fs::read(tg.join(&name)).unwrap();
        report.push(format!(
            "{} (our TetGen on upstream's .poly)",
            compare_text(
                &name,
                &ours,
                &entry(&t, &format!("temp/{name}")),
                0,
                "tutorial 3"
            )
        ));
    }
    // Our builder on our TetGen's output, in the frame of the project's scene, told the region
    // attributes TetGen gave: upstream's ids, 1930 and 2083 seeded, 2084 to 2086 the room's parts.
    let out = simpa_core::mesh::TetgenOutput::read(&simpa_core::mesh::OutputPaths::new(
        &tg,
        "scene_mesh",
    ))
    .unwrap();
    let attributes: BTreeSet<i32> = (0..out.ele.len())
        .map(|k| *out.ele.tet_attributes(k).last().unwrap() as i32)
        .collect();
    let attributes: Vec<i32> = attributes.into_iter().collect();
    assert_eq!(attributes, [1930, 2083, 2084, 2085, 2086]);
    let project = simpa_core::schema::load(&projects[2]).unwrap();
    let scene = simpa_core::config_xml::scene_mesh(&project).unwrap();
    let unitize = simpa_core::mesh::Unitize::of_scene(&scene).unwrap();
    let (built, _) =
        simpa_core::mesh::build_mbin(&out, scene.faces.len(), &attributes, &unitize).unwrap();
    Tutorial3 {
        t,
        dir,
        projects,
        built,
        report,
    }
}

/// Our `.mbin` for tutorial 3's run `r` and our `config`: [`Tutorial3::built`] with the fittings
/// under our ids, and the room's parts as `room` gives them.
fn tutorial3_mbin(
    built: &mbin::Mesh,
    r: &parity::Run,
    our_config: &str,
    room: impl Fn(i32) -> i32,
) -> (Vec<u8>, BTreeMap<i32, i32>) {
    let fittings = parity::id_map(&r.config, our_config, "encombrement");
    let mut ids = BTreeMap::new();
    let mut mesh = built.clone();
    for tet in &mut mesh.tetrahedra {
        let to = fittings
            .get(&tet.id_volume)
            .copied()
            .unwrap_or_else(|| room(tet.id_volume));
        ids.insert(tet.id_volume, to);
        tet.id_volume = to;
    }
    (mbin::write(&mesh), ids)
}

/// Tutorial 3 (a room with two fitting zones, six sources, five point receivers and a cutting
/// plane), its inputs. What our pipeline cannot do with it, measured and said:
/// - `simpa import-proj` refuses it: a `.proj`'s fitting zones are not imported. Each run's project
///   is taken from its `config.xml` and `mesh.cbin` instead ([`tutorial3`]);
/// - `simpa mesh` refuses that project: our geometry check finds its scene self-intersecting and
///   open, where upstream's GUI took its `.poly` through `preprocess.exe` (the mesh settings'
///   "preprocess", `projet_maillage.cpp:206-213`), which merges vertices and splits faces: its
///   `temp/scene_mesh.poly` has 133 facets for the run's 100 faces. Our own `.poly` of the project,
///   taken through our build of `preprocess.exe`, is not upstream's either (measured below).
///
/// So the mesher's `.poly` is upstream's own here, and what is compared is what comes after it:
/// our TetGen's `.1.*` against `temp/`, our builder's `.mbin` against each run's, and our
/// `config.xml` and `mesh.cbin` against each run's, as for tutorial 1.
#[test]
fn tutorial_3() {
    let Tutorial3 {
        t,
        dir,
        projects,
        built,
        report: made,
    } = tutorial3("t3");
    // The refusals, as a user meets them.
    let o = simpa_run(&[
        "import-proj".to_string(),
        support::paths::upstream_file(parity::TUTORIAL3)
            .display()
            .to_string(),
        dir.join("refused.simpa").display().to_string(),
    ]);
    assert_eq!(o.code, 2, "{o:#?}");
    assert!(
        o.stderr
            .contains("fitting zones and volumes are not imported from a .proj"),
        "{}",
        o.stderr
    );
    let mut report = vec![
        "import-proj: refused (exit 2): fitting zones are not imported from a .proj".to_string(),
    ];
    let last = t.runs.len() - 1;
    let o = simpa_run(&[
        "mesh".to_string(),
        projects[last].display().to_string(),
        "--out".into(),
        dir.join("refused-mesh").display().to_string(),
    ]);
    assert_eq!(o.code, 3, "{o:#?}");
    let refused: Vec<&str> = o
        .stderr
        .lines()
        .filter_map(|l| l.strip_prefix("refused ").and_then(|l| l.split(':').next()))
        .collect();
    assert_eq!(
        refused,
        ["self_intersections", "open_boundary", "unresolved_topology"],
        "{}",
        o.stderr
    );
    report.push(format!(
        "simpa mesh: refused by our geometry check (exit 3: {})",
        refused.join(", ")
    ));

    // Upstream's .poly against ours, and ours through preprocess.exe.
    let theirs_poly = entry(&t, "temp/scene_mesh.poly");
    let theirs_model = simpa_core::formats::poly::read(&theirs_poly).unwrap();
    let project = simpa_core::schema::load(&projects[last]).unwrap();
    let input = simpa_core::mesh::project_input(&project).unwrap();
    assert_eq!(
        (
            theirs_model.model_vertices.len(),
            theirs_model.model_faces.len()
        ),
        (57, 133)
    );
    assert_eq!(t.runs[last].mesh.faces.len(), 100);
    let pre = dir.join("preprocess");
    std::fs::create_dir_all(&pre).unwrap();
    std::fs::write(
        pre.join("scene_mesh.poly"),
        simpa_core::formats::poly::write(&input.poly),
    )
    .unwrap();
    let ran = std::process::Command::new(solver_exe("preprocess.exe"))
        .arg("scene_mesh.poly")
        .current_dir(&pre)
        .output()
        .unwrap();
    assert_eq!(ran.status.code(), Some(0));
    let after = simpa_core::formats::poly::read_file(&pre.join("scene_mesh.poly")).unwrap();
    let stdout = String::from_utf8_lossy(&ran.stdout);
    let status: Vec<&str> = stdout
        .lines()
        .filter(|l| l.contains(" : "))
        .map(str::trim)
        .collect();
    report.push(format!(
        "upstream's temp/scene_mesh.poly: {} vertices, {} facets for the run's 100 .cbin faces; \
         ours: {} vertices, {} facets; ours through our preprocess.exe: {} vertices, {} facets ({})",
        theirs_model.model_vertices.len(),
        theirs_model.model_faces.len(),
        input.poly.model_vertices.len(),
        input.poly.model_faces.len(),
        after.model_vertices.len(),
        after.model_faces.len(),
        status.join("; ")
    ));
    assert_ne!(
        (after.model_vertices.len(), after.model_faces.len()),
        (57, 133),
        "our .poly through preprocess.exe now has upstream's counts: compare it byte for byte"
    );
    report.extend(made);

    for (i, r) in t.runs.iter().enumerate() {
        let (our_config, our_cbin) = export_config(
            &projects[i],
            &dir.join(format!("export{i}")),
            SolverKind::Spps,
        );
        // The .mbin, as upstream's run holds it: TetGen's attributes kept.
        let (with_upstream_ids, _) = tutorial3_mbin(&built, r, &r.config, |id| id);
        assert_eq!(
            byte_difference(&with_upstream_ids, &r.tetra_bytes),
            None,
            "run {i}: tetramesh.mbin"
        );
        // And as ours: the fittings under our ids, the room 0.
        let (our_mbin, ids) = tutorial3_mbin(&built, r, &our_config, |_| 0);
        assert_eq!(mbin_difference(&our_mbin, &r.tetra_bytes, &ids), None);
        report.push(format!(
            "run {i} tetramesh.mbin: our TetGen and builder on upstream's .poly give the run's, byte \
             for byte ({} bytes); ours is the same once idVolume is read through {ids:?}",
            our_mbin.len()
        ));
        // config.xml and mesh.cbin as parity_inputs.rs defines them.
        let original = parity::importable(&r.config);
        let got = parity::solver_differences(&original, &our_config);
        let mut expected = parity::tutorial3_ids_and_by_design();
        expected.push(format!(
            "configuration@workingdirectory: upstream '{}', ours '{}'",
            parity::working_folder(&r.config),
            parity::working_folder(&our_config)
        ));
        assert_eq!(got, parity::sorted(expected), "run {i}: config.xml");
        let en = parity::id_map(&r.config, &our_config, "encombrement");
        let rs = parity::id_map(&r.config, &our_config, "recepteur_surfacique");
        let faces = parity::face_differences(&r.mesh, &cbin::read(&our_cbin).unwrap(), &rs, &en);
        assert_eq!(faces, Vec::<String>::new(), "run {i}: mesh.cbin");
        report.push(format!(
            "run {i} config.xml and mesh.cbin: the original's (with the two edits), but the ids \
             (fittings {en:?}) and the differences by design"
        ));
    }
    print_report("tutorial 3", &report);
}

/// Tutorial 3's three SPPS runs, same seed, on the original inputs (with `parity::importable`'s two
/// edits) and on ours: our `config.xml` and `mesh.cbin`, and the `.mbin` our TetGen and builder
/// make of upstream's `.poly` ([`tutorial3`]) as our builder writes it, the fittings under our ids
/// and the room as 0 (decision 1).
///
/// When the results differ, the panic says whether the same `.mbin` with the room's parts kept as
/// TetGen numbered them (upstream's 2084 to 2086, as upstream writes them) gives the original's
/// results: SPPS gives every tetrahedron with a nonzero `idVolume` the fitting of that id, NULL for
/// an unknown one, and hands it to the tetrahedron's scene faces
/// (`coreinitialisation.cpp:151-176`); a room written 0 is skipped, so the faces a fitting's
/// tetrahedra share with the room keep the fitting, where upstream's room overwrites it.
///
/// Measured 2026-09-24: all 24 output files of each of the 3 runs differ with the room as 0, and
/// none with the room kept. So this test fails until decision 1 is reversed, which is Burhan's and
/// Michael's call: it is ignored in the plain suite, with that reason, and `tools/gates/parity.ps1`
/// runs it and reports it BLOCKED on exactly that signature, never passed.
#[test]
#[ignore = "BLOCKED by decision 1 (the room written as idVolume 0 changes SPPS's results on tutorial 3): tools/gates/parity.ps1 runs it"]
fn tutorial_3_same_seed_runs() {
    let Tutorial3 {
        t,
        dir,
        projects,
        built,
        ..
    } = tutorial3("t3r");
    let mut report = Vec::new();
    let mut failures = Vec::new();
    for (i, r) in t.runs.iter().enumerate() {
        let (our_config, our_cbin) = export_config(
            &projects[i],
            &dir.join(format!("export{i}")),
            SolverKind::Spps,
        );
        let original = parity::importable(&r.config);
        let cut = parity::id_map(&r.config, &our_config, "recepteur_surfacique_coupe");
        let (our_mbin, ids) = tutorial3_mbin(&built, r, &our_config, |_| 0);
        let (theirs, d) = same_seed(
            &format!("t3-{i}"),
            SolverKind::Spps,
            (&original, &r.mesh_bytes, &r.tetra_bytes),
            (&our_config, &our_cbin, &our_mbin),
            &cut,
        );
        if d.is_empty() {
            report.push(format!(
                "run {i}: all {} output files equal to the original inputs' run (idVolume {ids:?}, \
                 cutting plane {cut:?})",
                theirs.len()
            ));
            continue;
        }
        let (kept, kept_ids) = tutorial3_mbin(&built, r, &our_config, |id| id);
        let (_, dk) = same_seed(
            &format!("t3-{i}-kept"),
            SolverKind::Spps,
            (&original, &r.mesh_bytes, &r.tetra_bytes),
            (&our_config, &our_cbin, &kept),
            &cut,
        );
        failures.push(format!(
            "run {i}: {} of {} output files differ with idVolume {ids:?}, first {}; with the room's \
             parts kept as TetGen numbered them ({kept_ids:?}), {} differ",
            d.len(),
            theirs.len(),
            d[0],
            dk.len()
        ));
    }
    print_report("tutorial 3, same-seed runs", &report);
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

// ---------------------------------------------------------------------------------------------
// Every comparison says no

/// Each comparison of the bed, fed the input that must make it fail.
#[test]
fn the_comparisons_say_no() {
    let t = tutorial(parity::TUTORIAL1);
    // Bytes: one byte changed, and one byte more.
    let poly = entry(&t, "temp/scene_mesh.poly");
    assert_eq!(byte_difference(&poly, &poly), None);
    let mut bent = poly.clone();
    bent[100] ^= 1;
    assert!(
        byte_difference(&bent, &poly)
            .unwrap()
            .contains("first difference at byte 100")
    );
    let mut longer = poly.clone();
    longer.push(b'\n');
    assert!(byte_difference(&longer, &poly).is_some());

    // TetGen's files: the trailer alone is ignored; a digit is a value; a tie printed the other
    // way is text only.
    let node = entry(&t, "temp/scene_mesh.1.node");
    let text = String::from_utf8(node.clone()).unwrap();
    let retrailed = text.replace("# Generated by", "# Generated by another tetgen.exe,");
    let d = tetgen_difference(retrailed.as_bytes(), &node);
    assert_eq!((d.text_lines, d.value_lines), (0, 0));
    let mut lines: Vec<String> = text.lines().map(str::to_string).collect();
    lines[1].push_str(" 9");
    let d = tetgen_difference(lines.join("\n").as_bytes(), &node);
    assert_eq!((d.text_lines, d.value_lines), (1, 1), "{d:?}");
    // Tutorial 2's first tie: 0.0977344512939453125 exactly, printed ...312 by ours and ...313
    // in 2019. Both are that f64; a digit further up is another number.
    let theirs_tie = b"1  0.097734451293945313 0 0\n";
    let d = tetgen_difference(b"1  0.097734451293945312 0 0\n", theirs_tie);
    assert_eq!(
        (d.text_lines, d.value_lines),
        (1, 0),
        "the same f64 printed two ways"
    );
    let d = tetgen_difference(b"1  0.097834451293945313 0 0\n", theirs_tie);
    assert_eq!((d.text_lines, d.value_lines), (1, 1), "a different number");

    // The .mbin: the room read through the map passes; without the map, and with one node moved,
    // it does not.
    let theirs = &t.runs[1].tetra_bytes;
    let mut ours = mbin::read(theirs).unwrap();
    for tet in &mut ours.tetrahedra {
        tet.id_volume = 0;
    }
    let ours_bytes = mbin::write(&ours);
    let map = BTreeMap::from([(1, 0)]);
    assert_eq!(mbin_difference(&ours_bytes, theirs, &map), None);
    let d = mbin_difference(&ours_bytes, theirs, &BTreeMap::new()).unwrap();
    assert!(d.contains("dump line"), "{d}");
    ours.nodes[5][1] = f32::from_bits(ours.nodes[5][1].to_bits() + 1);
    let d = mbin_difference(&mbin::write(&ours), theirs, &map).unwrap();
    assert!(d.contains("node"), "{d}");

    // config.xml: one value the solver reads, changed (the source's 1 kHz power one f32 step up).
    let r = &t.runs[1];
    let db = parity::attr_in(&r.config, "<bfreq freq=\"1000\" db=", "db");
    let bumped = parity::next_float_text(db);
    let edited = edit_attr(&r.config, "<bfreq freq=\"1000\" db=", "db", &bumped);
    assert_eq!(
        parity::solver_differences(&r.config, &r.config),
        Vec::<String>::new()
    );
    assert_eq!(parity::solver_differences(&r.config, &edited).len(), 1);

    // Results: the original's SPPS inputs run with seed 1 and with seed 2 differ, and the first
    // differing value is named; the same seed twice gives no difference. TCR draws no random
    // numbers: the source moved 0.5 m is the input that changes its results.
    let none = BTreeMap::new();
    let mut spps_run = None;
    for kind in [SolverKind::Spps, SolverKind::Tcr] {
        let r = t.runs.iter().find(|r| r.solver == kind).unwrap();
        let config = short_run(&r.config, kind);
        let changed = match kind {
            SolverKind::Spps => edit_attr(&config, "<simulation ", "random_seed", "2"),
            SolverKind::Tcr => {
                let x = parity::attr_in(&config, "<source ", "x");
                let moved = format!("{}", x.parse::<f64>().unwrap() + 0.5);
                edit_attr(&config, "<source ", "x", &moved)
            }
        };
        let name = solver_name(kind);
        let root = bed_dir(&format!("no-{name}"));
        let a = run(
            &root.join("a"),
            kind,
            &config,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        let b = run(
            &root.join("b"),
            kind,
            &config,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        assert_eq!(
            output_differences(&a, &b, &none),
            Vec::<String>::new(),
            "{name}: the same inputs twice"
        );
        let c = run(
            &root.join("c"),
            kind,
            &changed,
            &r.mesh_bytes,
            &r.tetra_bytes,
        );
        let d = output_differences(&a, &c, &none);
        println!(
            "{name}, the input changed: {} files differ, first: {:?}",
            d.len(),
            d.first()
        );
        assert!(
            !d.is_empty(),
            "{name}: a changed input gave the same results"
        );
        assert!(
            d.iter()
                .all(|l| l.contains("dump line") || l.contains("byte") || l.contains("wrote it")),
            "{name}: each difference names its first value: {d:?}"
        );
        if kind == SolverKind::Spps {
            spps_run = Some(a);
        }
    }
    // A .csbin decoded: one energy one bit off is found, and the receiver id map is applied.
    let a = spps_run.unwrap();
    let bytes = a
        .iter()
        .find(|(k, _)| k.ends_with("Sound level.csbin"))
        .map(|(_, b)| b)
        .expect("a surface receiver file");
    let original = csbin::read(bytes).unwrap();
    assert_eq!(csbin_difference(original.clone(), &original, &none), None);
    let mut bent = original.clone();
    let face = bent.receivers[0]
        .faces
        .iter_mut()
        .find(|f| !f.records.is_empty())
        .unwrap();
    face.records[0].energy = f32::from_bits(face.records[0].energy.to_bits() ^ 1);
    let d = csbin_difference(original.clone(), &bent, &none).unwrap();
    assert!(d.starts_with("dump line"), "{d}");
    let index = original.receivers[0].xml_index;
    let mut renumbered = original.clone();
    renumbered.receivers[0].xml_index = index + 1000;
    assert!(csbin_difference(renumbered.clone(), &original, &none).is_some());
    let map = BTreeMap::from([(index + 1000, index)]);
    assert_eq!(csbin_difference(renumbered, &original, &map), None);
}

// ---------------------------------------------------------------------------------------------
// Upstream's shipped 1.3.4 and 1.4.0 solvers against ours

/// How far two runs' numbers are apart, over every file both wrote: `(values that differ, largest
/// absolute difference, largest relative difference)`. GABE float columns and `.csbin` energies
/// are compared value by value; a file that does not decode counts as one difference of NaN.
/// How far two runs' numbers are apart, over every file both wrote. GABE float columns and `.csbin`
/// energies are compared value by value, per file; a file that does not decode counts as one
/// difference of NaN.
#[derive(Debug, Default)]
struct Spread {
    /// Values whose bits differ.
    n: usize,
    /// Of those, values that differ other than by a NaN's sign.
    numeric: usize,
    /// The largest absolute difference.
    abs: f64,
    /// The largest relative difference among values at least 1e-3 of their file's largest
    /// magnitude (the rest, near-zero intensity components, give meaningless ratios).
    rel: f64,
}

impl Spread {
    fn file(&mut self, pairs: &[(f32, f32)]) {
        let top = pairs
            .iter()
            .flat_map(|&(a, b)| [a, b])
            .filter(|v| v.is_finite())
            .fold(0f32, |m, v| m.max(v.abs()));
        for &(a, b) in pairs {
            if a.to_bits() == b.to_bits() {
                continue;
            }
            self.n += 1;
            if a.is_nan() && b.is_nan() {
                continue;
            }
            self.numeric += 1;
            let (a, b) = (f64::from(a), f64::from(b));
            let d = (a - b).abs();
            self.abs = self.abs.max(d);
            let m = a.abs().max(b.abs());
            if m >= 1e-3 * f64::from(top) && m > 0.0 {
                self.rel = self.rel.max(d / m);
            }
        }
    }
}

fn value_spread(theirs: &Outputs, ours: &Outputs) -> Spread {
    let mut s = Spread::default();
    for (k, t) in theirs {
        let Some(o) = ours.get(k) else { continue };
        if t == o {
            continue;
        }
        let mut pairs = Vec::new();
        if k.ends_with(".csbin") {
            if let (Ok(t), Ok(o)) = (csbin::read(t), csbin::read(o)) {
                for (rt, ro) in t.receivers.iter().zip(&o.receivers) {
                    for (ft, fo) in rt.faces.iter().zip(&ro.faces) {
                        for (a, b) in ft.records.iter().zip(fo.records.iter()) {
                            pairs.push((a.energy, b.energy));
                        }
                    }
                }
                s.file(&pairs);
                continue;
            }
        } else if let (Ok(t), Ok(o)) = (gabe::read(t), gabe::read(o)) {
            for (ct, co) in t.columns.iter().zip(&o.columns) {
                if let (
                    gabe::ColumnData::Float { values: vt, .. },
                    gabe::ColumnData::Float { values: vo, .. },
                ) = (&ct.data, &co.data)
                {
                    pairs.extend(vt.iter().copied().zip(vo.iter().copied()));
                }
            }
            s.file(&pairs);
            continue;
        }
        s.n += 1;
        s.numeric += 1;
        s.abs = f64::NAN;
    }
    s
}

/// Upstream's shipped solvers against ours, on tutorial 1's original inputs with the bed's edits
/// (seed 1, 10,000 particles, 500, 1000 and 2000 Hz): SPPS and TCR of v1.3.4 (2020-12-23, the last
/// stable release) and of v1.4.0 (2026-01-14, the pinned 929a5c8, whose sources ours are built
/// from). `$SIMPA_RELEASE_BINARIES` names the folder holding the installed releases,
/// `inst134\core\{spps,classical_theory}\` and `inst140\`: upstream's installers are not in this
/// repository, so this test is ignored in the plain suite and run by `tools/gates/parity.ps1`,
/// which passes the folder. It panics when the variable or a solver is missing.
///
/// The measured answer is in `docs/m5-m6-design.md`, decision 3.
#[test]
#[ignore = "needs upstream's installed 1.3.4 and 1.4.0 releases: tools/gates/parity.ps1 runs it with SIMPA_RELEASE_BINARIES"]
fn shipped_1_3_4_and_1_4_0_solvers_against_ours() {
    let root = std::env::var_os("SIMPA_RELEASE_BINARIES")
        .map(PathBuf::from)
        .expect("SIMPA_RELEASE_BINARIES must name the folder holding inst134 and inst140");
    let exe = |p: &str| {
        let p = root.join(p);
        assert!(p.is_file(), "{} is missing", p.display());
        p
    };
    let t = tutorial(parity::TUTORIAL1);
    let mut summary = Vec::new();
    for (kind, ours, v140, v134) in [
        (
            SolverKind::Spps,
            solver_exe("spps.exe"),
            exe("inst140/spps.exe"),
            exe("inst134/core/spps/spps.exe"),
        ),
        (
            SolverKind::Tcr,
            solver_exe("classicalTheory.exe"),
            exe("inst140/classicalTheory.exe"),
            exe("inst134/core/classical_theory/classicalTheory.exe"),
        ),
    ] {
        let r = t.runs.iter().find(|r| r.solver == kind).unwrap();
        let config = short_run(&r.config, kind);
        let name = solver_name(kind);
        let dir = bed_dir(&format!("shipped-{name}"));
        let mut runs: Vec<(&str, Outputs)> = Vec::new();
        for (label, program) in [("ours", &ours), ("1.4.0", &v140), ("1.3.4", &v134)] {
            let d = dir.join(label.replace('.', ""));
            std::fs::create_dir_all(&d).unwrap();
            let wd = simpa_core::config_xml::working_directory(&d).unwrap();
            std::fs::write(
                d.join("config.xml"),
                edit_attr(&config, "<configuration ", "workingdirectory", &wd),
            )
            .unwrap();
            std::fs::write(d.join("mesh.cbin"), &r.mesh_bytes).unwrap();
            std::fs::write(d.join("tetramesh.mbin"), &r.tetra_bytes).unwrap();
            let run = parity::support::run_solver(program, &d);
            println!(
                "{name} {label} ({}): exit {:?}",
                program.display(),
                run.exit
            );
            assert_eq!(
                run.exit,
                Some(0),
                "{name} {label}: {}\n{}",
                run.stdout,
                run.stderr
            );
            runs.push((
                label,
                parity::support::outputs(&d, &["config.xml", "mesh.cbin", "tetramesh.mbin"]),
            ));
        }
        for (a, b) in [(0, 1), (0, 2), (1, 2)] {
            let (la, oa) = &runs[a];
            let (lb, ob) = &runs[b];
            let d = output_differences(ob, oa, &BTreeMap::new());
            let s = value_spread(ob, oa);
            let same: Vec<&String> = oa.keys().filter(|k| oa.get(*k) == ob.get(*k)).collect();
            let line = format!(
                "{name}: {la} against {lb}: {} of {} files differ; {} values differ ({} other than \
                 by a NaN's sign), largest {:e} absolute, {:e} relative (values at least 1e-3 of \
                 their file's largest){}; identical: {same:?}",
                d.len(),
                oa.len().max(ob.len()),
                s.n,
                s.numeric,
                s.abs,
                s.rel,
                if d.is_empty() {
                    String::new()
                } else {
                    format!("; first: {}", d[0])
                }
            );
            println!("{line}");
            for x in &d {
                println!("    {x}");
            }
            // Per file: how far apart, and for a surface receiver also each face's energy summed
            // over its time steps.
            for (k, t) in ob
                .iter()
                .filter(|(k, t)| oa.get(*k).is_some_and(|o| o != *t))
            {
                let one = BTreeMap::from([(k.clone(), t.clone())]);
                let other = BTreeMap::from([(k.clone(), oa[k].clone())]);
                let s = value_spread(&one, &other);
                let mut per_face = String::new();
                if k.ends_with(".csbin")
                    && let (Ok(x), Ok(y)) = (csbin::read(t), csbin::read(&oa[k]))
                {
                    let mut worst = 0f64;
                    for (rx, ry) in x.receivers.iter().zip(&y.receivers) {
                        for (fx, fy) in rx.faces.iter().zip(&ry.faces) {
                            let sx: f64 = fx.records.iter().map(|r| f64::from(r.energy)).sum();
                            let sy: f64 = fy.records.iter().map(|r| f64::from(r.energy)).sum();
                            let m = sx.abs().max(sy.abs());
                            if m > 0.0 {
                                worst = worst.max((sx - sy).abs() / m);
                            }
                        }
                    }
                    per_face = format!("; each face's energy summed over time: {worst:e} relative");
                }
                println!(
                    "      {k}: {} values differ, largest {:e} relative{per_face}",
                    s.n, s.rel
                );
            }
            summary.push(line);
            if (a, b) == (0, 1) {
                // Ours is the pinned 929a5c8 sources built as upstream builds them: bit for bit.
                assert_eq!(
                    d,
                    Vec::<String>::new(),
                    "{name}: ours against the shipped 1.4.0"
                );
            } else {
                // 1.3.4 is another build of other sources: it must differ, or this bed cannot tell
                // two builds apart. How much is measured and reported.
                assert!(!d.is_empty(), "{name}: {la} against {lb}: bit-identical");
            }
        }
    }
    println!("\n{}", summary.join("\n"));
}
