//! TetGen's command line: the flags a project's [`MeshSettings`] ask for, numbers spelled as
//! upstream spells them, and the command line TetGen records in its output trailer.

use serde::{Deserialize, Serialize};

use crate::schema::MeshSettings;

/// The flags for `settings`, in upstream's order: `[-a<v>] -pq<r> -A -n [-Y]`
/// (`isimpa/data_manager/projet_maillage.cpp:167-170`, with `appendparams` = `-Y` when
/// `preserve_boundary`). TetGen reads each switch wherever it stands, so the order is cosmetic.
/// Numbers are [`setting_g15`]: upstream holds both settings as `float`.
pub fn tetgen_flags(settings: &MeshSettings) -> Vec<String> {
    let mut flags = Vec::with_capacity(5);
    if let Some(v) = settings.max_volume_m3 {
        flags.push(format!("-a{}", setting_g15(v.get())));
    }
    flags.push(format!(
        "-pq{}",
        setting_g15(settings.min_radius_edge_ratio.get())
    ));
    flags.push("-A".to_string());
    flags.push("-n".to_string());
    if settings.preserve_boundary {
        flags.push("-Y".to_string());
    }
    flags
}

/// True when `settings` ask for a facet-area constraint (`.var`) together with `-Y`, which
/// forbids the facet splits the constraint asks for: the validator's `mesh_settings_conflict`
/// (`docs/m5-m6-design.md`, decision 3; `docs/formats/var.md`).
pub fn settings_conflict(settings: &MeshSettings) -> bool {
    settings.surface_receiver_max_area_m2.is_some() && settings.preserve_boundary
}

/// A meshing setting as upstream puts it on TetGen's command line: narrowed to the `float`
/// `param_TetGenMaillage` holds it in (`isimpa/data_manager/projet.h:98-99`), promoted back to
/// `double` for `Convertor::ToString`, and printed by [`to_string_g15`]. So q = 1.1 is
/// `1.10000002384186`, as upstream spells it; 2, 5, 1.5 and 100 are exact in `f32`.
pub fn setting_g15(v: f64) -> String {
    to_string_g15(f64::from(v as f32))
}

/// `v` as upstream's `Convertor::ToString(double, int precision = 15)` prints it
/// (`isimpa/manager/sppsString.cpp:91-98`, default at `stringTools.h:123`): an `ostringstream` in
/// the classic locale at precision 15 with the default float field, which is `%.15g`.
pub fn to_string_g15(v: f64) -> String {
    format_g(v, 15)
}

/// `printf("%.<precision>g", v)` as the UCRT prints it: `precision` significant digits of the
/// exact binary value rounded half to even, trailing zeros dropped, fixed notation for decimal
/// exponents from -4 to `precision - 1`, otherwise `d.ddde±XX` with at least two exponent digits.
pub fn format_g(v: f64, precision: usize) -> String {
    let p = precision.max(1);
    if v.is_nan() {
        return if v.is_sign_negative() { "-nan" } else { "nan" }.to_string();
    }
    let mut out = String::new();
    if v.is_sign_negative() {
        out.push('-');
    }
    let a = v.abs();
    if a.is_infinite() {
        out.push_str("inf");
        return out;
    }
    if a == 0.0 {
        out.push('0');
        return out;
    }
    // Rust's exact formatting rounds half to even on the binary value, as the UCRT does.
    let sci = format!("{a:.*e}", p - 1);
    let (mantissa, exponent) = sci.split_once('e').expect("{:e} has an exponent");
    let exp: i32 = exponent.parse().expect("{:e} exponent is an integer");
    let digits: Vec<u8> = mantissa.bytes().filter(u8::is_ascii_digit).collect();
    let trimmed = |s: &[u8]| s.iter().rposition(|&b| b != b'0').map_or(0, |i| i + 1);
    let push = |out: &mut String, s: &[u8]| s.iter().for_each(|&b| out.push(char::from(b)));
    if exp >= -4 && exp < p as i32 {
        if exp >= 0 {
            let int_len = exp as usize + 1;
            push(&mut out, &digits[..int_len]);
            let frac = &digits[int_len..];
            let n = trimmed(frac);
            if n > 0 {
                out.push('.');
                push(&mut out, &frac[..n]);
            }
        } else {
            out.push_str("0.");
            for _ in 0..(-exp - 1) {
                out.push('0');
            }
            push(&mut out, &digits[..trimmed(&digits)]);
        }
    } else {
        push(&mut out, &digits[..1]);
        let n = trimmed(&digits[1..]);
        if n > 0 {
            out.push('.');
            push(&mut out, &digits[1..1 + n]);
        }
        let sign = if exp < 0 { '-' } else { '+' };
        out.push_str(&format!("e{sign}{:02}", exp.unsigned_abs()));
    }
    out
}

/// The command line TetGen recorded in a file's trailer, `# Generated by <command line>`
/// (`tetgen.cxx:33684, 33963, 34172, 34479, 34999`). TetGen builds it by joining its `argv` with
/// spaces, a space after each, so the program path may itself hold spaces: the input file is the
/// last word, the flags are the run of `-` words without a path separator before it, and the
/// program is the rest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TetgenCommand {
    pub program: String,
    pub flags: Vec<String>,
    pub input: String,
}

/// The command line in the last `# Generated by ` line of a TetGen output file, if it has one.
pub fn trailer_command(text: &str) -> Option<TetgenCommand> {
    const PREFIX: &str = "# Generated by ";
    let line = text
        .lines()
        .rev()
        .find_map(|l| l.trim_end_matches('\r').strip_prefix(PREFIX))?;
    let words: Vec<&str> = line.split(' ').filter(|w| !w.is_empty()).collect();
    let (&input, rest) = words.split_last()?;
    // A switch starts with `-` and, unlike a path, holds no separator.
    let is_flag = |w: &str| w.starts_with('-') && !w.contains(['\\', '/']);
    let first_flag = rest.iter().rposition(|w| !is_flag(w)).map_or(0, |i| i + 1);
    if first_flag == 0 {
        return None;
    }
    Some(TetgenCommand {
        program: rest[..first_flag].join(" "),
        flags: rest[first_flag..].iter().map(|w| w.to_string()).collect(),
        input: input.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::F64;

    fn settings(q: f64, a: Option<f64>, area: Option<f64>, y: bool) -> MeshSettings {
        MeshSettings {
            min_radius_edge_ratio: F64::new(q),
            max_volume_m3: a.map(F64::new),
            surface_receiver_max_area_m2: area.map(F64::new),
            preserve_boundary: y,
        }
    }

    #[test]
    fn default_settings_are_upstreams_gui_default() {
        assert_eq!(
            tetgen_flags(&MeshSettings::default()),
            ["-pq5", "-A", "-n", "-Y"]
        );
    }

    #[test]
    fn the_box_fixture_gives_tutorial_2s_flags() {
        // tests/fixtures/rooms/tutorial1_box.simpa: q 2, .var 0.1 m², no -Y.
        let s = settings(2.0, None, Some(0.1), false);
        assert_eq!(tetgen_flags(&s), ["-pq2", "-A", "-n"]);
    }

    #[test]
    fn numbers_are_spelled_as_convertor_to_string() {
        assert_eq!(tetgen_flags(&settings(1.5, None, None, false))[0], "-pq1.5");
        let with_a = tetgen_flags(&settings(5.0, Some(100.0), None, true));
        assert_eq!(with_a, ["-a100", "-pq5", "-A", "-n", "-Y"]);
        // Upstream's settings are float: a value not exact in f32 prints as the float it is.
        let inexact = tetgen_flags(&settings(1.1, Some(0.3), None, false));
        assert_eq!(
            inexact,
            ["-a0.300000011920929", "-pq1.10000002384186", "-A", "-n"]
        );
        assert_eq!(to_string_g15(0.1), "0.1");
        assert_eq!(to_string_g15(f64::from(0.1f32)), "0.100000001490116");
        assert_eq!(to_string_g15(1e20), "1e+20");
        assert_eq!(to_string_g15(1.5e-5), "1.5e-05");
        assert_eq!(to_string_g15(0.0001), "0.0001");
        assert_eq!(to_string_g15(123456789012345.0), "123456789012345");
        assert_eq!(to_string_g15(1234567890123456.0), "1.23456789012346e+15");
        assert_eq!(to_string_g15(-2.5), "-2.5");
        assert_eq!(to_string_g15(-0.0), "-0");
    }

    #[test]
    fn the_conflict_needs_both_the_constraint_and_minus_y() {
        assert!(settings_conflict(&settings(5.0, None, Some(5.0), true)));
        assert!(!settings_conflict(&settings(5.0, None, Some(5.0), false)));
        assert!(!settings_conflict(&settings(5.0, None, None, true)));
    }

    #[test]
    fn the_trailer_gives_the_flags_even_with_spaces_in_the_program_path() {
        let text = "12      8     7     5    11\r\n# Generated by B:\\repos\\I-Simpa-upstream\\build_solvers\\src\\tetgen\\Release\\tetgen.exe -pq5 -A -n -Y scene_mesh.poly \r\n";
        let c = trailer_command(text).unwrap();
        assert_eq!(c.flags, ["-pq5", "-A", "-n", "-Y"]);
        assert_eq!(c.input, "scene_mesh.poly");
        assert!(c.program.ends_with("tetgen.exe"));
        let spaced = "# Generated by C:\\Program Files\\x -y\\tetgen.exe -pq2 -A -n model.poly \n";
        let c = trailer_command(spaced).unwrap();
        assert_eq!(c.program, "C:\\Program Files\\x -y\\tetgen.exe");
        assert_eq!(c.flags, ["-pq2", "-A", "-n"]);
        // No trailer, or one without a program, says so.
        assert_eq!(trailer_command("1 2 3\n"), None);
        assert_eq!(trailer_command("# Generated by -pq2 x.poly\n"), None);
    }
}
